### ISSUE TITLE
how to support airplay video

### ISSUE THREAD

**Issue by ruoying86** [FDH2/UxPlay#101]
UxPlay Highlights:
Support for both AirPlay Mirror and AirPlay Audio-only (Apple Lossless ALAC) streaming protocols from current iOS/iPadOS 15.4 clients.

this mean not support airplay video?

why not support airplay video

now i use uxplay can do airplay mirror , but youku push can only push sound

**Comment by monomycelium** [comment]
AirPlay Video is supported on UxPlay to mirror the screen of your iPhone, iPad, or iPod touch to your device. However, content from some streaming platforms like Apple TV and Netflix cannot be directly streamed because of DRM. If your content does not have DRM, see #44.

**Comment by ruoying86** [comment]
i use youku app push no video，log show ：ct=2 spf=352 usingScreen=0 isMedia=0  audioFormat=0x40000

what is wrong with usingScreen=0 or  isMedia=0  ？

i check #44，youtube_app_airplay_video.txt log，isMedia=1

log
[airplay_youku_no_video.txt](https://github.com/FDH2/UxPlay/files/8866192/airplay_youku_no_video.txt)

**Comment by fduncanh** [comment]
ct=2 spf=352 usingScreen=0 isMedia=0 audioFormat=0x40000

This is the Apple Airplay sound-only protocol.  (ALAC loss-free audio).   It does not send any video, even to a "real" Apple TV.

Apple music uses ALAC.     You need to use Airplay Mirror to send video from your iPad/iPhone screen.   There are **two** different icons on the iPad/iPhone.   One (two rectangles representing video screens)  for Airplay Mirror, one for AirPlay Audio-Only ( a triangle with circles of radio waves from its peak)

**Comment by ruoying86** [comment]
refer to https://github.com/antimof/UxPlay/issues/14
		https://github.com/FD-/RPiPlay/pull/146#issuecomment-675134133
		https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

E: Package 'gstreamer1.0-doc' has no installation candidate

raop_ntp receive timeout not fix

**Comment by ruoying86** [comment]
@fduncanh   UxPlay is not a full emulation of Apple TV, In particular it doesn't let the client run a http server on the server, which is probably what the YouTube app wants to do.
the note in https://github.com/antimof/UxPlay/issues/14，is mean Push video from YouTube app is not working fine with uxplay？the issue is only audio？

**Comment by fduncanh** [comment]
@ruoying86 

Unfortunately,  UxPlay cannot play video from YouTube.app directly, it can only play the sound in AirPlay-Audio-only ALAC mode,
like Apple Music.    Same is for AppleTv.app.   

* You can still watch YouTube.app in AirPlay-mirror mode, which shows what is playing on the screen.   You get the audio  in compressed AAC-ELD  format (not as good as loss-free ALAC).

* The AppleTV.app doesn't even mirror the screen with UxPlay. (the video stream doesn't seem to be h264?)

Since your redmi tv works some hacker could investigate how it does it, and what the protocal is.   Probably has extra encrytion.

This would be a major task for a talented hacker, unless someone already did it.



Here is how the protocol used by UxPlay was originally discovered.

https://www.itread01.com/hkeyxif.html

**Comment by fduncanh** [comment]
I think everything EXCEPT appletv.app can be see in AirPlay-Mirror mode. (use the iOS device icon for this, NOT the in-app  AirPlay icon)


https://support.apple.com/en-us/HT204289


appleTV.app  is "special":    It justs shows a black screen within a frame in mirror mode,  and you may even  have to shut down and restart the iPad/iPhone after trying to play appleTV.app on UIxPlay, before UxPlay will work again!  Some bad DRM seems to get startied on the iOS deveice that will not go away till you restart!

**Comment by fduncanh** [comment]
Re. installing gstreamer on ubuntu.:

* There is no package gstreamer1.0--doc in ubuntu.

* You don't need gstreamer-plugins-bad1.0-dev  for UxPlay.   See the README for what you need.

**Comment by fduncanh** [comment]
This is a feature request that can't be implemented at this time, because the protocol for it is unknown.

Also it would not be a good idea to incorporate an http server into uxplay, if that is what would be needed.

**Comment by ruoying86** [comment]
![airplay_youku_video](https://user-images.githubusercontent.com/34363113/174259868-9fa00d34-5a43-45c7-8bb8-b0220384dafd.png)
This is the interactive process of pushing youku video with airplay
The handshake protocol seems to be similar to audio
video interactive protocol uses the http protocol，need to support http server

Why  incorporate an http server into uxplay is not be a good idea？ the wireshark file seems to need  an http server

**Comment by fduncanh** [comment]
So long as there is no unknown encryption/decryption going on after pair verify I  suppose it could be done.

UxPlay uses the "legacyPairing" protocol in which all client server communication remains  not encrypted after pair verify.


The RpiPlay author noted that


**From captures of the traffic between an iOS device running iOS 12.2 and an AppleTV running tvOS 12.2.1, one can see that the communication on the main mirroring HTTP connection is encrypted after the initial handshake. This could theoretically be part of the new AirPlay 2 protocol. The AppleTV running tvOS 12.2.1 identifies as AirTunes/380.20.1. When connecting from the same iOS device to an AppleTV 3rd generation (reporting as AirTunes/220.68), the communication is still visible in plain. From the log messages that the iOS device produces when connected to an AppleTV 3rd generation, it becomes apparent that the iOS device is treating this plain protocol as the legacy protocol (as originally introduced with iOS 9). Further research showed that at the moment, all available third-party AirPlay mirroring receivers (servers) are using this legacy protocol, including the open source implementation of dsafa22, which is the base for RPiPlay. Given Apple considers this a legacy protocol, it can be expected to be removed entirely in the future. This means that all third-party AirPlay receivers will have to be updated to the new (fully encrypted) protocol at some point.**

**More specifically, the encryption starts after the pair-verify handshake completed, so the fp-setup handshake is already happening encrypted. Judging from the encryption scheme for AirPlay video (aka HLS Relay), likely two AES GCM 128 ciphers are used on the socket communication (one for sending, one for receiving). However, I have no idea how the keys are derived from the handshake data.**


You are welcome to  fork Uxplay and work on it!       Right now, Uxplay just (1) sets up cryptography pairing with the iOS device so it can decrypt the video and audio streams;  (2) sets up an ntp server to keep to audio and video timings correct so video matches audio; (3) streams separated video and audio streams with timestamps into separate GStreamer pipelines.


Adding a http:server would complicate things, and maybe be a security issue.    I personally would not have time to work on this, my contribution to UxPlay is now basically completed after adding support for ALAC audio-only  and now Raspberry PI with Video4Linux. (RpiPlay only does OpenMAX, which is no longer being supported on the PI)

**Comment by ruoying86** [comment]
the wireshark file：
[airplay_youku_video.txt](https://github.com/FDH2/UxPlay/files/8936942/airplay_youku_video.txt)
the client-server communications after pair verify are unencrypted。the server version is AirTunes/220.68 as expected
The data responded by the server is in plist format
Currently it can be confirmed that IOS 15.3.1 with AirTunes/220.68 server can work

**Comment by fduncanh** [comment]
Since things are not encrypted, it looks  possible to perhaps understand the protocol that is used for AitrPlay video streaming to smart tv's.


There is a lot of recent work on AirPlay2 audio for streaming synchronised sound to smart speakers etc.   (shairport-sync)
but I dont know any similar projects for video.      You would be taking on a big project if you try!.    Good luck if you do, it would  eat up a lot of your free time!   I'm sorry I cant help.

**Comment by thiccaxe** [comment]
FWIW I am doing some research on how the YouTube app airplays.
(On AppleTV3,1 - probably same for 3,2)

First thing I noticed is that 3 connections are negotiated /pair-verify etc.

Second thing is that the first connection makes a request GET /server-info which returns xml/plist (usually it is /info with bplist)

Third thing is that on the second connection, client makes the request POST /fp-setup2. I have not seen this url documented anywhere. It is in similar format to the second /fp-setup with a similar length of 164 bytes (have not counted)

I have yet to discover exactly what allows these alternate steps. However, one thing I found out is that with the current UxPlay dnssd "features" integer, YouTube will send only audio. However, change the dnssd features number to the one found in Apple TV 3 and YouTube will attempt to (and fail) to negotiate video AND audio with UxPlay.

Also, the Airplay client version number has been bumped in the iOS 16 beta 1 however they have not dropped support for Apple TV 3 (yet)

**Comment by fduncanh** [comment]
Re: iOS16.   We live in fear every major iOS version... !   Its not AppleTV3 that matters, its "LegacyPairing"  (bit 27)

There are lots of smart TV's that do AirPlay2  (except for AppleTV-app DRM)     There is as example in https://github.com/SteeBono/airplayreceiver/wiki/AirPlay2-Protocol (which is the wiki of a project that seems essentially to be a direct  transcription of (probably) dsafa22's code into c#).  Also @ruoying86 is reporting about a China smart-tv "redmi-tv".

If the smart-tv's use LegacyPairing it wont go away soon, I guess.    It would be useful to have reports.

**Comment by fduncanh** [comment]
@thiccaxe 
can you document the features integers (both Apple TV3 and Uxplay) you mention.
Both https://github.com/SteeBono/airplayreceiver/wiki/AirPlay2-Protocol and https://emanuelecozzi.net/docs/airplay2
have tables of the bit values  (neither are complete, but they  are consistent, use both) and translate the features integers.  into both hex and binary.    I am guessing it is bit 49 that is needed for airplay2 video. 

UxPlay seems to report 130367356919  = 0x1E5A7FFFF7= 1 1110 0101 1010 0111 1111 1111 1111 1111 0111

If I am interpreting this correctly 


```
63 0
62 0
61 0
60 0

59 0
58 0
57 0
56 0

55 0
54 0
53 0
52 0 SupportsSetPeersExtendedMessage

51 0 (no) SupportsUnifiedPairSetupAndMFi
50 0 (no) MetadataFeatures_3 "Send NowPlaying info via bplist" 
49 0 (no) SupportsAirPlayVideoV2
48 0 (no) SupportsCoreUtilsPairingAndEncryption     38 || 46 || 43 || 48

47 0
46 0 (no) SupportsHKPairingAndAccessControl
45 0
44 0

43 0 (no) SupportsSystemPairing
42 0 (no) SupportsScreenMultiCodec
41 0 (no) SupportsPTP "Bit needed for device to show as supporting multi-room audio"
40 0 (no) SupportsBufferedAudio "Bit needed for device to show as supporting multi-room audio"
39 0
38 0 (no) SupportsUnifiedMediaControl
37 0
36 1

35 1 (yes)  SupportsTLS_PSK
34 1 (yes) SupportsAirPlayFromCloud
33 1  (yes) SupportsAirPlayVideoPlayQueue
32 0  (no)  IsCarPlay/Supports Volume "Don’t read key from pk record it is known"

31 0 
30 1 (yes) HasUnifiedAdvertiserInfo
29 0
28 1


27 1 (yes) SupportsLegacyPairing |   |  
26 0 (no) InfoAuthentication_8 = 26 || 51 " MFi authentication"
25 1 
24 0

23 0  (no) authentication type 1 RSA authentication
22 1
21 1 (yes) AudioFormats_3 "support for audio format 4"
20 1 (yes) AudioFormats_2 "support for audio format 3. This bit must be set for AirPlay 2 connection to work"

19 1 (yes) AudioFormats_1 "support for audio format 2. This bit must be set for AirPlay 2 connection to work"
18 1 (yes) AudioFormats_0  "support for audio format 1"
17 1 (yes) MetadataFeatures_2 "Send NowPlaying info via DAAP"
16 1 (yes) MetadataFeatures_1 "Send track progress status to receiver"

15 1 (yes) MetadataFeatures_0 "Send artwork image to receiver"
14 1 (yes) Authentication_4   "FairPlay authentication"
13 1 (yes) PhotoCaching "photo preloading supported"
12 1 (yes) FPSAPv2pt5_AES_GCM "FairPlay secure auth supported"

11 1 (yes) AudioRedundant
10 1
9   1 (yes) SupportsAirPlayAudio "audio supported"
8   1 (yes) ScreenRotate "screen rotation supported"

7   1 (yes) SupportsAirPlayScreen
6   1
5   1 (yes) SupportsAirPlaySlideshow
4   1 (yes) VideoHTTPLiveStreams "http live streaming supported"

3   0  (no) volume control for videos
2   1 (yes) video protected with FairPlay DRM
1   1 (yes) SupportsAirPlayPhoto
0   1 (yes)  SupportsAirPlayVideoV1

```

**Comment by thiccaxe** [comment]
> Edit: AppleTV3 is already unsupported as far as activation is concerned. I picked up one for USD20 on ebay six months ago,
and erasing then reactivating it bricked it. It no longer can connect directly to the activation server, it seems. Luckily one can still activate it using Apple Configurator 2.app running on a Mac, with the Apple TV3 connected via usb (this is the app for changing MDM settings on corporate iOS devices), and there is some windows app that can also do this.

I purchased an Apple TV3,1 in January this year and was able to set it up without issue. Last time I checked it was able to use apple services. Perhaps it is due to something else such as region? not sure

> Re: iOS16. We live in fear every major iOS version... ! 

in the ios 16 beta one thing I noticed was that when a connection to UxPlay fails (as mentioned in prev. comment) ios 16 will 'drop' that apple tv from the airplay list. Unsure as to exactly what allows it to reappear. This could be a beta bug or a cause of some of the airplay changes.

**Comment by thiccaxe** [comment]
I use this website which provides a nice interface: https://openairplay.github.io/airplay-spec/features.html and seems to be the same data.

While UxPlay does indeed report 130367356919, that is in the HTTP connection with the plist. The clue is that it is a different integer in dnssdint.h: 0x5A7FFEE6. In this case it is actually good, 


UxPlay plist features integer is 130367356919 which is same as the one from AppleTV which is 61647880183 but with bit 36 enabled.

With the setup 0xE << 32 | 0x5A7FFFF7 in raop_bandlers.h and AIRPLAY_FEATURES:
- "0x5A7FFFF6", OK
- "0x5A7FFFF7", youtube will not play
- "0x5A7FFFE6", OK
- "0x5A7FFFE7", youtube will not play.
We can conclude that youtube looks for the video support bit only. 

for other apps like Vimeo, I have not tested as much but the behavior varies

**Comment by thiccaxe** [comment]
> I guess I cant see it on mine without wireshark?
you can use https://pyatv.dev use atvremote. Or you could use something like Avahi Zerconf Browser to see what the mDNS record of the apple tv is.

**Comment by fduncanh** [comment]
Re apple3,2 activation.   Probably they fixed the activation server.    At end of  December 2021 when I got mine,  when the reset  bricked it, I found a number of discussions (angry posts!) about this on the internet, which led me to  the apple configurator fix.

**Comment by fduncanh** [comment]
In particular:

Things change. Constantly. Here are a few things worth knowing about the protocols:

*    The DMAP protocol (suite) stems from iTunes and was used on all Apple TVs until tvOS 13, i.e. all versions of Apple TV 3 and earlier as well as Apple TV 4 (and later) until tvOS 13 was released. It means it’s not widely used anymore, other than with older devices. It can be used to control the Music app in macOS [[#1172](https://github.com/postlund/pyatv/issues/1172)].
 
*   The MRP protocol was introduced in tvOS when the Apple TV 4 was introduced. In tvOS 15, it was demoted from a separate protocol (it used to have it’s own Remote app as well as Zeroconf service, _mediaremotetv._tcp.local) and moved to a special stream type in AirPlay 2 instead. Devices running tvOS 15 (beta or later) require AirPlay to be set up to function properly.

*    tvOS 10.2 enforced “device authentication” for AirPlay to function. This is referred to as “legacy pairing” and is only used to verify a connection, it does not enforce any encryption. It also works for RAOP. AirPlay 2 however require “HAP” (HomeKit) authentication, which enforce encryption. Only legacy pairing is supported for RAOP in pyatv at the moment (as encryption has n

**Comment by fduncanh** [comment]
@thiccaxe 
so you are basically reporting that  0x5A7FFFF7 in plist should change to 0x5A7FEE6?

the change in dnssdint.h occurred 
[here](https://github.com/FD-/RPiPlay/pull/107/commit/01155dd4e52881bdf77a1da8f76da36981db9691) in RPiPlay, without the corresponding change being made in the plist in raop_handlers.h

**Comment by fduncanh** [comment]
@thiccaxe 
I fixed the plist to in raop_handlers.h to take values from dnssdint.h, so its now 0x5A7FEE6

https://github.com/FDH2/UxPlay/commit/63092afcd6daf8cc0e298683b3f9a38d4f1695e0

but I dont see that youtube is behaving differently.   Its either in airplay-mirror mode, or airplay-audio without video.
Am I missing something?

**Comment by thiccaxe** [comment]
Sorry, I can see now that my previous comment was confusing.

The idea is that iOS will look at the mDNS features record of the Apple TV first, to figure out if it supports (for example, in the YouTube case, the Video bit). Based on that it will continue to either screen mirror, or use the http link stream.

the features value sent in the plist does not affect this decision and is (was) fine. I have not tested with the feature value from dnssdint.h but for UxPlay's use of video (screen mirroring) everything should work fine.

**Comment by fduncanh** [comment]
@thiccaxe 

In any case, the inconsistent plist seems to be an error (with no consequences) introduced in RPiPlay when the features were changed
(..FF7 -> ..EE6)  away from those of the  AppleTV3 in dnsssdint.h but not in raop_handlers.h that originally had a binary copy of the plist taken from the AppleTV, which was then transcribed into plist from.

But what exactly did you test (what was changed and where?)
 I guess I didn't understand

**Comment by fduncanh** [comment]
Your tests were with UxPlay or with the real AppleTV3?  I'm still confused!

This is what I have done in dnssdint.h:
(the plist in raop_handlers_.h now takes features =  AIRPLAY_FEATURES_2 << 32 | AIRPLAY_FEATURES_1 
(after converting strings to uint64_t)

the change  5A7FFFF7 to 5A7FFFE6   seems to have been make for the reasons you find.
(the later change 5A7FFFE6  to 5A7FFEE6 is to do with rotating the ipad which changes between portrait and  landscape

But I am not sure what to look for on youtube.


```
#define RAOP_TXTVERS "1"
#define RAOP_CH "2"             /* Audio channels: 2 */
#define RAOP_CN "0,1,2,3"       /* Audio codec: PCM, ALAC, AAC, AAC ELD */
#define RAOP_ET "0,3,5"         /* Encryption type: None, FairPlay, FairPlay SAPv2.5 */
#define RAOP_VV "2"
#define FEATURES_1 "0x5A7FFEE6" /* first 32 bits of features */
#define FEATURES_2 "0x0"        /* second 32 bits of features */
#define RAOP_FT FEATURES_1 "," FEATURES_2
#define RAOP_RHD "5.6.0.0"
#define RAOP_SF "0x4"
#define RAOP_SV "false"
#define RAOP_DA "true"
#define RAOP_SR "44100"         /* Sample rate: 44100 */
#define RAOP_SS "16"            /* Sample size: 16 */
#define RAOP_VS GLOBAL_VERSION  /* defined in global.h */
#define RAOP_TP "UDP"           /* Transport protocol. Possible values: UDP or TCP or TCP,UDP */
#define RAOP_MD "0,1,2"         /* Metadata: text, artwork, progress */
#define RAOP_VN "65537"
#define RAOP_PK "b07727d6f6cd6e08b58ede525ec3cdeaa252ad9f683feb212ef8a205246554e7"

/* use same features for RAOP and AIRPLAY: is this correct? */
#define AIRPLAY_FEATURES_1 FEATURES_1
#define AIRPLAY_FEATURES_2 FEATURES_2
#define AIRPLAY_FEATURES  AIRPLAY_FEATURES_1 "," AIRPLAY_FEATURES_2 
#define AIRPLAY_SRCVERS GLOBAL_VERSION /*defined in global.h */
#define AIRPLAY_FLAGS "0x4"
#define AIRPLAY_VV "2"
#define AIRPLAY_PK "b07727d6f6cd6e08b58ede525ec3cdeaa252ad9f683feb212ef8a205246554e7"
#define AIRPLAY_PI "2e388006-13ba-4041-9a67-25dd4a43d536"
```

**Comment by fduncanh** [comment]
@thiccaxe  

Yes, I verified your report that the important thing for youtube.app to play in uxplay mirror mode  is that the features code  in _airplay._tcp has bit 0 switched off.   This is what is advertised in mDNS_SD     It doesn't  seem to care about _raop._tcp  or the plist list, it seems.

It seems correct to make all three places where features are reported consistent.

**Comment by thiccaxe** [comment]
I have done some wireshark debugging, and it seems that a DMAP (port 3689) server is required for apps like YouTube to function. (this makes sense, as DMAP has API for scrubbing, pause/play, etc., see https://pyatv.dev/documentation/protocols/#digital-media-access-protocol-dmap) I think that this is now well out of scope for UxPlay, in addition to the required http client and will work on a fork.

Additionally, there is no need to clutter here aswell.

Best of luck

**Comment by fduncanh** [comment]
@thiccaxe A fork is a good idea.    

 I believe that the UxPlay codebase  has advanced a bit from RPiPlay, and even the 2019 dsafa22 sources,
with some fixes and better understanding of the RAOP  protocol,   but it is  basically finished, for what it is.    Its use with an iPad with Apple pencil for online teaching with Zoom on linux was an important initial  motivation for this fork.    Adding support for video streaming with a http client and DMAP  is a new direction, and should be a new forked project .

I se the POST/scrub requests in @ruoying86 's post above.  Yes that seems to be DMAP.

Happy forking!    The pyatv.dev site seems very useful!   Maybe it has details of  non-Legacy authentication protocols?

**Comment by thiccaxe** [comment]
On YouTube version 17.46.4 on UxPlay latest 1.16.1, airplaying from the youtube in-app casting button works - only audio (previously, youtube app would hang).
Seems to work as far back as Uxplay 1.53, so most likely a change on youtube's end.
