### ISSUE TITLE
GStreamer-CRITICAL ** error when executing ./uxplay

### ISSUE THREAD

**Issue by suyash-srivastava-dev** [FDH2/UxPlay#102]
I am not sure if this is the correct place to ask but below is my query.

It was working great with Ubuntu 20.04 , but as I updated to 22.04 . I am now getting below errors for GStreamer. Can anyone suggest on this ?

(uxplay:44148): GStreamer-CRITICAL **: {{numbers}}: gst_caps_from_string: assertion 'string' failed

(uxplay:44148): GStreamer-CRITICAL **: {{numbers}}: gst_pad_template_new: assertion 'caps != NULL' failed

(uxplay:44148): GStreamer-CRITICAL **: {{numbers}}: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(uxplay:44148): GStreamer-CRITICAL **: {{numbers}}: gst_element_class_add_pad_template: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed

(uxplay:44148): GStreamer-Video-CRITICAL **: {{numbers}}: gst_video_decoder_init: assertion 'pad_template != NULL' failed

(uxplay:44148): GStreamer-WARNING **: {{numbers}}: Element vaapidecode0 has an ALWAYS template src, but no pad of the same name

**Comment by fduncanh** [comment]
probably vaapi issue.   Uxplay is tested on Ubunbtu-22.04   


try 

uxplay -avdec


(try reading README where this is discussed!)

**Comment by suyash-srivastava-dev** [comment]
Thanks for the input, it works with this
./uxplay -avdec
