### ISSUE TITLE
connection fail

### ISSUE THREAD

**Issue by coldairance** [FDH2/UxPlay#110]
i wonder why?
my ufw is disabled and i start the uxpaly by specifying ports，but my iphoneXr(15.2.1)，ipad6(15.3.1) both fail to build connection
the terminal show nothing：
![image](https://user-images.githubusercontent.com/67637508/178215309-0a35cd31-55b1-42fe-91a4-149832ec4494.png)
![image](https://user-images.githubusercontent.com/67637508/178217552-7c608bad-581d-4b49-bb63-0bf34af350f2.png)
my system is:
```
Linux version 5.13.0-52-generic (buildd@lcy02-amd64-067) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 
GNU ld (GNU Binutils for Ubuntu) 2.34) #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022
```

**Comment by thiccaxe** [comment]
Does it work when ports are not manually set?

**Comment by coldairance** [comment]
Ok, it's my router goes wrong, I opend hot spot by wired mode or iphone,
ipad and laptop connected it and the uxplay worked well.First I thought it's my
vlan that didn't close, but when I closed it, it still didn't work well, maybe something else is wrong.

**Comment by fduncanh** [comment]
This seems resolved?
