### ISSUE TITLE
Failed to compile with lto

### ISSUE THREAD

**Issue by PetrusZ** [FDH2/UxPlay#111]
Use lto with CFLAGS=-flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing.

Got an error:

```
/var/tmp/portage/media-video/uxplay-1.54/work/UxPlay-1.54/renderers/video_renderer.h:53:6: error: type of ‘video_renderer_flush’ does not match original declaration [-Werror=lto-type-mismatch]
```

This bug is orignal discovered on bugs.gentoo.org, https://bugs.gentoo.org/860183 .

**Comment by fduncanh** [comment]
thanks!   fixed!

( I think this empty function is never called, it was used in RPiPlay by the omx driver)
