### ISSUE TITLE
Pin Code Authentication before starting Mirroring. 

### ISSUE THREAD

**Issue by malikAr** [FDH2/UxPlay#113]
Hi @fduncanh, I have one requirement that when a user starts mirroring it must ask for some type of code for authentication. once the user enters a valid code then only mirroring starts.

Code is read by UXPlay from some kind of file or some random code self-generated by UXPlay.

**Comment by fduncanh** [comment]
This is required by AppleTV but not by UxPlay.   But  if MDM (Mobile device management) is imposed (e.g. on a corporate iOS device)  the iOS client may require it.   I think this is for corporate security so company information is not downloaded or streamed to an impostor appleTV.

I'm assuming your issue involves MDM.  correct me if I am wrong.

Currently UxPlay responds with an error message when a pin is requested. At raop.c line  213:
```
    } else if (!strcmp(method, "POST") && !strcmp(url, "/pair-pin-start")) {
       logger_log(conn->raop->logger, LOGGER_ERR,  "*** ERROR: Unsupported client request %s with URL %s", method, url);
       logger_log(conn->raop->logger, LOGGER_INFO, "*** AirPlay client has requested PIN as implemented on AppleTV,");
       logger_log(conn->raop->logger, LOGGER_INFO, "*** but UxPlay does not require a PIN and cannot supply one.");
       logger_log(conn->raop->logger, LOGGER_INFO, "*** This client behavior may have been required by mobile device management (MDM)");
       logger_log(conn->raop->logger, LOGGER_INFO, "*** (such as Apple Configurator or a third-party MDM tool).");
```
In principle it is known how this pin protocol works, but its too much a minority requirement to justify implementing it (lots of cryptography). see:

https://htmlpreview.github.io/?https://github.com/philippe44/RAOP-Player/blob/master/doc/auth_protocol.html

If a "pull request" from a fork with a working implementation is proposed, I'll consider it.

Apple configurator can be used to modify MDM restrictions on iOS devices.

**Comment by fduncanh** [comment]
Most of the articles linked to above are from the point of view of a (linux)  emulation of an **iOS client** interacting with with a **real AppleTV**.


Your case is the opposite. It could be much easier to implement if  it really was worth doing.   It would still mean a new pin would have to be supplied each time the client connects, because there would be no stored history of earlier client-server pairing

**Comment by malikAr** [comment]
Thanks, @fduncanh. Let me check mentioned point.

**Comment by fduncanh** [comment]
this is relevant
https://github.com/FDH2/UxPlay/issues/33

**Comment by fduncanh** [comment]
Solution for you is to remove the Mobile Device Management rule that the iOS client must authenticate with a PIN (see #33).

To add  the pair-pin-start feature to UxPlay seems far too involved cryptographically, and rarely useful, though the information on how to do it is probably known by now at https://github.com/postlund/pyatv.   If you want to try, post back.

**Comment by Booth1983** [comment]
Generally a pin could be a good idea. We using uxplay in my schoolnetwork and everyone within the network can connect, not only the students in the classroom.
This could be prevented by a pin.

**Comment by Booth1983** [comment]
I'll take a look at it as soon as it's released (and I have time to install it on one of my systems). Thank you for your time so far.
