### ISSUE TITLE
Question: can UxPlay be used for desktop mirroring in a virt-manager VM running Debian 11?

### ISSUE THREAD

**Issue by gnutechie** [FDH2/UxPlay#115]
I'm looking into creating multiple workstations on one host computer based on VMs. I tried using USB to HDMI adapters but those from Displaylink are pretty finnicky and so far I've made them work only with Windows VMs. I want a GNU/Linux solution so I thought of screen mirroring. Has anyone tried or used UxPlay and an Anycast Dongle for the same use case?

Thanks in advance

**Comment by fduncanh** [comment]
Only works with Apple's AirPlay Mirror protocol.    Works as a second screen for Apple computers running macOS.

It can also work with a proprietary (paid) Windows AirPlay emulator software called AirMyPc.    This was added for a teacher
with a mixed classroom of kids with iPads and Windows  tablets mirroring to a Linux server.

UxPlay doesn't do other casting protocols.
