### ISSUE TITLE
No video or audio sent despite reported successful connection

### ISSUE THREAD

**Issue by kosmas12** [FDH2/UxPlay#120]
Hi!

I wanted to set up an AirPlay server on my Linux computer to help my cousin mirror his iPad to it so he has a bigger screen. So for this, I downloaded the UxPlay source code and compiled it with the commands the README suggested. When we connected the first time around, it worked. But after that, the iPad and UxPlay report a successful connection, but no audio is transmitted (except for one time where it did send audio randomly) and no window opens for video to transmit either. I am not exactly sure how to fix this. The steps I have tried so far are rebooting, recompiling, using `glimagesink`, `ximagesink` and `xvimagesink`. None of them have worked. I have also tried `-avdec` to no avail. I also tried disabling `ufw`, the preinstalled firewall.

My computer runs Linux Mint 21 with Nvidia driver 515
The iPad is an 8th gen iPad running iPad OS 15.6.1

I can gather and provide more info if needed. Thanks in advance!

**Comment by LockonS** [comment]
Not sure what happened and if not done, please check system's audio setting first. Probably already checked.
In that case may I suggest to use pulseaudio and see if the problem can be solved. Pulseaudio's audio sink is `pulsesink`. 

```
# an example
uxplay -vs xvimagesink -as pulsesink
```

**Comment by fduncanh** [comment]
1. go through the troubleshooting section of the UxPlay README
2.  does the -d (debug) show anything wrong?  You can compare it with correcet debug output in the UxPlay wiki

**Comment by fduncanh** [comment]
any resolution?

**Comment by fduncanh** [comment]
seems this issue is no longer active?  reopen if needed
