### ISSUE TITLE
Wrong Colors 

### ISSUE THREAD

**Issue by Chebbo314** [FDH2/UxPlay#129]
Hi Im new to the whole raspberry game,
my Problem is that the colors of the stream are the wrong ones.
Blue = orange
etc.

I tired -bt709 and different video encoders
anyone a idea?

**Comment by fduncanh** [comment]
you are probably using framebuffer video.    (no X11)

use  uxplay -vs kmssink    for framebuffer video.
 also may need -bt709

**Comment by fduncanh** [comment]
@Chebbo314  did using -vs kmssink (maybe with -bt709 as well) fix your problem?  if not please give more details
about with operating system, X11 or not, etc.

**Comment by Chebbo314** [comment]
@fduncanh yep tested it a few minutes ago thank you very much !
