### ISSUE TITLE
The raop_handler_setup response eventPort will create a new http link

### ISSUE THREAD

**Issue by heweisheng** [FDH2/UxPlay#130]
The transmission of eventPort will lead to the creation of a new http connection, but what is the function of this connection? Instead of transmitting, I can reduce an http connection.
![image](https://user-images.githubusercontent.com/37769332/190302013-957ce036-bae1-4139-8769-f99885592210.png)

**Comment by fduncanh** [comment]
I believe the event port receives things ("events") like volume changes on the client.
You could learn more by studying the code or looking at some of the various descriptions  of RAOP that can be found.  (see the README for some links).
