### ISSUE TITLE
Windows Fullscreen support

### ISSUE THREAD

**Issue by xshrinix** [FDH2/UxPlay#133]
I am currently using uxplay in windows environment. Is there any possible way to use fullscreen mode?
I wanted to remove the title bar also (Shown in the screenshot). 
Command i am using is - uxplay.exe -n AirplayRec -nh -s 1920x1080@60 -as "wasapisink low_latency=true" -vs glimagesink.
device - Ipad.
![Screenshot (15)](https://user-images.githubusercontent.com/17141022/193206248-7782d4cb-c321-4f9e-959a-bd3da1b6abd2.png)

**Comment by fduncanh** [comment]
Try using the -fs option which will work if "fullscreen=true" is an option of the videosink being used by GStreamer.   (On Linux this works for waylandsink and vaapisink)

I am not familiar with the Windows videosinks and possible choices among them.  If you don't specify which one to use, the "autovideosink" algorithm chooses one for you.

Find out which videosink is being used by gstreamer, and what choices are availble.
(and what extra options they support)

export GST_DEBUG=2   (or maybe 4,5 6 etc) may allow you to work out which one.

**Comment by fduncanh** [comment]
OK  I tested.

what you want is 

```
uxplay -vs "d3d11videosink fullscreen-toggle-mode=alt-enter"
```
(plus any other options)

You toggle into an out of full-screen mode with the alt+enter key combination.

**Comment by fduncanh** [comment]
The info about fullscreen mode has been added to the Windows section of the README.

**Comment by xshrinix** [comment]
Thanks for the quick reply. Provided solution worked out for me.

**Comment by fduncanh** [comment]
yesterday I did a new small update that makes  the option that allows alt-enter for fullscreen  the default for -vs d3d11video.

If you didnt get that version, its on github now.
