### ISSUE TITLE
no element "avdec_aac"

### ISSUE THREAD

**Issue by attrobit** [FDH2/UxPlay#138]
Hey,

when i start the newest version of UxPlay i got the following error:
`
** (uxplay:86164): ERROR **: 18:03:38.661: gst_parse_launch error (audio 1):
 no element "avdec_aac"

[1]    86164 trace trap (core dumped)  ./uxplay
`
I use Fedora 36 Workstation and installed all the libraries.

**Comment by fduncanh** [comment]
* Red Hat, Fedora, CentOS (now continued as Rocky Linux or Alma Linux): (sudo yum install) openssl-devel libplist-devel avahi-compat-libdns_sd-devel (some from the "PowerTools" add-on repository) (+libX11-devel for ZOOMFIX). The required GStreamer packages (some from [rpmfusion.org](https://rpmfusion.org/)) are: gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-libav gstreamer1-plugins-bad-free (+ gstreamer1-vaapi for intel graphics).

you have not installed gstreamer-1-libav (or maybe redhat dont give you a complete version, in that case get it from rpmfusion.org )

examine your gstreamer installation with
 ```
gst-inspect-1.0   libav
```

with `gst-inspect-1.0 | grep aac` I get

```
% gst-inspect-1.0 | grep aac    
audioparsers:  aacparse: AAC audio stream parser
faac:  faac: AAC audio encoder
libav:  avdec_aac: libav AAC (Advanced Audio Coding) decoder
libav:  avdec_aac_at: libav aac (AudioToolbox) decoder
libav:  avdec_aac_fixed: libav AAC (Advanced Audio Coding) decoder
libav:  avdec_aac_latm: libav AAC LATM (Advanced Audio Coding LATM syntax) decoder
libav:  avenc_aac: libav AAC (Advanced Audio Coding) encoder
libav:  avenc_aac_at: libav aac (AudioToolbox) encoder
libav:  avmux_adts: libav ADTS AAC (Advanced Audio Coding) muxer (not recommended, use aacparse instead)
typefindfunctions: audio/aac: aac, adts, adif, loas
```

**Comment by attrobit** [comment]
my output is:
`gst-inspect-1.0 | grep aac
audioparsers:  aacparse: AAC audio stream parser
fdkaac:  fdkaacdec: FDK AAC audio decoder
fdkaac:  fdkaacenc: FDK AAC audio encoder
libav:  avmux_adts: libav ADTS AAC (Advanced Audio Coding) muxer (not recommended, use aacparse instead)
typefindfunctions: audio/aac: aac, adts, adif, loas`

So i will install it from rpmfusion. Thanks for your help!

**Comment by fduncanh** [comment]
This  is output from a (non-RedHat) linux install (what I posted earlier was from macOS)

```
gst-inspect-1.0 | grep aac
audioparsers:  aacparse: AAC audio stream parser
fdkaac:  fdkaacdec: FDK AAC audio decoder
fdkaac:  fdkaacenc: FDK AAC audio encoder
libav:  avdec_aac: libav AAC (Advanced Audio Coding) decoder
libav:  avdec_aac_fixed: libav AAC (Advanced Audio Coding) decoder
libav:  avdec_aac_latm: libav AAC LATM (Advanced Audio Coding LATM syntax) decoder
libav:  avenc_aac: libav AAC (Advanced Audio Coding) encoder
libav:  avmux_adts: libav ADTS AAC (Advanced Audio Coding) muxer (not recommended, use aacparse instead)
typefindfunctions: audio/aac: aac, adts, adif, loas
```
yes you are missing all the libav: avdec_aac (and avenc_aac)  plugins.    Uxplay tests for  libav and exits gracefully if it is absent,  but  you got past that test with an incomplete libav.   I can't halt uxplay if avdec_aac is missing since it is only used for software (cpu) decoding.   There are other aac decoders used in hardware (gpu) decoding, so a missing avdec_aac is not necessarily fatal.
