### ISSUE TITLE
No issues yet? Let's change that :-)

### ISSUE THREAD

**Issue by uxch** [FDH2/UxPlay#145]
first: great tool, love it.
second: maybe noob question, and I don't have exact version numbers from before, so accept my apologies.
I'm on 1.58 (AUR) and while the server appears on my iOS devices, none of them (15.x/16.0.2) can connect (`uxplay -m -nh -n [..]`). Is this a known issue? `-d ` produces no outpout after init:

```
uxplay -d                                                                                               
supported audio format 1: AAC-ELD 44100/2
supported audio format 2: ALAC 44100/16/2
GStreamer video pipeline will be:
"appsrc name=video_source ! queue ! h264parse ! decodebin ! videoconvert ! autovideosink name=video_sink sync=false"
Initialized GStreamer video renderer
using system MAC address D0:NA:LD:SS
Initialized server socket(s)
```

It's no trouble, I am just wondering. Thanks everyone for writing free software.

**Comment by thiccaxe** [comment]
Is whatever port UxPlay uses open on your firewall?
You may need to explicitly allow UDP/TCP on some 5 ports and configure UxPlay to use those

**Comment by fduncanh** [comment]
Please read "Troubleshooting" section of README on website or  in your documentation folder

**Comment by fduncanh** [comment]
problem is probably resolved.  Please close if it is

**Comment by uxch** [comment]
Thanks for getting back and the link (and sorry for replying a bit late). I do not use a firewall, if I want to lull myself into a false sense of security, I use anti-virus software :-) But I did a quick pgrep just to make sure. I don't want to be _that_ user with two firewalls. I'll investigate a bit more on my side, just wantedf to make sure it's not a dumb mistake everybody knows about but me. Also, I'll close thre issue, because I am a big fan of zero inbox, and wish you the same zero-issues bliss.
