### ISSUE TITLE
You should add the possibility to install UxPlay via repository in README.md

### ISSUE THREAD

**Issue by All3xJ** [FDH2/UxPlay#147]
For people less experience, you should write in plain sight that you can install it via repo, for example in Ubuntu:

`sudo apt install uxplay`

**Comment by fduncanh** [comment]
Its in there, before the build-it-yourself instructions.   Maybe could be clearer.

**Comment by fduncanh** [comment]
Fixed. See https://github.com/FDH2/UxPlay

**Comment by All3xJ** [comment]
> Fixed. See it at https://github.com/FDH2/UxPlay
> 
> text is
> 
> Linux distributions providing prebuilt uxplay packages include Debian "testing" (Bookworm), Ubuntu (since 22.04), and Ubuntu derivatives (install with "sudo apt install uxplay"). To easily build latest UxPlay from source, or for guidance on required GStreamer plugins, see [Getting UxPlay](https://github.com/FDH2/UxPlay#getting-uxplay) below. Raspberry Pi users see [here](https://github.com/FDH2/UxPlay/wiki/Gstreamer-Video4Linux2-plugin-patches).

Great, I'd also add a paragraph to put that text inside, such us: "Pre-built binaries" just before "Building UxPlay on Linux (or *BSD)" paragraph

**Comment by fduncanh** [comment]
This new text is not "buried" in the Getting Uxplay section, it is right at the top of the README  page , so it's very obvious now I think.

Thanks for your suggestion about this.
