### ISSUE TITLE
Is it possible to avoid using `git push -f` ?

### ISSUE THREAD

**Issue by sihuan** [FDH2/UxPlay#148]
Hi, I'm building the `uxplay-git` package for the [archlinuxcn repo](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/uxplay-git). It uses the latest commit build and uses `printf  "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"` as the version number.
It looks like this repo sometimes does a `git push -f` which causes the commit count to fall back, which causes the version number to fall back and our users can't update (in fact our build bot refuses to push updates to the user because the new package looks "older")
Is it possible to avoid using `git push -f`, please?

**Comment by fduncanh** [comment]
@sihuan 
I am sorry, but I just had to do a git push -f  again.
(after an accidental very bad commit accident that needed immediate reversal)

I am trying not to do this any more, but sometimes things happen

**Comment by sihuan** [comment]
> @sihuan I am sorry, but I just had to do a git push -f again. (after an accidental very bad commit accident that needed immediate reversal)
> 
> I am trying not to do this any more, but sometimes things happen

It's okay. I'm going to use the `build date-commit hash` as the package version number, so that won't be a problem.
