### ISSUE TITLE
Does not play when streaming audio only

### ISSUE THREAD

**Issue by notthewave** [FDH2/UxPlay#15]
Segfaulted twice, not sure what causes it (on audio only).
```
raop_rtp audio: ntp = 1632842560238364, now = 1632842563331949, latency=3093585, rtp=1961122080
zsh: segmentation fault  ./uxplay -p -d -vs ximagesink -s 1280x720
```
There is not much useful output other than that :(

**Comment by fduncanh** [comment]
Streaming radio from iPad music works, but this is still screen mirroring with a fixed iPad screen image showing.  I don't have an audio-only source I can think of to test.   Can you suggest one? UxPlay 1.35  is a descendent of https://github.com/FD-/RPiPlay 
and https://github.com/antimof/UxPlay.   If you can make either of these work for audio without screen mirroring, its probable that audio-only on UxPlay 1.35 can be fixed.   You should copy or put a symlink to dns_sd.h in /usr/include to get these to compile, I guess.  You'll have to investigate this.   

The motivation of UxPlay/RPiPlay has been Airplay mirroring, so I dont know about audio only.

**Comment by fduncanh** [comment]
getting audio only might be as easy as just not starting a video renderer.  At present, a video renderer always gets started, which might cause the segfault if there is no video stream.

try compiling a version of uxplay with lines 506-510 and 521 of  uxplay.cpp commented out  (//....) , and testing with an audio-only source.

If this works a no-video option is easily added.

**Comment by fduncanh** [comment]
@notthewave
 
comment out (with // ) lines 92 and 98 as well as line 521 of uxplay.cpp to make a hacked no-video version of uxplay for testing purposes.

**Comment by fduncanh** [comment]
@notthewave 

if this works i will just add  an option   -vs 0
to have no video.

**Comment by notthewave** [comment]
What I did was to select the "Apple TV" as an output audio device. 
like so and was expecting it to work (only a demo as it did not actually work):

https://user-images.githubusercontent.com/74874782/135153952-30339637-3bc6-405b-b4ad-3bd6bcfa4b76.mp4

not that I require it but might be a nice feature

**Comment by fduncanh** [comment]
@notthewave 

did you comment out those 3 lines in uxplay.cpp  and compile?

did  the modification to not show a  mirror window prevent the segtfault?

you seem to say  it didnt work, but were not clear

what is the audio source you are testing with?

maybe post  the uxpaly -d output

**Comment by notthewave** [comment]
I'm playing music with VLC and use Pipewire. But there is still no audio even after commenting the 3 lines out. The output looks exactly the same as before commenting the relevant lines out.

**Comment by notthewave** [comment]
Ok it works when using the regular screen share option and not the audio device option like above. There is also no video but audio works.

**Comment by fduncanh** [comment]
I  think I see what you are doing.  I see that  the iPad (iPadOS 15)  also has an audio airplay option as well as a mirror  option.
The audio one doesn't segfault for me , but doesnt work.

uxplay  may be mirror (with audio) only, I dont know.
The audio only without mirror  is  a different protocol.

I  checked that RpiPlay behaves the same way, 
so its  not so clear if anything can easily be done to make the other protocol work.

There are some audio only AirPlay servers out there, I think.

**Comment by fduncanh** [comment]
@notthewave 

But it doesnt fault segfault with mirror protocol and no video window?

Is that a useful option then?    (But I guess the segfault was from trying to use the audio  non-mirror protocol, and that is now gone, even though no sound?)

**Comment by notthewave** [comment]
I tried the audio option several times sometimes it sometimes failed sooner or later, sometimes not, but with the mirroring option it does not segfault.

**Comment by notthewave** [comment]
I believe that audio only can be useful, but that can be achieved with other methods too, s.a. Bluetooth. Might be useful when connected to a Desktop PC.

**Comment by fduncanh** [comment]
I think the audio option is mainly for smart speakers now (?)

I'll look into extending the -vs option to allow ``-vs 0`` to  give  Airplay mirror protocol without video rendering
just like the -a option gives video without audio by mirroring.   (And clarify the README to say that audio Airplay is not supported).

But thats the only easy change that I can make.

**Comment by fduncanh** [comment]
@notthewave 

just to be clear, you never heard sound with the non-mirror audio option before it failed, right?

**Comment by notthewave** [comment]
It probably does not prevent the Apple device from sending video output and is therefore quite inefficient.

**Comment by notthewave** [comment]
No. no sound at all with the audio-only option. But the output states that it's receiving info.

**Comment by notthewave** [comment]
The log only starts when audio is played. (audio-only (video-clip above))

**Comment by notthewave** [comment]
raop_rtp audio: ntp = 1632862818736162, now = 1632862816652568, latency=-2083594, rtp=1167896666
etc. etc.

**Comment by fduncanh** [comment]
@notthewave 

yes mirror for audio only is inefficient, of course.

But I do have control of a maximum frames per second instruction sent to  the ipad, which can go as low as 1 fps.

**Comment by notthewave** [comment]
Sure that it is a different protocol? After all I'm receiving something, it just does not play.

**Comment by fduncanh** [comment]
no I'm not sure.   But we are using a legacy protocol, so not implementing  all of Apples more recent "secrets".

maybe RPiPlay developer might know

**Comment by notthewave** [comment]
Maybe it uses a different codec? That is better quality wise?

**Comment by fduncanh** [comment]
FD- (RPiPlay developer) has an essay on Airplay protocals at the end of the UxPlay readme, you could look at that.

The only easy thing  I can do is create a "-vs 0" option for mirror protocol with video at 1 fps not rendered in a window.

**Comment by fduncanh** [comment]
UxPlay 1.40 now supports Airplay audio (Lossless ALAC audio) when not mirroring the screen

**Comment by notthewave** [comment]
Nice to hear! Sadly, I can't try it as my dormitory has isolated the clients of it's network, so they can't talk to one another over it. I wonder if there is a way to get it working regardless. Though I do believe that would require special hardware just like https://github.com/seemoo-lab/owl.
