### ISSUE TITLE
Cannot launch on Fedora 37 

### ISSUE THREAD

**Issue by patkepa** [FDH2/UxPlay#158]
I encountered an issue while trying to launch build of UxPlay on **Fedora 37**:

```bash
UxPlay 1.60: An Open-Source AirPlay mirroring and audio-streaming server.

** (uxplay:8755): ERROR **: 20:40:04.200: gst_parse_launch error (audio 1):
 no element "avdec_aac"

Trace/breakpoint trap (core dumped)
```
I already went through all gstreamer dependencies I could install, the one that contains "avdec_acc" should be package **gstreamer1-plugin-libav** from RPMFusion, which I have installed.

Since it seemed like an issue with audio I tried to disable it using `uxplay -a`, but in resulted in different error message:

```bash
UxPlay 1.60: An Open-Source AirPlay mirroring and audio-streaming server.
audio_disabled
using system MAC address 12:f7:28:c0:23:99
Illegal instruction (core dumped)
```

**Comment by fduncanh** [comment]
see issue #138 for solution.

or  look at this section of README:
Non-Debian-based Linux or \*BSD

  Red Hat, Fedora, CentOS (now continued as Rocky Linux or Alma Linux): (sudo yum install) openssl-devel libplist-devel 
avahi-compat-libdns_sd-devel (some from the "PowerTools" add-on repository) (+libX11-devel for fullscreen X11, and 
"ZOOMFIX" if needed). The required GStreamer packages are: gstreamer1-devel gstreamer1-plugins-base-devel 
gstreamer1-libav gstreamer1-plugins-bad-free (+ gstreamer1-vaapi for intel graphics); you may need to get some of them 
(in particular gstreamer1-libav) from [rpmfusion.org](https://rpmfusion.org/) (which provides packages including plugins 
that RedHat does not ship for license reasons).

**Comment by fduncanh** [comment]
I didnt read your issue far enough to see you think  you are using the rpmfusion version of gstreamer1-plugin-libav
The message no element avdec_aac definitev shows (I believe) that the rpmfusion.org gstreamer1-livav rpm is not properly installed.

whats does "`gst-inspect 1.0 libav | grep aac`" show?
I get
```
gst-inspect-1.0 libav | grep aac
  avdec_aac: libav AAC (Advanced Audio Coding) decoder
  avdec_aac_fixed: libav AAC (Advanced Audio Coding) decoder
  avdec_aac_latm: libav AAC LATM (Advanced Audio Coding LATM syntax) decoder
  avenc_aac: libav AAC (Advanced Audio Coding) encoder
  avmux_adts: libav ADTS AAC (Advanced Audio Coding) muxer (not recommended, use aacparse instead)
```
I don't know why you get a coredump with -a option. This is happening during the setup phase

what message does "uxplay -a -d" give?

**Comment by fduncanh** [comment]
I have installed Fedora 37 in virtualbox.    I reproduced your issue with libav.  The RedHat distributed  version of gstreamer's libav plugin is the issue.

I have not yet managed to get a RPMFusion version of gstreamer1--plugin-libav installed.

Compared to RedHat 9 clones, Fedora 37 seems a complete mess as far as this is concerned.

**Comment by fduncanh** [comment]
Everything works in Fedora 36.

It seems the crucial rpm from RPMFusion is not gstreamer1-plugins-libav but may be 
ffmpeg-libs which it uses

**Comment by fduncanh** [comment]
@patkepa 

Tried again in Fedora 37 (on VirtualBox.) **now it works.**

The key is to install and activate RPMFusion before starting to build uxplay.   In recent Fedora,  gstreamer1-plugins-libav
is not taken from RPMFusion .org, but ffmpeg--libs  (which gstreamer1-plugins-libav is just a front end for)  _is_ taken from RPMFusion.org.

sudo yum install (or sudo dnf install) ffmpeg-libs should fix things for you.

**Comment by fduncanh** [comment]
The instructions in the [UxPlay README](https://github.com/FDH2/UxPlay#non-debian-based-linux-or-bsd) have been updated for this Fedora issue.

_[In recent **Fedora**, the libav plugin package is renamed to "gstreamer1-plugin-libav". which now needs the RPM Fusion package ffmpeg-libs for the patent-encumbered code which RedHat does not provide: check with "rpm -qi ffmpeg-libs" that it lists "Packager" as RPM Fusion; if this is not installed, uxplay will fail to start, with error: **no element "avdec_aac"** ]_.
