### ISSUE TITLE
Dear develop. How can the client end the current image actively

### ISSUE THREAD

**Issue by nozuonodienobb** [FDH2/UxPlay#159]
when i mirroing, i take the another iphone to connect the app, I want to disconneted for the current client, how to do? 3k

**Comment by thiccaxe** [comment]
From README:

-nohold Drops the current connection when a new client attempts to connect. Without this option, the current client maintains exclusive ownership of UxPlay until it disconnects.

**Comment by nozuonodienobb** [comment]
how to dorp the current connection

**Comment by fduncanh** [comment]
There is a setting with a name like max_connections.  Apple TV allows 12, I think.
each client requires 2 connections.

I set max_connection to 2 to prevent a new client from connecting while a previous client is connected.
a  request for a third connection is then ignored.

The nohold option sets max_connections to 3.   If a third connection is requested,  I destroy the previous 2, and the new client takes over.

code is in lib/httpd.c see line 355
