### ISSUE TITLE
Why don't use hostname as default server name?

### ISSUE THREAD

**Issue by PetrusZ** [FDH2/UxPlay#16]
There is a PR for antimof/UxPlay, https://github.com/antimof/UxPlay/pull/42, why don't use it?

I think is a good idea to use hostname as default server name.

**Comment by fduncanh** [comment]
You can run multiple instances of UxPlay  provided you use different server names ports and macaddress. 

This distinguishes the windows

Why would it be useful to default to hostname?

**Comment by fduncanh** [comment]
This (utsname) would be very linux specific.

**Comment by fduncanh** [comment]
OK I see the point.

I've implemented it, and pushed UxPlay to v1.36 as this is a significant change.
Thanks for the suggestion.

**Comment by PetrusZ** [comment]
Great!👍🏻

**Comment by fduncanh** [comment]
@PetrusZ 

I thought this through again, and instead decided to append @hostname  (hostname = utsname.nodename)
to UxPlay, or whatever was selected with -n option, so default choice would be  seen as  UxPlay@hostname

It's  now released as UxPlay 1.37
