### ISSUE TITLE
Don't adds debug flags by default

### ISSUE THREAD

**Issue by PetrusZ** [FDH2/UxPlay#160]
https://github.com/FDH2/UxPlay/blob/a5f2ba39b227dc0f7feaf15ec6ece908e9be31bd/lib/CMakeLists.txt#L6

debug flags slow down the build process and take more disk/ram and I think it should not be added by default..

See also: https://bugs.gentoo.org/887787

**Comment by fduncanh** [comment]
Please be more explicit about which flags are the problem...

**Comment by PetrusZ** [comment]
Yeah :)

**Comment by fduncanh** [comment]
These flags are all inherited from RPiPlay,  (RPiPlay/renderers/CMakeLists.txt) I don't know what many of them do...

**Comment by fduncanh** [comment]
-g removed

**Comment by PetrusZ** [comment]
Thank you!
