### ISSUE TITLE
the build system overwrites user's optimization (-O*)

### ISSUE THREAD

**Issue by PetrusZ** [FDH2/UxPlay#161]
man gcc says:
"If you use multiple -O options, with or without level numbers, the last such option is the one that is effective".

https://github.com/FDH2/UxPlay/blob/a5f2ba39b227dc0f7feaf15ec6ece908e9be31bd/lib/CMakeLists.txt#L16

So, since the build system adds -O* after -O* provided by my CFLAGS/CXXFLAGS means that it is overwritten and unless there are known issues with -O* configured by the user, the build system should not overwrite -O*.

See also: https://bugs.gentoo.org/887789

**Comment by fduncanh** [comment]
The C_FLAGS in the CMakeFiles.txt's are mostly inherited from earlier code.

Can you review them and make suggestions?

**Comment by PetrusZ** [comment]
OK, I'll debug/test it tomorrow, it's a little late today.

**Comment by fduncanh** [comment]
@PetrusZ 
I have rearranged lib/CMakeLists.txt so any $CFLAGS in the user's build environment are postpended (not prepended) to Cflags.  This will fix the reported issue.

**Comment by PetrusZ** [comment]
Thank you so much!
