### ISSUE TITLE
Uxplay is connecting to my IOS device however I only see a blackscreen upon connection

### ISSUE THREAD

**Issue by gomezenrique93** [FDH2/UxPlay#167]
Hello, 
I'm running pop_os on a system76 laptop that only has integrated graphics with an intel chip. I went through the steps of installing all the gstreamer plugins listed and I also ran the command sudo apt install uxplay.

As of this moment my IOS device connects to Uxplay however I'm only seeing a black screen.

**Comment by fduncanh** [comment]
not enough info.

see https://github.com/FDH2/UxPlay#troubleshooting for guidance

**Comment by fduncanh** [comment]
please close your issue if it is fixed
