### ISSUE TITLE
iPad screen mirror crashes uxplay

### ISSUE THREAD

**Issue by rogerbinns** [FDH2/UxPlay#170]
If I try to screen mirror my iPad to a freshly compiled uxplay 1.61, then uxplay gets an X error.  Xubuntu X based desktop.  Audio streaming works fine.

````
$ ~/uxplay -nohold
UxPlay 1.61: An Open-Source AirPlay mirroring and audio-streaming server.
using system MAC address a8:5e:45:e2:e9:3c
Initialized server socket(s)
Accepted IPv4 client on socket 32
Local: 192.168.1.5
Remote: 192.168.1.151
Client identified as User-Agent: AirPlay/675.1.1
Accepted IPv4 client on socket 36
Local: 192.168.1.5
Remote: 192.168.1.151
raop_rtp_mirror starting mirroring
Begin streaming to GStreamer video pipeline
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x5a00002
  Serial number of failed request:  4612
  Current serial number in output stream:  4612
````

**Comment by fduncanh** [comment]
checkout https://github.com/FDH2/UxPlay#troubleshooting

use a -vs option
uxplay -vs <imagesink>

<imagesink>  could be xvimagesink or gklmagesink, etc,

**Comment by rogerbinns** [comment]
autovideosink, ximagesink, xvimagesink all give the fatal BadWindow fatal error above.

glimagesink shows the screen but seems like it can't keep up refreshing (the bottom third is mostly black while the top refreshes)

vaapisink works perfectly.

I hadn't realised the BadWindow error was due to video sink (no mention of this failure mode in the doc).  So this situation is covered in the doc and uxplay can be made to work.  Thanks!
