### ISSUE TITLE
Follow up to [FDH2/UxPlay] UxPlay 1.62 (Discussion #172)

### ISSUE THREAD

**Issue by IInatas** [FDH2/UxPlay#173]
Thanks for your reply and a _big_ sorry for posting in the wrong channel.

I tried `uxplay` and got this error:
> UxPlay 1.62: An Open-Source AirPlay mirroring and audio-streaming server.
> Required gstreamer plugin 'libav' not found
> Missing plugin is contained in  '[GStreamer 1.x]-libav'

next I searched for libav which is installed under
 /usr/lib/gstreamer-1.0/libgstlibav.so
by `package gst-libav 1.20.5-1`

I read that vaapi might be a problem - so I deleted it and recompiled uxplay, but no success eigther.

regards,
Marcus

**Comment by fduncanh** [comment]
Its working for me on latest Manjaro.   (are you on X86_64 or arm (R Pi?))

does `gst-inspect-1.0 libav` show it is available for gstreamer?

```
gst-inspect-1.0 libav | grep avdec                  
  avdec_4xm: libav 4X Movie decoder
  avdec_8bps: libav QuickTime 8BPS video decoder
  avdec_8svx_exp: libav 8SVX exponential decoder
  avdec_8svx_fib: libav 8SVX fibonacci decoder
  avdec_aac: libav AAC (Advanced Audio Coding) decoder
  avdec_aac_fixed: libav AAC (Advanced Audio Coding) decoder
  avdec_aac_latm: libav AAC LATM (Advanced Audio Coding LATM syntax) decoder
<snip>
```

The plugins you need are:
* Arch Linux (sudo pacman -Syu) gst-plugins-good gst-plugins-bad gst-libav (+ gstreamer-vaapi for Intel graphics).

```
pacman -Qi gst-libav                  
Name            : gst-libav
Version         : 1.20.5-1
Description     : Multimedia graph framework - libav plugin
Architecture    : x86_64
URL             : https://gstreamer.freedesktop.org/
Licenses        : LGPL
Groups          : None
Provides        : gst-ffmpeg=1.20.5
Depends On      : gst-plugins-base-libs=1.20.5  bzip2  ffmpeg
Optional Deps   : None
Required By     : uxplay
Optional For    : phonon-qt5-gstreamer  qt5-multimedia  webkit2gtk  webkit2gtk-4.1
Conflicts With  : None
Replaces        : None
Installed Size  : 234.48 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Tue 20 Dec 2022 02:35:47 AM EST
Install Date    : Mon 26 Dec 2022 05:28:57 PM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by IInatas** [comment]
Thanks for the kind support - I got it up and running :-)
I am using the latest Manjaro (X86_64)
`gst-inspect-1.0 libav` showed it was unavailable for gstreamer, even though `pacman -Qi gst-libav` showed the identical version as yours.

A simply reinstall didn't worked. I had to remove almost all gst-XX plugins - reboot (sick nightmares return) - then reinstall all needed gst-xx plugins and finally `gst-inspect-1.0 libav` could find something.
Then recompiled `uxplay` and it worked smoothly again.

regards, Marcus

**Comment by IInatas** [comment]
Sorry for bothering - I have another problem now.
While typing the IPAD went to sleep and the connection to uxplay got lost.
Running `uxplay` now brings up a connection to the IPad, but then I get the following error:
`uxplay -nc -vs ximagesink`
> UxPlay 1.62: An Open-Source AirPlay mirroring and audio-streaming server.
> using system MAC address ....
> Initialized server socket(s)
> Accepted IPv4 client on socket 32
> Local: 192.168.178.37
> Remote: 192.168.178.39
> Client identified as User-Agent: AirPlay/670.6.2
> Accepted IPv4 client on socket 34
> Local: 192.168.178.37
> Remote: 192.168.178.39
> raop_rtp_mirror starting mirroring
> Begin streaming to GStreamer video pipeline
> X Error of failed request:  BadWindow (invalid Window parameter)
>   Major opcode of failed request:  20 (X_GetProperty)
>   Resource id in failed request:  0x8000002
>   Serial number of failed request:  2719
>   Current serial number in output stream:  2719

I am on KDE Plasma and X

regards, Marcus

**Comment by fduncanh** [comment]
This below is something added in uxplay-1.62.
It was supposed to stop needless searches for the X11 window if
default (autovideosink) selected something non-X11

I will need to see if this new code has broken something.
@IInatas 

please test with
-vs xvimagesink
-vs glimagesink
-vs ximagesink
-vs gtksink

and report which of these work and dont work for you

```
Begin streaming to GStreamer video pipeline
Looking for X11 UxPlay Window, attempt 1
Looking for X11 UxPlay Window, attempt 2
Looking for X11 UxPlay Window, attempt 3
Looking for X11 UxPlay Window, attempt 4
Looking for X11 UxPlay Window, attempt 5
X Error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 20 (X_GetProperty)
Resource id in failed request: 0x8000002
Serial number of failed request: 2719
Current serial number in output stream: 2719
```

**Comment by IInatas** [comment]
My success with the various parameters:
- [X] -vs xvimagesink
- [X] -vs glimagesink
- [X] -vs ximagesink <-----last comment it failed (I tried it last, may be there is a connection)
- [ ] -vs gtksink  <----- core dump after *
- [X] -vs autovideosink
- [X] -vs vaapisink

I don't know what changed in the last two hours? I tried `uxplay -vs ximagesink` and `uxplay` several times last time and they always failed. This time I tried the other options first, maybe that changed something, because before the IPad went to sleep it worked fine with `uxplay`.

regards, Marcus

 p.s.
* (uxplay:13336): ERROR **: 20:49:07.294: get_parse_launch error (video) : no element "gtksink"

**Comment by fduncanh** [comment]
sounds good.

Is this issue ready for closing?

**Comment by IInatas** [comment]
For me this issue is solved - **thank you for your your kind support.**

**Comment by IInatas** [comment]
P.P.S:
The problem that `uxplay` does not start has reappeared:
> UxPlay 1.62: An Open-Source AirPlay mirroring and audio-streaming server.
Required gstreamer plugin 'libav' not found
Missing plugin is contained in  '[GStreamer 1.x]-libav'
stopping

It is clearly a problem with gstreamer in combination with uxplay, but I couldn't find the root cause.
... but, a [workaround that works on nvidia developer]( https://forums.developer.nvidia.com/t/gstreamer-warning-failed-to-load-plugin-libgstlibav-so-libgomp-so-1-cannot-allocate-memory-in-static-tls-block/223710).
`rm -rf ~/.cache/gstreamer-1.0/ `
Maybe it's an issue with nvidia lib's, but I have no option to check that.

HTH,
Marcus
