### ISSUE TITLE
The connection was successful but no screen was displayed

### ISSUE THREAD

**Issue by sett6** [FDH2/UxPlay#178]
OS: Arch Linux x86_64
  WM: dwm
![image](https://user-images.githubusercontent.com/75558384/217720854-0ec40396-2e63-47cf-9692-09155728de6f.png)

**Comment by fduncanh** [comment]
1. Read the troubleshooting section of the README.

2.  see what uxplay -d shows

3. try different videsosinks ( -vs option)

give more details

**Comment by fduncanh** [comment]
@sett6  is this resolved?
please close issue in that case

**Comment by fduncanh** [comment]
closing, seems done.
