### ISSUE TITLE
RPI Video Renderer

### ISSUE THREAD

**Issue by hesa2020** [FDH2/UxPlay#182]
Hello I am not getting any video output with gstreamer window I tried running this from SSH:
gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink

And it returned:
Could not open display (null)

I then did:
export DISPLAY=:0.0

And then the test ran fine with a small window showing on the desktop, however when i try Uxplay with the following command:

./uxplay -n PiStreamer -v4l2 -rpiwl

I am not getting any video but I can hear the audio being streamed even tho it said:
- Begin streaming to GStreamer video pipeline

Edit: I got it working with ./uxplay -n PiStreamer -avdec
But its very choppy and I preferred how it was shown in RPIPlay with the screen centred and black background.

I tried adding audio part to RPIPlay on my fork and i can play sound without video but I can't play sound with video, I haven't figured out why yet.

**Comment by fduncanh** [comment]
Have you read the README?   Its pretty detailed about what to do.

which model RPi? which operating system ?  32 or 64 bit? if its not raspberry Pi OS (Bullseye), have you patched gstreamer-plugins-good?  (Only works for Ubunbtu and Manjaro)

with -avdec, you also need -vsync in UxPlay 1.63.    For best perfomance you need to use hardware video decoding.

**Comment by fduncanh** [comment]
Doesn't seem to be a UxPlay issue? (is  it about backporting to RPiPlay?)
