### ISSUE TITLE
--help option

### ISSUE THREAD

**Issue by rogerbinns** [FDH2/UxPlay#185]
It would be nice if uxplay provided standard help text.  It seems very determined not to provide any!

```console
$ ./uxplay --help
unknown option --help, stopping
$ ./uxplay -help
unknown option -help, stopping
$ ./uxplay -?
unknown option -?, stopping
$ ./uxplay -
unknown option -, stopping
$ ./uxplay 231312
unknown option 231312, stopping
```

I eventually discovered via ```-v``` that ```-h``` works.  Perhaps it is worth adding the line ```for help, use option "-h"``` after printing the unknown option message?

**Comment by fduncanh** [comment]
done

```
> uxplay --help
unknown option --help, stopping (for help use option "-h")
```
