### ISSUE TITLE
seems not work but no errors

### ISSUE THREAD

**Issue by spicemint** [FDH2/UxPlay#19]
installing on ubuntu 16.04 but with nvidia card, removed gstreamer1.0-vaapi
Linux SAT 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
uxplay starts, i see it on the ipad, but nothing happening on the screen, also tried the rpi version on this pc, same issue, works fine on raspberry though, any idea what I could do to get it working on pc? I assume that my pc is connected via vga should not make a difference.

> ./uxplay -d
using randomly-generated MAC address d6:28:dd:46:15:c5

Initialized server socket(s)
Accepted IPv4 client on socket 32
Local: 10.0.0.96
Remote: 10.0.0.64
Open connections: 1
httpd receiving on socket 32
conn_request
Handling request GET with URL /info
INFO len = 1166432284
httpd receiving on socket 32
conn_request
Handling request POST with URL /pair-setup
httpd receiving on socket 32
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 32
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 32
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 32
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 32
conn_request
Handling request SETUP with URL rtsp://10.0.0.96/11412413893314300445
DACP-ID: 42ADA2D6C4C7F6E7
Active-Remote: 1461888801
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 59050
raop_ntp parse remote ip = 10.0.0.64
raop_ntp starting time
raop_ntp local timing port socket 33 port UDP 45365
raop_rtp parse remote ip = 10.0.0.64
raop_rtp_mirror parse remote ip = 10.0.0.64
eport = 37918, tport = 45365
raop_ntp send_len = 32
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -1632962674290389
Accepted IPv4 client on socket 34
Local: 10.0.0.96
Remote: 10.0.0.64
Open connections: 2
httpd receiving on socket 32
conn_request
Handling request GET with URL /info
INFO len = 1166432284
httpd receiving on socket 32
conn_request
Handling request GET_PARAMETER with URL rtsp://10.0.0.96/11412413893314300445
httpd receiving on socket 32
conn_request
Handling request RECORD with URL rtsp://10.0.0.96/11412413893314300445
raop_handler_record
httpd receiving on socket 32
conn_request
Handling request SET_PARAMETER with URL rtsp://10.0.0.96/11412413893314300445
httpd receiving on socket 32
conn_request
Handling request SETUP with URL rtsp://10.0.0.96/11412413893314300445
DACP-ID: 42ADA2D6C4C7F6E7
Active-Remote: 1461888801
Transport: null
type = 110
streamConnectionID = 15713346008141612446
raop_rtp_mirror starting mirroring
raop_rtp_mirror local data port socket 35 port TCP 40217
Mirroring initialized successfully
raop_rtp_mirror accepting client
raop_rtp_mirror width_source = 1440.000000 height_source = 1080.000000 width = 1440.000000 height = 1080.000000
raop_rtp_mirror sps size = 18
raop_rtp_mirror pps size = 4
raop_rtp_mirror video ntp = 1633525472716935, now = 1633525472671461, latency = -45474
raop_rtp_mirror video ntp = 1633525472750270, now = 1633525472681481, latency = -68789
raop_rtp_mirror video ntp = 1633525472775272, now = 1633525472708044, latency = -67228
raop_rtp_mirror video ntp = 1633525472800273, now = 1633525472732082, latency = -68191
raop_rtp_mirror video ntp = 1633525472816940, now = 1633525472776864, latency = -40076
raop_rtp_mirror video ntp = 1633525472858609, now = 1633525472791004, latency = -67605
raop_rtp_mirror video ntp = 1633525472908612, now = 1633525472841535, latency = -67077
raop_rtp_mirror video ntp = 1633525472958614, now = 1633525472890732, latency = -67882
raop_rtp_mirror video ntp = 1633525473008617, now = 1633525472941240, latency = -67377
raop_rtp_mirror video ntp = 1633525473058619, now = 1633525472991085, latency = -67534
raop_rtp_mirror video ntp = 1633525473108622, now = 1633525473041483, latency = -67139
raop_rtp_mirror video ntp = 1633525473158624, now = 1633525473091524, latency = -67100
raop_rtp_mirror video ntp = 1633525473208627, now = 1633525473142309, latency = -66318
raop_rtp_mirror video ntp = 1633525473258629, now = 1633525473193353, latency = -65276
raop_rtp_mirror video ntp = 1633525473308632, now = 1633525473241624, latency = -67008
raop_rtp_mirror video ntp = 1633525473358634, now = 1633525473291106, latency = -67528
raop_rtp_mirror video ntp = 1633525473408637, now = 1633525473339581, latency = -69056
raop_rtp_mirror video ntp = 1633525473441972, now = 1633525473374595, latency = -67377
raop_rtp_mirror video ntp = 1633525473475305, now = 1633525473442538, latency = -32767
raop_rtp_mirror video ntp = 1633525473500308, now = 1633525473453658, latency = -46650
raop_rtp_mirror video ntp = 1633525473550310, now = 1633525473486611, latency = -63699
raop_rtp_mirror video ntp = 1633525473600313, now = 1633525473540482, latency = -59831
raop_rtp_mirror video ntp = 1633525473650315, now = 1633525473589335, latency = -60980
raop_rtp_mirror video ntp = 1633525473700318, now = 1633525473636629, latency = -63689
raop_rtp_mirror video ntp = 1633525473741987, now = 1633525473674918, latency = -67069
raop_rtp_mirror video ntp = 1633525473791989, now = 1633525473723876, latency = -68113
raop_rtp_mirror video ntp = 1633525473841992, now = 1633525473775422, latency = -66570
raop_rtp_mirror video ntp = 1633525473891994, now = 1633525473825590, latency = -66404
raop_rtp_mirror video ntp = 1633525473941997, now = 1633525473875984, latency = -66013
raop_rtp_mirror video ntp = 1633525474000333, now = 1633525473939957, latency = -60376
raop_rtp_mirror video ntp = 1633525474050335, now = 1633525473988626, latency = -61709
raop_rtp_mirror video ntp = 1633525474100338, now = 1633525474035978, latency = -64360
raop_rtp_mirror video ntp = 1633525474150340, now = 1633525474089772, latency = -60568
raop_rtp_mirror video ntp = 1633525474200343, now = 1633525474139470, latency = -60873
raop_rtp_mirror video ntp = 1633525474250345, now = 1633525474189277, latency = -61068
raop_rtp_mirror video ntp = 1633525474292014, now = 1633525474225790, latency = -66224
raop_rtp_mirror video ntp = 1633525474342017, now = 1633525474275500, latency = -66517
raop_rtp_mirror video ntp = 1633525474400353, now = 1633525474333944, latency = -66409
raop_rtp_mirror video ntp = 1633525474450355, now = 1633525474383673, latency = -66682
raop_rtp_mirror video ntp = 1633525474508692, now = 1633525474446733, latency = -61959
^CStopping...
raop_rtp_mirror video ntp = 1633525474558694, now = 1633525474499740, latency = -58954
raop_rtp_mirror video ntp = 1633525474608697, now = 1633525474548862, latency = -59835
raop_rtp_mirror video ntp = 1633525474658699, now = 1633525474597804, latency = -60895
Removing connection for socket 32
Destroying connection
Open connections: 1
raop_ntp stopping time thread
raop_ntp exiting thread
raop_ntp stopped time thread
raop_rtp_mirror exiting TCP thread
Removing connection for socket 34
Destroying connection
Open connections: 0
Exiting HTTP thread

**Comment by spicemint** [comment]
> uxplay -d -vs ximagesink

that indeed did the trick, super awesome, so happy, I have an apple tv 2 but that stupid thing wouldn't mirror when the ipad's are on vpn which we are like 99% of the time, this works with vpn as well so awesome, many many thanks

**Comment by bendschs** [comment]
i have the same problem on my raspberry pi 4. uxplay starts up fine with ./uxplay -d -vs autovideosink and i am also able to connect, but then immediately get disconnected with no error message. 

```
./uxplay -d -vs autovideosink
Initialized server socket(s)
Accepted IPv4 client on socket 37
Local: 192.168.3.72
Remote: 192.168.3.45
Open connections: 1
httpd receiving on socket 37
conn_request
Handling request GET with URL /info
INFO len = -605042676
httpd receiving on socket 37
conn_request
Handling request POST with URL /pair-setup
httpd receiving on socket 37
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 37
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 37
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 37
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 37
conn_request
Handling request SETUP with URL rtsp://192.168.3.72/16067733023866569581
DACP-ID: 6B542BF4CCA92CE8
Active-Remote: 672302283
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 51715
raop_ntp parse remote ip = 192.168.3.45
raop_ntp starting time
raop_ntp local timing port socket 38 port UDP 59643
raop_rtp parse remote ip = 192.168.3.45
raop_rtp_mirror parse remote ip = 192.168.3.45
eport = 46001, tport = 59643
raop_ntp send_len = 32
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -1633701196307169
Accepted IPv4 client on socket 39
Local: 192.168.3.72
Remote: 192.168.3.45
Open connections: 2
httpd receiving on socket 37
conn_request
Handling request GET with URL /info
INFO len = -605042676
httpd receiving on socket 37
conn_request
Handling request GET_PARAMETER with URL rtsp://192.168.3.72/16067733023866569581
httpd receiving on socket 37
conn_request
Handling request RECORD with URL rtsp://192.168.3.72/16067733023866569581
raop_handler_record
httpd receiving on socket 37
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.3.72/16067733023866569581
httpd receiving on socket 37
conn_request
Handling request SETUP with URL rtsp://192.168.3.72/16067733023866569581
DACP-ID: 6B542BF4CCA92CE8
Active-Remote: 672302283
Transport: null
type = 110
streamConnectionID = 9925863035276118702
raop_rtp_mirror starting mirroring
raop_rtp_mirror local data port socket 40 port TCP 33179
Mirroring initialized successfully
raop_rtp_mirror accepting client
raop_rtp_mirror width_source = 500.000000 height_source = 1080.000000 width = 500.000000 height = 1080.000000
raop_rtp_mirror sps size = 18
raop_rtp_mirror pps size = 4
raop_rtp_mirror video ntp = 1633944362395290, now = 1633944362319737, latency = -75553
raop_rtp_mirror video ntp = 1633944362445343, now = 1633944362343575, latency = -101768
raop_rtp_mirror video ntp = 1633944362462027, now = 1633944362360753, latency = -101274
raop_rtp_mirror video ntp = 1633944362495396, now = 1633944362393239, latency = -102157
raop_rtp_mirror video ntp = 1633944362528765, now = 1633944362425726, latency = -103039
raop_rtp_mirror video ntp = 1633944362562134, now = 1633944362460489, latency = -101645
raop_rtp_mirror video ntp = 1633944362595503, now = 1633944362581183, latency = -14320
raop_rtp_mirror video ntp = 1633944362628872, now = 1633944362588947, latency = -39925
raop_rtp_mirror video ntp = 1633944362662240, now = 1633944362595659, latency = -66581
raop_rtp_mirror video ntp = 1633944362695609, now = 1633944362601396, latency = -94213
raop_rtp_mirror video ntp = 1633944362728943, now = 1633944362659172, latency = -69771
raop_rtp_mirror video ntp = 1633944362762276, now = 1633944362691533, latency = -70743
raop_rtp_mirror video ntp = 1633944362795580, now = 1633944362697254, latency = -98326
GStreamer error: No valid frames decoded before end of stream
Re-launching server...
raop_rtp_mirror video ntp = 1633944362828948, now = 1633944362724845, latency = -104103
raop_rtp_mirror video ntp = 1633944362862316, now = 1633944362761142, latency = -101174
raop_rtp_mirror video ntp = 1633944362895684, now = 1633944362792929, latency = -102755
raop_rtp_mirror video ntp = 1633944362929053, now = 1633944362827153, latency = -101900
raop_rtp_mirror video ntp = 1633944362962421, now = 1633944362861683, latency = -100738
raop_rtp_mirror video ntp = 1633944362995789, now = 1633944362971838, latency = -23951
raop_rtp_mirror video ntp = 1633944363029157, now = 1633944362979233, latency = -49924
raop_rtp_mirror video ntp = 1633944363062526, now = 1633944362979427, latency = -83099
raop_rtp_mirror video ntp = 1633944363095859, now = 1633944363027796, latency = -68063
raop_rtp_mirror video ntp = 1633944363129192, now = 1633944363059464, latency = -69728
raop_rtp_mirror video ntp = 1633944363162526, now = 1633944363093351, latency = -69175
raop_rtp_mirror video ntp = 1633944363212683, now = 1633944363111847, latency = -100836
raop_rtp_mirror video ntp = 1633944363246016, now = 1633944363177576, latency = -68440
raop_rtp_mirror video ntp = 1633944363279349, now = 1633944363211478, latency = -67871
raop_rtp_mirror video ntp = 1633944363312683, now = 1633944363244343, latency = -68340
Removing connection for socket 37
Destroying connection
Open connections: 1
raop_ntp stopping time thread
raop_ntp exiting thread
raop_ntp stopped time thread
raop_rtp_mirror exiting TCP thread
Removing connection for socket 39
Destroying connection
Open connections: 0
Exiting HTTP thread
Initialized server socket(s)
```


if i try to start it wit ximagesink i get:

```
./uxplay -d -vs ximagesink
Initialized server socket(s)
GStreamer error: Could not initialise X output
Re-launching server..
```

on a more general note i wanted to ask if uxplay is even recommended over RPiplay on a raspberry pi. I noticed that there is not much development going on there any more, that‘s why i am testing uxplay.
