### ISSUE TITLE
Touch Functionality

### ISSUE THREAD

**Issue by pguaca** [FDH2/UxPlay#194]
Hi@all,

my use case:
I'm running a macbook pro(1440x900) and installed uxplay on Ubuntu 20.04.6 LTS which is running on a NUC8i7BEH which is connected to an interactive Touch Display - Iiyama North America 43" (1920x1080) 

I successfully connected my macbook with Ubuntu via Screen Mirroring.
Now, the emulated / screen mirrored window in Ubuntu doesn't allow touch interaction.

1. Is there a way to enable touch interaction for the mirrored window? outside of it touch interaction works pretty fine.
2. The mirrored window on Ubuntu is showing black bars around the screen shared macbook desktop, no matter which resolution I'm choosing. Is there a way to make the mirrored window go complete full screen which will fit into Iiyama North America 43" (1920x1080) without black borders around and with touch interaction functionality?

Thanks in advance

**Comment by fduncanh** [comment]
1. touchscreen.   UxPlay or its clients won't receive any touchscreen signals from the mirror window.   (but maybe you can close the window with a touch?   UxPlay would learn indirectly that the window was closed)


2. full screen works with a few "videosinks" but not all.     If X11 (ximagesink or xvimagesink) is used, the terminal tells you

*  *** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode

with waylandsink and vaapisink, you get full screen  with option -fs.    It depends on  the GStreamer "videosink" being used.  (the -vs ...  option).    glimagesink and gtksink don't seem to have a fullscreen mode.
