### ISSUE TITLE
building gstreamer1.0-plugins-good failed on rpi 4b bullseye 32bit

### ISSUE THREAD

**Issue by Camouflager** [FDH2/UxPlay#195]
following this link https://github.com/FDH2/UxPlay/wiki/Gstreamer-Video4Linux2-plugin-patches#debian-based-systems-raspberry-pi-os-ubuntu-patch-the-deb-package-source

during this step
```
apt-get source gstreamer1.0-plugins-good
cd gst-plugins-good1.0-1.18.4
debuild
```

building failed with 
```
dh_missing: warning: usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstrpicamsrc.so exists in debian/tmp but is not installed to anywhere 
dh_missing: error: missing files, aborting
	The following debhelper tools have reported what they installed (with files per package)
	* dh_install: gstreamer1.0-gtk3 (1), gstreamer1.0-plugins-good (72), gstreamer1.0-pulseaudio (0), gstreamer1.0-qt5 (0)
	* dh_installdocs: gstreamer1.0-gtk3 (0), gstreamer1.0-plugins-good (0), gstreamer1.0-pulseaudio (0), gstreamer1.0-qt5 (0)
	If the missing files are installed by another tool, please file a bug against it.
	When filing the report, if the tool is not part of debhelper itself, please reference the
	"Logging helpers and dh_missing" section from the "PROGRAMMING" guide for debhelper (10.6.3+).
	 (in the debhelper package: /usr/share/doc/debhelper/PROGRAMMING.gz)
	Be sure to test with dpkg-buildpackage -A/-B as the results may vary when only a subset is built
	If the omission is intentional or no other helper can take care of this consider adding the
	paths to debian/not-installed.

	Remember to be careful with paths containing "arm-linux-gnueabihf", where you might need to
	use a wildcard or (assuming compat 13+) e.g. ${DEB_HOST_MULTIARCH} in debian/not-installed
	to ensure it works on all architectures (see #961104).
make: *** [debian/rules:49: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

Any help is appreciated

**Comment by fduncanh** [comment]
Is everything installed so UxPlay  Bullseye 32B works **without** rebuilding gstreamer1.0-plugins-good?   (this needs the -bt709 uxplay option).    

Rebuilding libgstvideo4linux.so  isn't absolutely necessary (but better to do!) in  RPiOS Bullseye, because they have already added part of the backport patch to GStreamer-1.18.4

all the gstreamer packages needed should be installed before debuild

**Comment by fduncanh** [comment]
I just successfully retested on a fully updated RPiOs Bullseye 32Bit RPi 4b  (on which
uxplay worked only with the -bt709 option, showing it was using gstreamer as supplied by RPi OS.)

 After debuild finished, it stalled at some final tests  (xvfb-rn dh_auto_test || true) with 

```
ninja: Entering directory `/home/pi/gst-plugins-good1.0-1.18.4/obj-arm-linux-gnueabihf'
ninja no work to do
```
(I needed to do a ctrl-C  (I'll add this to the recipe) to break out of debuild at this point)

I then proceeded with the recipe  (`cd obj*`, etc):

Everything worked.

**Comment by fduncanh** [comment]
In fact, you build succeeded, just the debbuild tests failed.  all you need to do  (I think) is continue the process   (cd obj*; patch, etc.)
