### ISSUE TITLE
Cmake fails because of libplist "missing" even though it is installed.

### ISSUE THREAD

**Issue by fduncanh** [FDH2/UxPlay#197]
_(posted by   @ivanzgroot at the old UxPlay antimof site)_
https://github.com/antimof/UxPlay/issues/134

Cmake fails looking for libplist-2.0 but libplist-2.2.0-9.fc38.x86_64 is already installed.
Running on Fedora 38.

`-- Project name: uxplay
-- Will compile using X11 Libraries (use cmake option -DNO_X11_DEPS=ON if X11 dependence is not wanted)
-- *** CFLAGS "" from build environment will be postpended to CMAKE_CFLAGS
-- Using CFLAGS with -march=native
-- *** ONLY USE THIS WHEN COMPILING ON THE MACHINE THAT WILL RUN UXPLAY
-- run "cmake -DNO_MARCH_NATIVE=ON" to switch off this compiler option
-- using CMAKE_CFLAGS: -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Ofast -march=native
-- Checking for one of the modules 'libplist>=2.0'
-- Checking for one of the modules 'libplist-2.0'
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:894 (message):
None of the required 'libplist-2.0' found
Call Stack (most recent call first):
lib/CMakeLists.txt:92 (pkg_search_module)

-- Will use X_DISPLAY_FIX
-- ZOOMFIX will NOT be applied as Gstreamer version is >= 1.20
-- Configuring incomplete, errors occurred!`

if I run:

sudo dnf update && sudo dnf install libplist

the results are:

Package libplist-2.2.0-9.fc38.x86_64 is already installed. Dependencies resolved. Nothing to do. Complete!

**Comment by fduncanh** [comment]
* **UxPlay builds correctly on fedora 38 (tested)** 

@ivanzgroot : From your cmake output, it look like pkgconf  (to provide "pkg-config") is not installed.  what does "which pkg-config" report  (should be "/usr/bin/pkg-config")

The README says

 You also need pkg-config: if it is not found by "which pkg-config", install pkg-config or its work-alike replacement pkgconf. Also make sure that cmake>=3.4.1 is installed: 

On Fedora 38  install two rpms:  pkgconf and pkgconf-pkg-config

**Comment by ivanzgroot** [comment]
Hey, Thanks for the repost in here @fduncanh. I accidentally published to the old site.

I just tried to install the packages with:

`sudo dnf update && sudo dnf install pkgconf-pkg-config pkgconf`

and it came back with:

Package pkgconf-pkg-config-1.8.0-6.fc38.x86_64 is already installed.
Package pkgconf-1.8.0-6.fc38.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

So pkgconf is installed.


But I just got it working. It was indeed missing the libplist-2.0 package. 
I had libplist-2.2.0-9.fc38.x86_64 installed but cmake is looking for **ibplist-devel-2.2.0-9.fc38.x86_64** . 
After installing it the Cmake command worked.

**Comment by fduncanh** [comment]
OK!     It does list libplist-devel in the RedHat instructions!

* Red Hat, or clones like CentOS (now continued as Rocky Linux or Alma Linux): (sudo dnf install, or sudo yum install) openssl-devel libplist-devel avahi-compat-libdns_sd-devel gstreamer1-devel gstreamer1-plugins-base-devel (+libX11-devel for fullscreen X11) (some of these may be in the "CodeReady" add-on repository, called "PowerTools" by clones)

**Comment by shubhxms** [comment]
hello!
i get the following error when i run uxplay
`uxplay: error while loading shared libraries: libplist-2.0.so.3: cannot open shared object file: No such file or directory`
libsplist is installed

**Comment by fduncanh** [comment]
@shubhxms give more details.
did you compile uxplay yourself?   which version ("uxplay -v")
what distribution?

how do you know that libplist is installed?

**Comment by fduncanh** [comment]
on e.g. Ubuntu-22.04 LTS,  libplist-2.0.so.3 is in /usr/linux/x86_64-linux-gnu/
and is installed by "sudo apt install libplist3"

If you built uxplay yourself (recommended) and  followed the instruction you should have it installed.

If you used a prebuilt package, that package should have included libplist in its requirements.

**Comment by geeflaxx** [comment]
Hey I have arch linux and libplist3 is not in the package manager

does someone has a solution?

![image](https://github.com/FDH2/UxPlay/assets/21129138/2ca97823-e198-4642-abd3-15812054dae1)

**Comment by fduncanh** [comment]
what makes you think you need "libplist3" ????  what problem are you having?   (The comment above is about is about Ubuntu)


Arch puts everything needed in its  "libplist" package, which is clearly installed on your system.

"pacman -Ql libplist" shows what it contains

Is something not working for you?

**Comment by geeflaxx** [comment]
![image](https://github.com/FDH2/UxPlay/assets/21129138/5739a9cf-a1bb-467c-8321-e3de9dea71bc)


I already installed it

**Comment by fduncanh** [comment]
a new release of libplist was recently made,  annoyingly with one single modified item in its supposedly "stable" API that breaks some apps, but not uxplay.   Arch always rushes to provide the latest things, so it seems they have renamed libplist-2.0.so.3 to lib-2.0.so.4, when they upgraded it, because there is a change in the API.

Your uxplay was built to use  libplist-2.0.so.3, which was the name of the shared library that was installed by the time uxplay was built, either by you from source or by the AUR  script.     After it was built, Arch upgraded libplist, and broke previously-compiled uxplay. 

* Just rebuild uxplay from source or with AUR, and you will be OK

**Comment by fduncanh** [comment]
Closing, see #199

**Comment by fduncanh** [comment]
@shubhxms 

If you are using Arch Linux, the issue is because of a recent Arch update of libplist **after** uxplay was compiled.  See #199   You just need to rebuild uxplay (using AUR, if that is how you installed it)

* Suggestion: always give full details, such as which distribution you use, and description (e.g. "it used to work, but has stopped working")

**Comment by shubhxms** [comment]
> @shubhxms give more details. did you compile uxplay yourself? which version ("uxplay -v") what distribution?
i am on a arch based distro, i downloaded the AUR package
"uxplay -v " returns an error: "uxplay: error while loading shared libraries: libplist-2.0.so.3: cannot open shared object file: No such file or directory"
> how do you know that libplist is installed? (the error message appears to indicate that it isn't)
i tried installing and the system said "reinstalling, already installed" 
> EDIT: look for it with
> 
> ```
> find /usr  -name  "libplist*"
> ```
/usr/lib/pkgconfig/libplist++-2.0.pc
/usr/lib/pkgconfig/libplist-2.0.pc
find: ‘/usr/lib/mysql/plugin/auth_pam_tool_dir’: Permission denied
/usr/lib/libplist++-2.0.so
/usr/lib/libplist++-2.0.so.4
/usr/lib/libplist++-2.0.so.4.3.0
/usr/lib/libplist-2.0.so
/usr/lib/libplist-2.0.so.4
/usr/lib/libplist-2.0.so.4.3.0
find: ‘/usr/share/polkit-1/rules.d’: Permission denied

**Comment by shubhxms** [comment]
> @shubhxms
> 
> If you are using Arch Linux, the issue is because of a recent Arch update of libplist **after** uxplay was compiled. See #199 You just need to rebuild uxplay (using AUR, if that is how you installed it)

oh! thank you!

> * Suggestion: always give full details, such as which distribution you use, and description (e.g. "it used to work, but has stopped working")

i will keep that in mind, sorry for the confusion!

**Comment by fduncanh** [comment]
All good now?

**Comment by shubhxms** [comment]
I get the "could not connect to Uxplay@<my-laptop>" error (https://github.com/FDH2/UxPlay#2-uxplay-starts-but-stalls-after-initialized-server-sockets-appears-with-the-server-name-showing-on-the-client-but-the-client-fails-to-connect-when-the-uxplay-server-is-selected)
firewalld is not running and I do not have ufw installed

**Comment by fduncanh** [comment]
run "uxplay -d" and post the output here

**Comment by shubhxms** [comment]
uxplay -d
'''
UxPlay 1.64: An Open-Source AirPlay mirroring and audio-streaming server.
Audio format 1: AAC-ELD 44100/2
GStreamer audio pipeline 1: "appsrc name=audio_source ! queue ! avdec_aac ! audioconvert ! audioresample ! volume name=volume ! level ! autoaudiosink sync=true"
Audio format 2: ALAC 44100/16/2
GStreamer audio pipeline 2: "appsrc name=audio_source ! queue ! avdec_alac! audioconvert ! audioresample ! volume name=volume ! level ! autoaudiosink sync=false"
GStreamer video pipeline will be:
"appsrc name=video_source ! queue ! h264parse ! decodebin ! videoconvert !autovideosink name=video_sink sync=true"
Initialized GStreamer video renderer
using system MAC address 8c:16:45:bc:54:70
Initialized server socket(s)
'''

**Comment by fduncanh** [comment]
sounds like a firewall.  I'll boot Arch and look

**Comment by fduncanh** [comment]
check for the firewall with

```
sudo systemctl status firewalld
```
stop it with

```
sudo systemctl stop firewalld
```

**Comment by shubhxms** [comment]
>sudo systemctl status firewalld

firewalld.service - firewalld - dynamic firewall daemon
Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled;>
Active: inactive (dead)
Docs: man:firewalld(1)
lines 1-4/4 (END)

it is not running

same issue - "could not connect to uxplay@<my-laptop>"

**Comment by fduncanh** [comment]
The symptom you have means that the uxplay server is not hearing anything back from the iOS device. 
You need to find out why.  
https://linuxconfig.org/how-to-monitor-network-activity-on-a-linux-system

On arch, with the firewall disabled, it works here

```
sudo systemctl status firewalld
○ firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; preset: disabled)
     Active: inactive (dead)
       Docs: man:firewalld(1)
```
```

uxplay
UxPlay 1.64: An Open-Source AirPlay mirroring and audio-streaming server.
using system MAC address 80:dx:4c:ab:a1:66
Initialized server socket(s)
Accepted IPv4 client on socket 24
Local: 192.168.1.28
Remote: 192.168.1.109
Client identified as User-Agent: AirPlay/680.23.1
Accepted IPv4 client on socket 26
Local: 192.168.1.28
Remote: 192.168.1.109
raop_rtp_mirror starting mirroring
Begin streaming to GStreamer video pipeline
```

**Comment by fduncanh** [comment]
also check for ufw, iptables 

https://www.baeldung.com/linux/firewall-status

**Comment by shubhxms** [comment]
hi! i gave up on the idea back then but was able to get it working now!
thank you so much for being so responsive and helpful! :)

**Comment by Booth1983** [comment]
Hi,
when I compile Uxplay on Ubuntu 20.04 it gives me the same Issue as mentioned above.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBPLIST
    linked by target "airplay" in directory /home/schule/bin/uxplay/UxPlay/lib

-- Configuring incomplete, errors occurred!
```

Use of **sudo apt install libplist3** says, that its allready installed.
