### ISSUE TITLE
error compiling.

### ISSUE THREAD

**Issue by mohad12211** [FDH2/UxPlay#2]
![image](https://user-images.githubusercontent.com/51754973/130338520-2d62abd8-9a3a-4dca-95d5-50192da39927.png)
apparently you added a new parameter `videosink.c_str()` but you didn't change the function's parameters itself.
btw I'm using the aur package

**Comment by lolwat97** [comment]
Can confirm, freshly cloned repo fails compilation.

**Comment by fduncanh** [comment]
sorry, now fixed 
(some files were forgotten to be included in a previous commit)

**Comment by mohad12211** [comment]
solved with the latest commit
