### ISSUE TITLE
[PROBLEM] Connecting to UxPlay doesnt change anything on the display

### ISSUE THREAD

**Issue by Fallcrim** [FDH2/UxPlay#205]
**OS**
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
```

As told in the title, connecting a device doesnt change the screen. I am running x64 Desktop version and once I run the start command, I don't get errors, but I can still see my desktop like nothing happened. Any ideas why?

**Run command:**
`uxplay -rpiwl -avdec`

**Comment by fduncanh** [comment]
am I correct in interpreting what you say as that you are running a 64-bit version of Raspian  Bullseye on a Raspberry Pi model 4B?

1.  Does Raspian use the Raspberry Pi OS (Bullseye) kernel  tree with support for hardware h264 video decoding by
the Bradcom GPU?   (we haven't tested Raspbian, just Raspberry Pi OS Bullseye) A "pure Debian" kernel does not have this.

See https://github.com/FDH2/UxPlay/wiki/Gstreamer-Video4Linux2-plugin-patches which says:

* IMPORTANT, kernel module bcm2835_codec.ko MUST be present for hardware video decoding. (Raspberry Pi OS, Ubuntu and Manjaro all have it, but if you are using a different distribution, you should check.) Look for it with "find /lib/modules -name bcm2835_codec.ko". There is no point in patching if the bcm2835_codec module is missing.
-
The option  -avdec is for NOT using hardware decoding:  It can't be combined with -rpiwl

Just try with the -d "debug" option
uxplay -avdec -d

What output do you get?   (Try reading the README (including the "Troubleshooting" section)

**Comment by fduncanh** [comment]
Here are examples of debug output from UxPlay with the uxplay -d option: https://github.com/FDH2/UxPlay/wiki/example-of-UxPlay-debug-output

Compare with your own debug output to see where any problem is shown.

**Comment by fduncanh** [comment]
Needs more information for this to be a valid issue.
