### ISSUE TITLE
Add the ability to request a code for connection

### ISSUE THREAD

**Issue by GribouilleVert** [FDH2/UxPlay#208]
Hi,

I use UxPlay to forward the sound of my iPad to my computer, buy when i'm at my work (which is a coworking space with ~40 peoples on the network), people sometime start airplaying on my computer which is qui annoying. I know that airplay has a feature wherin the airplay server can request for the client to provide a code to confirm physical access to the server device (my TV does this). Would it be possible to implement such a feature in UxPlay ? It would be usefull in preventing people on the same network from connecting to your devices without consent.

 \-Vasco

**Comment by fduncanh** [comment]
Not easy to replicate the apple code solution.


An iPad lists a Wi-Fi Address in its "about section"  which is its true MAC address and is reported  to the server as its "device ID"  when the connection is set up   (this not its  macAddress, which I think is randomized for privacy, and visible on  the network).

It would be fairly easy add an option to uxplay   to  only allow connections to clients with a deviceID listed in the uxplay startup file.

**Comment by GribouilleVert** [comment]
Oh ok, thank you for the info !

**Comment by fduncanh** [comment]
@GribouilleVert 

I looked into this, and its easy to implement, so I'll add this feature.
UxPlay will report name, model and deviceID of client that request a connection,
and if option "-restrict" is is used, it will check that deviceID is in the "allowed" list,
specified by option " -allow XX:XX:XX:XX:XX:XX: (probably  entered in the uxplayrc file)
so that it's easy to enter the right number for future connections

**Comment by fduncanh** [comment]
@GribouilleVert 
The code you wanted  is now in the "testing" branch.

The new options  `-restrict [no]` and ``-allow <clientID> `` are documented in uxplay -h and man uxplay, but not yet in the README.

Please test.

 *  **clientID** is reported when a client tries to connect.  
* It is also listed as  Settings->General-> Wi Fi Address on the iOS device (it is the true MACaddress )
 
Add allowed clients in ~/.uxplayrc  (with restrictions enforced) using
```
restrict
allow  XX:XX:XX:XX:XX:XX
allow YY:YY:YY:YY:YY:YY
```


Use 

```
uxplay -restrict no
```
to switch off client checking that is set in ~/.uxplayrc.

Use

```
uxplay -allow ZZ:ZZ:ZZ:ZZ:ZZ:ZZ
```
to allow  a client not listed in ~/.uxplayrc.

**Comment by fduncanh** [comment]
I will probably also add a -block <clientID> option  to block certain clients while not enforcing restictions on others.

**Comment by fduncanh** [comment]
The main branch has this feature (plus an unrelated fix) now

**Comment by fduncanh** [comment]
@GribouilleVert 

The --restrict -allow -block features are included in the latest UxPlay-1.66 (just released).

Let us know if they solve your issue.

**Comment by fduncanh** [comment]
@GribouilleVert 

Latest UxPlay at github (v 1.67) finally supports Apple-Style pin pairing.
https://github.com/FDH2/UxPlay

**Comment by GribouilleVert** [comment]
Awesome, thank you so much !
