### ISSUE TITLE
No audio on raspberry pi 3b plus 

### ISSUE THREAD

**Issue by myagizmaktav** [FDH2/UxPlay#217]
https://github.com/antimof/UxPlay/issues/141?notification_referrer_id=NT_kwDOBuRXV7Q3NzA5MzAyNDU4OjExNTYyNzg2Mw
 the issue moved here.
 

  

>  2. are you using Raspberry Pi OS (Bullseye) (the current release)?
    3. Have you got working audio set up on your R Pi 3b+? (before using uxplay)
    4. why are you showing the -h help text? did you put this option in your startup file?

 2. I'm using the bullseye version. https://i.imgur.com/LfHXSZb.png
 3. No
 4. I try every audio sink method for audio problems.
 
 @fduncanh

**Comment by fduncanh** [comment]
based on your answer to 3.   This seems  not to be a UxPlay issue.  Google for "raspberry pi audio configuration",
don't test uxplay before you have working audio.

First get audio working on the pi.   test it with something that says "left speaker" and "right speaker" when you press on a the corresponding icon.

You need to chose what to output audio to , using raspi-config.   There is analog headphone jack output and hdmi sound output (on R Pi 4b, not sure about 3B+).   Or you can attach a usb speaker to one of the usb ports.

https://www.raspberrypi.com/documentation/computers/configuration.html#audio-configuration

You need to install pulseaudio, I think.

After audio is working, Uxplay should work.

**Comment by fduncanh** [comment]
If you still have issues after getting audio to work (without using uxplay), post a new issue.

* need confirmed working audio _before_ testing UxPlay)
