### ISSUE TITLE
Using UxPlay in Headless Ubuntu Server

### ISSUE THREAD

**Issue by diskun00** [FDH2/UxPlay#220]
Hi,

First, thank a lot for the great project. I am always looking for this kind of software for wireless project. Currently, I am planning using my old laptop with a headless ubuntu server as a mirror server, so that its connected projector can get input from my phone/mac. However, the current installation does not work out well, i.e., 1). the screen is a bit blurred and looks like mozaic (not all color are well displayed). 2). the delay is a bit high as I need to wait ~ 10 seconds to for the connection.

I am wondering if I need to install something additionally. For example, should i install a GUI? Thank you in advance!

**Comment by fduncanh** [comment]
Are you running X11, or  just using the framebuffer?   

On Ubuntu with X11 on the old laptop, uxplay should work.

without X11 try 
```
uxplay -vs kmssink
```


The UxPlay "README" document says:

By default, GStreamer uses an algorithm to search for the best "videosink" (GStreamer's term for a graphics driver to display images) to use. You can overide this with the uxplay option -vs <videosink>. Which videosinks are available depends on your operating system and graphics hardware: use "gst-inspect-1.0 | grep sink | grep -e video -e Video -e image" to see what is available. Some possibilites on Linux/*BSD are:

    glimagesink (OpenGL), waylandsink

    xvimagesink, ximagesink (X11)

    kmssink, fbdevsink (console graphics without X11)

    vaapisink (for Intel/AMD hardware-accelerated graphics); for NVIDIA hardware graphics (with CUDA) use glimagesink combined with "-vd nvh264dec" (or "nvh264sldec", a new variant which will become "nvh264dec" in GStreamer-1.24).


The "kmssink" gstreamer videosink  works on Raspberry Pi.    

I am not sure ihow to get it working  on a intel device.    This is a GStreamer issue .  
Maybe Googling will help.

**Comment by fduncanh** [comment]
OK 

https://www.maketecheasier.com/connect-projector-to-ubuntu-linux/

I don't know about projectors. yet.  Are you running X11 or running in console mode?  (probably X11)

HDMI or VGA?

**Comment by diskun00** [comment]
> OK
> 
> https://www.kentfaith.com/blog/article_how-to-connect-projector-to-linux_1956
> 
> https://www.maketecheasier.com/connect-projector-to-ubuntu-linux/
> 
> I don't know about projectors. yet. Are you running X11 or running in console mode? (probably X11)
> 
> HDMI or VGA?

Hey @fduncanh, thank you for the informative advice. Will check it out later and update here. Regarding my setup,  I am using ubuntu in console model (no gui/x11 installed). A projector is connected via HDMI cable (kinda like a external monitor to my laptop).

**Comment by fduncanh** [comment]
In console mode, try
uxplay -vs kmssink

**Comment by diskun00** [comment]
it works now. Thank you so much!

**Comment by zxystd** [comment]
@diskun00 
> 1). the screen is a bit blurred and looks like mozaic (not all color are well displayed).

Hi, is this problem fixed? I also face the same issue. I am using Ubuntu Desktop 20.04, IPad Pro 2021, the picture looks not 'clear' just like something masking there, for other airplay sink products displaying perfectly(android side)

**Comment by fduncanh** [comment]
@zxystd 

There was no problem in uxplay  that was  "fixed": 

The user @diskun00  was using console mode (not X11 or Wayland) so needed to use option 
"uxplay -vs kmssink"

We  can't know what your issue is without more details
