### ISSUE TITLE
cpu 100%，dead loop。

### ISSUE THREAD

**Issue by CNoob4ever** [FDH2/UxPlay#222]
![image](https://github.com/FDH2/UxPlay/assets/22703081/dcaffcd0-a05a-4db3-afea-b347ec49aad7)
![image](https://github.com/FDH2/UxPlay/assets/22703081/1062d412-d192-4d2d-9b61-7e67650b0ec6)
![image](https://github.com/FDH2/UxPlay/assets/22703081/c8087cbd-e1b6-44f7-bea2-e1827a37b0dc)

**Comment by fduncanh** [comment]
give details.  (about the computer and the OS, uxplay version etc, self-compiled or from a distribution?)

Why did you show the code in the top screen, did you get such a timeout?


I have no idea why llhttp acted strange.


Is this reproducible or a one-time event?

If you can reproduce it, please do it with the uxplay -d (debug) option and post the output here as a "*.txt>" file

**Comment by CNoob4ever** [comment]
> give details. (about the computer and the OS, uxplay version etc, self-compiled or from a distribution?)
> 
> Why did you show the code in the top screen, did you get such a timeout?
> 
> I have no idea why llhttp acted strange.
> 
> Is this reproducible or a one-time event?
> 
> If you can reproduce it, please do it with the uxplay -d (debug) option and post the output here as a "*.txt>" file

**Comment by CNoob4ever** [comment]
> give details. (about the computer and the OS, uxplay version etc, self-compiled or from a distribution?)
> 
> Why did you show the code in the top screen, did you get such a timeout?
> 
> I have no idea why llhttp acted strange.
> 
> Is this reproducible or a one-time event?
> 
> If you can reproduce it, please do it with the uxplay -d (debug) option and post the output here as a "*.txt>" file

Hi, I have done secondary development based on uxplay. The setup includes an N100 mini host, Ubuntu 22.04, and uxplay version 1.64. When connecting and disconnecting AirPlay frequently, there is a chance of triggering a conn_reset, which leads to a probabilistic loop in the s_n_llhttp__internal__n_closed function within the llhttp__internal_run process. Currently, my solution is to use the macro LLHTTP_STRICT_MODE=1 to address the issue.

**Comment by fduncanh** [comment]
Is this a llhttp bug?

*  Try replacing the contents of the lib/llhttp directory with llhttp v6.0.7  (find it in a github versiion of UxPlay dated before
2022.10.29

* is it a uxplay bug?  (in the conn_reset code, I reset should shut down processes involving http parsing (which is what llhttp does)

* can it be reliably reproduced by triggering a conn_reset?  (just shut down the wifi on the client, and a "normal" reset will occur after 15 secs.)

There is also a possibilty of an unclean socket after a reset, it might be the issue.

*   should llhttp be running with LLHTTP_STRICT_MODE=1 anyway?

you can help uxplay by diagnosing this more to fix any issue in the code.

**Comment by fduncanh** [comment]
> I believe this is a bug. I have looked at several versions of llhttp on GitHub, and in s_n_llhttp__internal__n_closed, there is no infinite loop. I have added LLHTTP_STRICT_MODE=1 to the compiler, and in the past few days of testing, I haven't encountered any issues.

* bug in uxplay?   (as opposed to a bug in llhtpp ?)  does the issue occur also in older llhttp versions?
* how do you "add LLHTTP_STRIC_MODE=1" to the compiler?

**Comment by fduncanh** [comment]
Thanks for your investigations.    I would like to try to make a bug report to llhttp.

To help with this I have made two new branches of UxPlay on github:

* branch llhttp605, which is a roll back to the point where the original  llhttp author (indutny)  handed over to a new maintainer(who then handed over to a newer maintainer who seems enthusiastic to make  "improvements")

* branch llhttp912,   the latest release.

can you test these (without STRICT_MODE changes) to see if both , either, or none of these show the bug you see.

Thanks!

* you should just clone new copies of UxPlay in two new directories:

```
mkdir llhttp605
cd llhttp605
git clone http://github.com/FDH2/UxPlay
cd UxPlay
git checkout llhttp605
mkdir build
cd build
cmake ..
make
```
 then run ./uxplay

repeat  for llhttp912 in the other directory.

**Comment by fduncanh** [comment]
this is your suspect section of code in 6.0.5

```
static llparse_state_t llhttp__internal__run(
    llhttp__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  int match;
  switch ((llparse_state_t) (intptr_t) state->_current) {
    case s_n_llhttp__internal__n_closed:
    s_n_llhttp__internal__n_closed: {
      if (p == endp) {
        return s_n_llhttp__internal__n_closed;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llhttp__internal__n_closed;
        }
        case 13: {
          p++;
          goto s_n_llhttp__internal__n_closed;
        }
        default: {
          p++;
          goto s_n_llhttp__internal__n_error_4;
        }
      }
      /* UNREACHABLE */;
      abort();
    }
```

here it is in

**Comment by fduncanh** [comment]
@CNoob4ever 


> Hi, I have done secondary development based on uxplay. The setup includes an N100 mini host, Ubuntu 22.04, and uxplay version 1.64. When connecting and disconnecting AirPlay frequently, there is a chance of triggering a conn_reset, which leads to a probabilistic loop in the s_n_llhttp__internal__n_closed function within the llhttp__internal_run process. Currently, my solution is to use the macro LLHTTP_STRICT_MODE=1 to address the issue.

I see that conn_reset (in uxplay.cpp) calls raop_stop (in lib/raop.c) which calls httpd_stop ( in lib/httpd.c)

**maybe  simply changing raop_stop so it calls httpd_destroy rather than http_stop will fix your issue, without LLHTTP_STRICT=1**  (just edit "https_stop" to "httpd_destroy")
"
can you test?

**Comment by fduncanh** [comment]
@CNoob4ever 

any more details are welcomed here

**Comment by fduncanh** [comment]
closed, (will reopen if more into is provided)
can't duplicate
