### ISSUE TITLE
Build Windows full executable

### ISSUE THREAD

**Issue by vpuedro** [FDH2/UxPlay#224]
I hope this message finds you well. I am reaching out to discuss the exciting project we've been working on. We are currently exploring the possibility of compiling the program, inclusive of all required libraries, to enable standalone execution on a different workstation.

Could you kindly advise if it is feasible to achieve this goal? Your insights and expertise in this matter would be greatly appreciated.

Thank you for your time, and we believe that this project has incredible potential!

**Comment by vpuedro** [comment]
Sorry, I've workd on it, I'll publish PR soon

**Comment by fduncanh** [comment]
Someone has already  been distributing a compiled version of UxPlay for windows (found on the web)
https://www.pogs.cafe/iphone

It can certainly be done.

**Comment by fduncanh** [comment]
not actually an issue, so closing.    (feel free to add more comments here.)

**Comment by Durian-p** [comment]
> Someone has already been distributing a compiled version of UxPlay for windows (found on the web) https://www.pogs.cafe/iphone
> 
> It can certainly be done.

I exec the .exe from the website and my computer got hacked recently!! My properties in steam account were sold and stolen. I am pretty sure this exe is the one that cause this. I checked the exe. It will contact the IP 192.229.211.108, and download some .bin files that looks funny.  I checked the IP and it most likely to be a malicious IP. So DONT USE THE SOFTWARE in this site!!!
![uxplay_report](https://github.com/FDH2/UxPlay/assets/88613370/68433556-f2dd-4f99-9d36-baa1182252f9)

Check out this post for more information about this IP:
https://www.reddit.com/r/sophos/comments/12ddqns/an_attempt_to_communicate_with_a_botnet_or/

**Comment by Durian-p** [comment]
> > Someone has already been distributing a compiled version of UxPlay for windows (found on the web) https://www.pogs.cafe/iphone
> > It can certainly be done.
> 
> I exec the .exe from the website and my computer got hacked recently!! My properties in steam account were sold and stolen. I am pretty sure this exe is the one that cause this. I checked the exe. It will contact the IP 192.229.211.108, and download some .bin files that looks funny. I checked the IP and it most likely to be a malicious IP. So DONT USE THE SOFTWARE in this site!!! ![uxplay_report](https://private-user-images.githubusercontent.com/88613370/318181485-68433556-f2dd-4f99-9d36-baa1182252f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTE3NDksIm5iZiI6MTcxMTc5MTQ0OSwicGF0aCI6Ii84ODYxMzM3MC8zMTgxODE0ODUtNjg0MzM1NTYtZjJkZC00Zjk5LTlkMzYtYmFhMTE4MjI1MmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5MzcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3M2MxMzg4NDJiNDEwM2ZiYzU1NDUyYzhiNmJmZjVkMzkyZDllMGNjNWQ1YmYzNDI3Y2Y1MmNmNTc1YjE3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlf8xOyTv5oa5eVDUSupOejdtSDcZ9Ar_t7zALjhAkw)
> 
> Check out this post for more information about this IP: https://www.reddit.com/r/sophos/comments/12ddqns/an_attempt_to_communicate_with_a_botnet_or/

definitely malicious!!
![image](https://github.com/FDH2/UxPlay/assets/88613370/859d7794-7d6b-457a-bb56-360a8766fe4f)
![image](https://github.com/FDH2/UxPlay/assets/88613370/ff2272a8-e044-4481-be95-837fa6426fcf)
![image](https://github.com/FDH2/UxPlay/assets/88613370/a491a051-7dc0-439b-ba60-1b57f91e6490)

**Comment by fduncanh** [comment]
I disabled the link to that site, and added a warning.

Much safer (and easy) to build UxPlay from source on Windowss
