### ISSUE TITLE
Multple Screens

### ISSUE THREAD

**Issue by mischaelschill** [FDH2/UxPlay#225]
Is there a way to have multiple instances running, so that I can mirror/extend on multiple screens?

**Comment by fduncanh** [comment]
Is this for having more than one display for a Mac client?

Right now uxplay can only have a single mirror window on the server.


Do modern AppleTV's do what you want?

**Comment by fduncanh** [comment]
You can run multiple instances of UxPlay  on  the same server.   Just give them different (random)  MAC addresses with the 
-m option and different server names.

In terminal 1
uxplay -m -n uxplay1

in terminal 2
uxplay  -m -n uxplay2

They both were running, but I could  not get a M2 macbook to mirror (or screen-extend) to more
 than one instance at a time.

When I activated uxplay2 mirroring, the mac dropped mirroring to uxplay1.
I guess I could mirror _two  different macs_ simultaneously, one to  uxplay1 and one to uxplay2, each on a different window.

The obstacle to multiple displays for a single mac seems a macOS issue, not a UxPlay issue.  (???)

closing the issue, but feel free to post more details
