### ISSUE TITLE
How to implement multiple screens?

### ISSUE THREAD

**Issue by Mangomm** [FDH2/UxPlay#227]
Hello, when I have multiple ios devices, how do I screen them to my computer through UxPlay?
This should be a very common need.

**Comment by fduncanh** [comment]
currently UxPlay can only handle one client at a time,

You could run multiple instances on uxplay, provided they have different server names and MAC addresses (use option -m)

```
uxplay -m -n UxPlay1

uxplay -m -n UxPlay2

etc
```
