### ISSUE TITLE
Can't play audio dump file

### ISSUE THREAD

**Issue by Mangomm** [FDH2/UxPlay#229]
base https://github.com/FDH2/UxPlay/issues/121.

Hello, how is this problem now? I also encountered the same problem, I used Uxplay to obtain h264 and audio data, and then sent ffmpeg+sdl to play. The video is successfully displayed, but the audio in ffmpeg cannot be decoded successfully.

When I use the command to get dump audio file:
/uxplay -p 30445,30446, 30447 -vs kmsssink -as pulsesink  -n uxplay  -nh -admp ./uxplay-adump

Then play it with vlc or ffplay and find it doesn't play.
What should I do to successfully play the audio?

vlc:
/home/admin1/eng/vlc/vlc

VLC media player 4.0.0-dev Otto Chriek (revision 4.0.0-dev-23113-Gf7BB59D9F5)
[000055f562fbdd30] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Mpeg4GASpecificConfig: error 1
Mpeg4GASpecificConfig: error 1
Mpeg4GASpecificConfig: error 1
Mpeg4GASpecificConfig: error 1
[00007f555c0041f0] mpeg4audio demux packetizer error: latm sub frames not yet supported, please send a sample
Mpeg4GASpecificConfig: error 1
Mpeg4GASpecificConfig: error 1
^CQObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
admin1@admin1:~/airplay/UxPlay/build$

ffplay:
./ffplay   ~/airplay/UxPlay/build/uxplay-adump.1.aac

[aac @ 0x7feab4000cc0] Format aac detected only with low score of 1, misdetection possible!
[aac @ 0x7feab4001e80] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] channel element 1.13 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] channel element 2.11 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (62) exceeds limit (40).
[aac @ 0x7feab4001e80] channel element 3.11 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (29) exceeds limit (5).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Pulse data corrupt or invalid.
[aac @ 0x7feab4001e80] channel element 3.1 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 3.6 is not allocated
[aac @ 0x7feab4001e80] Number of bands (44) exceeds limit (37).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (53) exceeds limit (40).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] channel element 2.13 is not allocated
[aac @ 0x7feab4001e80] channel element 1.15 is not allocated
[aac @ 0x7feab4001e80] Number of bands (63) exceeds limit (39).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (22) exceeds limit (13).
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (53) exceeds limit (40).
[aac @ 0x7feab4001e80] channel element 1.4 is not allocated
[aac @ 0x7feab4001e80] SBR was found before the first channel element.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (46) exceeds limit (40).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] channel element 3.5 is not allocated
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (53) exceeds limit (40).
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 3.5 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 10 times
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (43) exceeds limit (40).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (52) exceeds limit (28).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
    Last message repeated 1 times
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 3.0 is not allocated
[aac @ 0x7feab4001e80] Number of bands (10) exceeds limit (8).
[aac @ 0x7feab4001e80] channel element 3.0 is not allocated
[aac @ 0x7feab4001e80] channel element 3.3 is not allocated
[aac @ 0x7feab4001e80] channel element 3.8 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Number of bands (44) exceeds limit (41).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] decode_pce: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] channel element 3.1 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
    Last message repeated 1 times
[aac @ 0x7feab4001e80] Prediction is not allowed in AAC-LC.
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] channel element 2.6 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Gain control is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (25) exceeds limit (14).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] Number of bands (13) exceeds limit (8).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] channel element 3.14 is not allocated
[aac @ 0x7feab4001e80] channel element 2.2 is not allocated
[aac @ 0x7feab4001e80] channel element 2.0 is not allocated
[aac @ 0x7feab4001e80] channel element 1.8 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] channel element 1.14 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 22 times
[aac @ 0x7feab4001e80] channel element 1.1 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (11) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 2.5 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (3) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 2.13 is not allocated
[aac @ 0x7feab4001e80] channel element 2.2 is not allocated
[aac @ 0x7feab4001e80] Number of bands (53) exceeds limit (29).
[aac @ 0x7feab4001e80] channel element 2.13 is not allocated
[aac @ 0x7feab4001e80] channel element 2.14 is not allocated
[aac @ 0x7feab4001e80] channel element 2.12 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] channel element 3.13 is not allocated
[aac @ 0x7feab4001e80] channel element 2.1 is not allocated
[aac @ 0x7feab4001e80] Number of bands (27) exceeds limit (6).
[aac @ 0x7feab4001e80] Number of bands (28) exceeds limit (26).
[aac @ 0x7feab4001e80] Number of bands (7) exceeds limit (1).
[aac @ 0x7feab4001e80] channel element 3.11 is not allocated
[aac @ 0x7feab4001e80] channel element 1.5 is not allocated
[aac @ 0x7feab4001e80] channel element 1.0 is not allocated
[aac @ 0x7feab4001e80] Number of bands (27) exceeds limit (12).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (18) exceeds limit (4).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of bands (22) exceeds limit (4).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (6) exceeds limit (5).
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (56) exceeds limit (40).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (9) exceeds limit (7).
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 24 times
[aac @ 0x7feab4001e80] channel element 2.13 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] channel element 1.5 is not allocated
[aac @ 0x7feab4001e80] channel element 3.8 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Prediction is not allowed in AAC-LC.
[aac @ 0x7feab4001e80] channel element 3.2 is not allocated
[aac @ 0x7feab4001e80] channel element 1.13 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 24 times
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (22) exceeds limit (10).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (44) exceeds limit (40).
[aac @ 0x7feab4001e80] channel element 3.6 is not allocated
[aac @ 0x7feab4001e80] channel element 2.10 is not allocated
[aac @ 0x7feab4001e80] channel element 3.1 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (42) exceeds limit (41).
[aac @ 0x7feab4001e80] SBR was found before the first channel element.
[aac @ 0x7feab4001e80] channel element 1.3 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of bands (41) exceeds limit (29).
[aac @ 0x7feab4001e80] channel element 1.9 is not allocated
[aac @ 0x7feab4001e80] channel element 3.5 is not allocated
[aac @ 0x7feab4001e80] channel element 2.15 is not allocated
[aac @ 0x7feab4001e80] channel element 1.1 is not allocated
[aac @ 0x7feab4001e80] channel element 2.14 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] channel element 1.10 is not allocated
[aac @ 0x7feab4001e80] channel element 3.2 is not allocated
[aac @ 0x7feab4001e80] channel element 1.7 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of bands (6) exceeds limit (3).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 1.3 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (53) exceeds limit (40).
[aac @ 0x7feab4001e80] channel element 2.8 is not allocated
[aac @ 0x7feab4001e80] Number of bands (3) exceeds limit (2).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (50) exceeds limit (40).
[aac @ 0x7feab4001e80] Number of bands (3) exceeds limit (1).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of bands (51) exceeds limit (36).
[aac @ 0x7feab4001e80] Number of bands (4) exceeds limit (1).
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 24 times
[aac @ 0x7feab4001e80] channel element 2.5 is not allocated
[aac @ 0x7feab4001e80] channel element 0.2 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] skip_data_stream_element: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] Number of bands (7) exceeds limit (1).
[aac @ 0x7feab4001e80] channel element 3.6 is not allocated
[aac @ 0x7feab4001e80] Number of bands (20) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 3.11 is not allocated
[aac @ 0x7feab4001e80] channel element 1.0 is not allocated
[aac @ 0x7feab4001e80] channel element 3.0 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 24 times
[aac @ 0x7feab4001e80] channel element 3.9 is not allocated
[aac @ 0x7feab4001e80] channel element 1.7 is not allocated
[aac @ 0x7feab4001e80] channel element 1.4 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (6) exceeds limit (1).
[aac @ 0x7feab4001e80] channel element 3.9 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (50) exceeds limit (41).
[aac @ 0x7feab4001e80] channel element 1.4 is not allocated
[aac @ 0x7feab4001e80] Number of bands (11) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 2.8 is not allocated
[aac @ 0x7feab4001e80] channel element 3.13 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Prediction is not allowed in AAC-LC.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of bands (6) exceeds limit (2).
[aac @ 0x7feab4001e80] Number of bands (11) exceeds limit (7).
[aac @ 0x7feab4001e80] channel element 3.10 is not allocated
    Last message repeated 1 times
[aac @ 0x7feab4001e80] Number of bands (24) exceeds limit (5).
[aac @ 0x7feab4001e80] Number of bands (24) exceeds limit (19).
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 24 times
[aac @ 0x7feab4001e80] skip_data_stream_element: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] Number of bands (9) exceeds limit (4).
[aac @ 0x7feab4001e80] Number of bands (14) exceeds limit (12).
[aac @ 0x7feab4001e80] Pulse tool not allowed in eight short sequence.
[aac @ 0x7feab4001e80] channel element 2.8 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (46) exceeds limit (40).
[aac @ 0x7feab4001e80] channel element 1.14 is not allocated
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] decode_pce: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 2.5 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (42) exceeds limit (41).
[aac @ 0x7feab4001e80] channel element 1.8 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (54) exceeds limit (51).
[aac @ 0x7feab4001e80] Number of bands (21) exceeds limit (16).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] ms_present = 3 is reserved.
[aac @ 0x7feab4001e80] Number of bands (26) exceeds limit (25).
[aac @ 0x7feab4001e80] Number of bands (9) exceeds limit (6).
[aac @ 0x7feab4001e80] skip_data_stream_element: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] Number of bands (11) exceeds limit (2).
[aac @ 0x7feab4001e80] Number of bands (22) exceeds limit (11).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (15) exceeds limit (14).
[aac @ 0x7feab4001e80] channel element 1.7 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Prediction is not allowed in AAC-LC.
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 1.9 is not allocated
[aac @ 0x7feab4001e80] Number of bands (6) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 2.10 is not allocated
[aac @ 0x7feab4001e80] channel element 3.12 is not allocated
[aac @ 0x7feab4001e80] channel element 3.0 is not allocated
[aac @ 0x7feab4001e80] channel element 1.0 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 21 times
[aac @ 0x7feab4001e80] channel element 2.8 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (11) exceeds limit (9).
[aac @ 0x7feab4001e80] channel element 3.10 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Number of bands (3) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 2.2 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (17) exceeds limit (12).
[aac @ 0x7feab4001e80] channel element 3.4 is not allocated
[aac @ 0x7feab4001e80] Number of bands (11) exceeds limit (2).
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 21 times
[aac @ 0x7feab4001e80] channel element 3.8 is not allocated
[aac @ 0x7feab4001e80] channel element 3.7 is not allocated
[aac @ 0x7feab4001e80] channel element 1.1 is not allocated
[aac @ 0x7feab4001e80] Number of bands (41) exceeds limit (39).
[aac @ 0x7feab4001e80] channel element 2.2 is not allocated
[aac @ 0x7feab4001e80] Number of bands (29) exceeds limit (16).
[aac @ 0x7feab4001e80] channel element 1.15 is not allocated
[aac @ 0x7feab4001e80] Number of bands (5) exceeds limit (4).
[aac @ 0x7feab4001e80] channel element 3.0 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 21 times
[aac @ 0x7feab4001e80] channel element 3.5 is not allocated
[aac @ 0x7feab4001e80] skip_data_stream_element: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] Number of bands (10) exceeds limit (6).
[aac @ 0x7feab4001e80] channel element 2.13 is not allocated
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 2.9 is not allocated
[aac @ 0x7feab4001e80] channel element 2.2 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Too large remapped id is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7feab4001e80] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (56) exceeds limit (41).
[aac @ 0x7feab4001e80] channel element 1.6 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (23) exceeds limit (7).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (29) exceeds limit (12).
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 3.5 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 25 times
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 2.2 is not allocated
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (37) exceeds limit (27).
[aac @ 0x7feab4001e80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Prediction is not allowed in AAC-LC.
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 22 times
[aac @ 0x7feab4001e80] channel element 3.14 is not allocated
[aac @ 0x7feab4001e80] Number of scalefactor bands in group (54) exceeds limit (40).
[aac @ 0x7feab4001e80] skip_data_stream_element: Input buffer exhausted before END element found
[aac @ 0x7feab4001e80] Number of bands (5) exceeds limit (2).
[aac @ 0x7feab4001e80] channel element 2.9 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] Number of bands (41) exceeds limit (38).
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 22 times
[aac @ 0x7feab4001e80] channel element 2.7 is not allocated
[aac @ 0x7feab4001e80] Reserved bit set.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4001e80] channel element 1.13 is not allocated
[aac @ 0x7feab4001e80] channel element 1.1 is not allocated
[aac @ 0x7feab4001e80] channel element 3.0 is not allocated
[aac @ 0x7feab4001e80] Dependent coupling is not supported together with LTP
    Last message repeated 22 times
[aac @ 0x7feab4001e80] channel element 3.2 is not allocated
[aac @ 0x7feab4001e80] Error decoding AAC frame header.
[aac @ 0x7feab4001e80] invalid band type
[aac @ 0x7feab4000cc0] Estimating duration from bitrate, this may be inaccurate
[aac @ 0x7feab4000cc0] Could not find codec parameters for stream 0 (Audio: aac (LTP), 5.1, fltp, 396 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, aac, from '/home/admin1/airplay/UxPlay/build/uxplay-adump.1.aac':
  Duration: 00:00:21.46, bitrate: 398 kb/s
  Stream #0:0: Audio: aac (LTP), 3.0, fltp, 396 kb/s
Failed to open file '/home/admin1/airplay/UxPlay/build/uxplay-adump.1.aac' or configure filtergraph
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0

**Comment by fduncanh** [comment]
Unfortunately the   audio dump file was just added for debugging purposes.   We don't know how to containerize it to make it playable.
