### ISSUE TITLE
Larger resolution than 1920x1080 (macOS Sonoma client issue)

### ISSUE THREAD

**Issue by ionull** [FDH2/UxPlay#231]
When I set it to 2560x1440 or larger, there's only error log from VLC:
unexpected partitioned VCL NAL unit: nalu_type = 2, ref_idc = 0, nalu_size = 3793,processed bytes 4, payloadsize = 3797 nalus_count = 1
unexpected partitioned VCL NAL unit: nalu_type = 2, ref_idc = 0, nalu_size = 3793,processed bytes 4, payloadsize = 3797 nalus_count = 1

**Comment by fduncanh** [comment]
Thanks for the report.

What is the iOS device? (is it one of the larger new ipads?)

Does the image get displayed at all?   Or are you just reporting the error message?

**Comment by ionull** [comment]
Hi, it's mirroring from my MacBook Pro to my iMac 5k with Ubuntu. The speed
should be ok because they are linked by cable. It works well when iMac
running on macOS. There is no any image displayed when set larger
resolution than 1080p.

**Comment by fduncanh** [comment]
looking at the code, it seems this is just an informational message about the type of video data package ("NAL unit")
received.      We havent seen "slice data" NAL's before.  
Do they fail to get processd properly?

If this can be reproduced it can probably get fixed.
```  
                    int nalu_type = payload_decrypted[nalu_size] & 0x1f;
                    int ref_idc = (payload_decrypted[nalu_size] >> 5);		    
                    switch (nalu_type) {
                    case 14:  /* Prefix NALu , seen before all VCL Nalu's in AirMyPc */
                    case 5:   /*IDR, slice_layer_without_partitioning */
                    case 1:   /*non-IDR, slice_layer_without_partitioning */
                        break;
	            case 2:   /* slice data partition A */
                    case 3:   /* slice data partition B */
                    case 4:   /* slice data partition C */
                        logger_log(raop_rtp_mirror->logger, LOGGER_INFO,
                                   "unexpected partitioned VCL NAL unit: nalu_type = %d, ref_idc = %d, nalu_size = %d,"
                                   "processed bytes %d, payloadsize = %d nalus_count = %d",
                                   nalu_type, ref_idc, nc_len, nalu_size, payload_size, nalus_count);
                        break;
                    case 6:
                        if (logger_debug) {
                            char *str = utils_data_to_string(payload_decrypted + nalu_size, nc_len, 16); 
                            logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG, "raop_rtp_mirror SEI NAL size = %d", nc_len);		
                            logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG,
                                       "raop_rtp_mirror h264 Supplemental Enhancement Information:\n%s", str);
                            free(str);
                        }
                        break;
                    case 7:
                        if (logger_debug) {
                            char *str = utils_data_to_string(payload_decrypted + nalu_size, nc_len, 16); 
                            logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG, "raop_rtp_mirror SPS NAL size = %d", nc_len);		
                            logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG,
                                       "raop_rtp_mirror h264 Sequence Parameter Set:\n%s", str);
                            free(str);
                        }
                        break;
                    case 8:
                        if (logger_debug) {
                            char *str = utils_data_to_string(payload_decrypted + nalu_size, nc_len, 16); 
                            logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG, "raop_rtp_mirror PPS NAL size = %d", nc_len);		
                            logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG,
                                       "raop_rtp_mirror h264 Picture Parameter Set :\n%s", str);
                            free(str);
                        }
                        break;
                    default:
                        logger_log(raop_rtp_mirror->logger, LOGGER_INFO,
                                   "unexpected non-VCL NAL unit: nalu_type = %d, ref_idc = %d, nalu_size = %d,"
                                   "processed bytes %d, payloadsize = %d nalus_count = %d",
                                   nalu_type, ref_idc, nc_len, nalu_size, payload_size, nalus_count);
			break;
		    }
                    nalu_size += nc_len;
                }
```

**Comment by ionull** [comment]
It can be reproduced every time. I am not familiar with C programming but
can help testing.

**Comment by fduncanh** [comment]
The message is just informational.

What actually happens with
the video?

What  kind of iOS client device is producing this video?

iPad/ iPone, which model, which vesion of iOS / iPadOS etc.

what uxplay command is being used (what options?)

**Comment by fduncanh** [comment]
NAL units are part of H264 video format data

https://en.wikipedia.org/wiki/Network_Abstraction_Layer

**Comment by ionull** [comment]
Hi
There is no "iOS" device but a MacBook Pro using screen mirroring.
Launch command: uxplay -vs waylandsink -fs
Config: s 2560x1440

**Comment by fduncanh** [comment]
OK 
This can be tested (maybe only  next week , or the week after).

Right now its assumed that each video NAL unit is a complete video frame, maybe the three "partitioned slices"
should be grouped  together and sent to gstreamer as a group.


* you still have still not described what actually happens :  Does the screen image (a) not get displayed (b) get partially displayed or (c)????  when -s 2650x1440 option is used

* a  debug output (use option uxplay -d ....) would be useful.    Post it here as a "*.txt"
 file using drag and drop.

**Comment by ionull** [comment]
Hi, thanks for response.
* I have told it in previous comment: no any image displayed
* 
[uxplay-debug.txt](https://github.com/FDH2/UxPlay/files/13059690/uxplay-debug.txt)

**Comment by fduncanh** [comment]
Its probably because iOS clients dont snd "partioned slices"so we did not see them before.

I'm guessing the larger  image needed partitioning.   If we can understand the H264 details, this can probably be fixed

https://stackoverflow.com/questions/19642736/count-frames-in-h-264-bitstream

**Comment by fduncanh** [comment]
Just a thought:

can you check if an older uxplay release (say 1.62) also has the issue?

The "video resumed" line in the debug output might come from a recent change

look in "releases" o the uxplay web page

**Comment by fduncanh** [comment]
For reference:

http://www.szatmary.org/blog/25

**Comment by ionull** [comment]
Hi, I just make install 1.62. It can display but the resolution is the same, no 2560x1440

**Comment by fduncanh** [comment]
Thanks.

The issue will be looked at, my guess is it can be fixed, and finding out how to process NAL units with partitioned slices"

**Comment by ionull** [comment]
BTW, when I set fps to 60, there's the same error log without any image displayed.

**Comment by fduncanh** [comment]
the fps setting tell the client what the maximum acceptable fps is.  Its up to the client to decide what fps to use.

No one is available to investigate this issue at the moment.  In a week's time probably.

**Comment by ionull** [comment]
No hurry, thanks for your hard working ;)

**Comment by fduncanh** [comment]
finally had the opportunity to test.

uxplay -s 2650x1440 

seems to be working fine to mirror a macbook M2 2023
The debug output shows that the  client (the macbook) is indeed sending video with 2560x1440
The screen image filled the big screen on the uxplay server., which can  display 2650x1440

* so not sure what causes your issue,  we can't reproduce it yet.

```
raop_rtp_mirror accepting client

Received unencrypted codec packet from client: payload_size 39 header 01 00 16 01  ts_client = 155214.533833
raop_rtp_mirror: unidentified extra header data  0.000000, 0.000000
begin video stream wxh = 2560x1440; source 2560x1440
raop_rtp_mirror width_source = 2560.000000 height_source = 1440.000000 width = 2560.000000 height = 1440.000000
raop_rtp_mirror: SPS+PPS header size = 6
raop_rtp_mirror h264 SPS+PPS header:
01 64 00 33 ff e1 

raop_rtp_mirror SPS NAL size = 20
raop_rtp_mirror h264 Sequence Parameter Set:
27 64 00 33 ac 56 80 28 00 b5 a6 e0 20 20 20 da 
08 84 65 80 

raop_rtp_mirror PPS NAL size = 4
raop_rtp_mirror h264 Picture Parameter Set:
28 ee 37 27 

remainder size = 4
remainder of SPS+PPS packet:
fd f8 f8 00 

video renderer paused
raop_rtp video: now = 1698172794.698381, ntp = 1698172794.638531, latency = 0.059850, ts = 155214.533833, 00 10 00 00 
raop_rtp_mirror SEI NAL size = 30
raop_rtp_mirror h264 Supplemental Enhancement Information:
06 05 1a 47 56 4a dc 5c 4c 43 3f 94 ef c5 11 3c 
d1 43 a8 01 ff cc cc ff 02 00 7a 12 00 80 

video renderer resumed
Begin streaming to GStreamer video pipeline
Looking for X11 UxPlay Window, attempt 1
raop_rtp video: now = 1698172794.708889, ntp = 1698172794.671864, latency = 0.037025, ts = 155214.567167, 00 00 00 00 
video renderer resumed
Looking for X11 UxPlay Window, attempt 2
httpd receiving on socket 24
```

**Comment by fduncanh** [comment]
@ionull Our  test was on a macbook running Ventura 13.6. no strange partitioned NAL: units were seen

What OS is you macbook using?

**Comment by ionull** [comment]
@fduncanh Hi, I am using macOS Sonoma (m1 pro mackbook 14)

**Comment by fduncanh** [comment]
OK since macOS ventura works perfectly, will need to update out test machine to Sonoma to investigate your issue.

**Comment by fduncanh** [comment]
@ionull 

* now have updated the macOS client to Sonoma, but UxPlay still works perfectly at 2560x1440

see debug output below (from after video starts):

```
raop_rtp_mirror accepting client

Received unencrypted codec packet from client: payload_size 39 header 01 00 16 01  ts_client = 204.833833
raop_rtp_mirror: unidentified extra header data  0.000000, 0.000000
begin video stream wxh = 2560x1440; source 2560x1440
raop_rtp_mirror width_source = 2560.000000 height_source = 1440.000000 width = 2560.000000 height = 1440.000000
raop_rtp_mirror: SPS+PPS header size = 6
raop_rtp_mirror h264 SPS+PPS header:
01 64 00 33 ff e1 

raop_rtp_mirror SPS NAL size = 20
raop_rtp_mirror h264 Sequence Parameter Set:
27 64 00 33 ac 56 80 28 00 b5 a6 e0 20 20 20 da 
08 84 65 80 

raop_rtp_mirror PPS NAL size = 4
raop_rtp_mirror h264 Picture Parameter Set:
28 ee 37 27 

remainder size = 4
remainder of SPS+PPS packet:
fd f8 f8 00 

video renderer paused

raop_ntp send time type_t=82 packetlen = 32, now = 1698218649.026339
80 d2 00 07 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 e8 e3 41 19 06 be 27 ad 

raop_ntp receive time type_t=83 packetlen = 32, now = 1698218649.031012 t1 = 205.159171, t2 = 205.159207
80 d3 00 07 00 00 00 00 e8 e3 41 19 06 be 27 ad 
83 aa 7f 4d 28 bf 75 3d 83 aa 7f 4d 28 c1 cd 06 

raop_ntp sync correction = 0
raop_rtp video: now = 1698218649.044293, ntp = 1698218648.704330, latency = 0.339963, ts = 204.833833, 00 10 00 00 
raop_rtp_mirror SEI NAL size = 30
raop_rtp_mirror h264 Supplemental Enhancement Information:
06 05 1a 47 56 4a dc 5c 4c 43 3f 94 ef c5 11 3c 
d1 43 a8 01 ff cc cc ff 02 00 5b 8d 80 80 

video renderer resumed
Begin streaming to GStreamer video pipeline
Looking for X11 UxPlay Window, attempt 1
raop_rtp video: now = 1698218649.056915, ntp = 1698218648.770997, latency = 0.285919, ts = 204.900500, 00 00 00 00 
video renderer resumed
Looking for X11 UxPlay Window, attempt 2
raop_rtp video: now = 1698218649.071294, ntp = 1698218648.804330, latency = 0.266964, ts = 204.933833, 00 00 00 00 
video renderer resumed
Looking for X11 UxPlay Window, attempt 3

*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode

raop_rtp video: now = 1698218649.118451, ntp = 1698218649.137663, latency = -0.019212, ts = 205.267167, 00 00 00 00 
raop_rtp video: now = 1698218649.118537, ntp = 1698218649.170997, latency = -0.052460, ts = 205.300500, 00 00 00 00 
raop_rtp video: now = 1698218649.128378, ntp = 1698218649.204330, latency = -0.075952, ts = 205.333833, 00 00 00 00 
raop_rtp video: now = 1698218649.155681, ntp = 1698218649.237663, latency = -0.081982, ts = 205.367167, 00 00 00 00 
raop_rtp video: now = 1698218649.183962, ntp = 1698218649.270997, latency = -0.087035, ts = 205.400500, 00 00 00 00 
raop_rtp video: now = 1698218649.210272, ntp = 1698218649.304330, latency = -0.094057, ts = 205.433833, 00 00 00 00 
raop_rtp video: now = 1698218649.239367, ntp = 1698218649.337663, latency = -0.098296, ts = 205.467167, 00 00 00 00 
raop_rtp video: now = 1698218649.346909, ntp = 1698218649.370996, latency = -0.024088, ts = 205.500500, 00 00 00 00 
raop_rtp video: now = 1698218649.347399, ntp = 1698218649.404330, latency = -0.056930, ts = 205.533833, 00 00 00 00 

Received video streaming performance info packet from client: payload_size 194 header 05 00 00 00  ts_raw = 0
raop_rtp video: now = 1698218649.347684, ntp = 1698218649.437663, latency = -0.089979, ts = 205.567167, 00 00 00 00 
raop_rtp video: now = 1698218649.369867, ntp = 1698218649.470997, latency = -0.101130, ts = 205.600500, 00 00 00 00 

```

**Comment by ionull** [comment]
Is it because my Linux is a "iMac 2014"?

**Comment by fduncanh** [comment]
@ionull 

The problem in your debug seems to be 

```
raop_rtp_mirror accepting client

Received unencrypted codec packet from client: payload_size 0 header 01 00 16 01  ts_client = 337090.007167
raop_rtp_mirror, discard type 0x01 packet with no payload
```

> ``

**Comment by fduncanh** [comment]
> Is it because my Linux is a "iMac 2014"?

It shouldn't matter, you are running Ubuntu on it.  Which Ubuntu exactly?

**Comment by ionull** [comment]
Ubuntu 22.04

**Comment by fduncanh** [comment]
will retest on Ubuntu 22.04  (on an intel PC)

**Comment by ionull** [comment]
I tried to airplay my MacBookPro mid 2012 with Mojave system, it can airplay to my Linux with 5k resolution set. However I can't find a way to cable link them. The resolution is only 1080p.

**Comment by fduncanh** [comment]
no problem on Ubunt 22.04.1  on intel pc
```
raop_rtp_mirror accepting client

Received unencrypted codec packet from client: payload_size 39 header 01 00 16 01  ts_client = 976.833833
raop_rtp_mirror: unidentified extra header data  0.000000, 0.000000
begin video stream wxh = 2560x1440; source 2560x1440
raop_rtp_mirror width_source = 2560.000000 height_source = 1440.000000 width = 2560.000000 height = 1440.000000
raop_rtp_mirror: SPS+PPS header size = 6
raop_rtp_mirror h264 SPS+PPS header:
01 64 00 33 ff e1 

```

your issue is in the apparently empty data packet set by the client, not anything on the server, it appears.

I look to see if a simple code change could provide more information on that.

**Comment by fduncanh** [comment]
@ionull 
I believe you said your system worked for "uxplay -s 1920x1080"

Please post the debug trace (just the bit starting with "raop_rtp_mirror accepting client") in that (working) case.

**Comment by ionull** [comment]
[uxplay-log-work.txt](https://github.com/FDH2/UxPlay/files/13163033/uxplay-log-work.txt)

**Comment by fduncanh** [comment]
You 1920x1080 debug is OK
```
 raop_rtp_mirror accepting client

Received unencrypted codec packet from client: payload_size 39 header 01 00 16 01  ts_client = 109163.918393
raop_rtp_mirror: unidentified extra header data  0.000000, 0.000000
begin video stream wxh = 1920x1080; source 1920x1080
raop_rtp_mirror width_source = 1920.000000 height_source = 1080.000000 width = 1920.000000 height = 1080.000000
raop_rtp_mirror: SPS+PPS header size = 6
raop_rtp_mirror h264 SPS+PPS header:
01 64 00 2a ff e1 
```

@ionull 

add some code at line 364 of lib/raop_rtp_mirror.c  (just  above "switch (*packet[4])
```
            {
	      char *str = utils_data_to_string(packet,128, 16);
	      printf("received video packet with header:\n%s\n",str);
	      free (str);
	    }
```	    
this will print the 128-byte header of each video packet received

**Comment by ionull** [comment]
[uxplay-log-video-packet-header.txt](https://github.com/FDH2/UxPlay/files/13163336/uxplay-log-video-packet-header.txt)

**Comment by fduncanh** [comment]
OK  your first video packet header says it is unexcrypted  but had no data attached to it.
Normall this should carry so data called SPS and PPS    that tell the h264 about the video format.

The second packet is initial video data ( a "  type 5 IDR VCL NAL unit")

the subsequent packets are "type 1(?) IDR VCL NAL units, possibly type 2)

mystery!

**Comment by fduncanh** [comment]
```
Received unencrypted codec packet from client: payload_size 0 header 01 00 16 01  ts_client = 110640.739497
raop_rtp_mirror, discard type 0x01 packet with no payload

```
In the packet below, it should not issue the PPS NAL_SIZE = ... message.
I'll check the uxplay code to see how that happens

```
received video packet with header:
02 ab 04 00 00 10 00 00 49 b5 4f bd 30 b0 01 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

raop_rtp video: now = 1698222658.928188, ntp = 1698222658.923944, latency = 0.004245, ts = 110640.739497, 00 10 00 00 
raop_rtp_mirror PPS NAL size = 305918
raop_rtp_mirror h264 Picture Parameter Set :
```

**Comment by fduncanh** [comment]
I think that the beginning of the data  in the second video packet below ( 28 01 af 13 ..) is the PPS prepended to the "type 5 IDR VCL NAL unit".

question: what is your m1 macbook pro sending data this way, while our m2 mackbook pro doesnt do this ???

```
raop_rtp video: now = 1698222658.928188, ntp = 1698222658.923944, latency = 0.004245, ts = 110640.739497, 00 10 00 00 
raop_rtp_mirror PPS NAL size = 305918
raop_rtp_mirror h264 Picture Parameter Set :
28 01 af 13 60 88 78 a0 50 4b 40 eb c1 bf 09 3a 
1c 92 34 10 ee 4a 88 25 ba eb ef 98 3c b2 6b 6e 
bd 0d 02 0b ac 8f d8 b4 ee 38 94 4e 25 9c 43 ee 
8c f9 22 02 59 54 2e 28 0c 4f bc 1d 55 37 3a 6d 
58 f1 a1 da 28 1c 10 10 00 ac fc e8 93 65 00 d2 
03 07 34 9f 84 78 5b 70 06 c2 de 3e 99 73 5f 70 
33 6e b0 24 43 ed 89 15 f1 2b 0c 13 14 c4 9f 35 
f4 c6 85 ef cb 71 d1 7a 87 3f 40 cf f7 6a 95 84 
e3 ea ab a9 1a 7e a9 5f 4d c4 95 b4 f3 46 93 96 
73 38 a8 95 79 80 47 31 62 af a5 8a fe b1 72 7b 
83 9d 1f 8c fd 2f d0 c2 b0 95 a7 fb fb 69 33 c5 
```

**Comment by ionull** [comment]
I think maybe because I like both device by a cable? With Dhcp server on
Linux side.

**Comment by fduncanh** [comment]
I dont think it is about cable etc.

The message about PPS NAL size could come from two places.
can you modify line 480 of raop_rtp_mirror.c , and run with debug again so I can tell which place it came from:
``
                      logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG, "raop_rtp_mirror PPS NAL size = %d", nc_len);		
```
change this to
``
                     logger_log(raop_rtp_mirror->logger, LOGGER_DEBUG, "type 8: raop_rtp_mirror PPS NAL size = %d", nc_len);		
```

**Comment by fduncanh** [comment]
@ionull 

do this:
at line 446, just before "switch (nalu_type)", add
```
   printf("*** nalu_type = %d, nalus_count = %d nc_len = %d\n", nalu_type, nalus_count, nc_len);
```

**Comment by ionull** [comment]
Hi, it's weird. After I change the code and add the line. I can airplay 2560 now...

**Comment by fduncanh** [comment]
I will make a special version of uxplay for you in the "testing" branch (not yet created) of uxplay, to give the info I need to debug your issue.   I'm guessing that PPS and SPS info is being added in front of the second video packet, not sent unencrypted with the first packet, so I need to look at it in detail.

I'll let you know here when its ready.

**Comment by ionull** [comment]
[uxplay-log-nalu-type.txt](https://github.com/FDH2/UxPlay/files/13164526/uxplay-log-nalu-type.txt)

**Comment by ionull** [comment]
Now, I almost know how the issue happen. When I plugin cable between two devices, the connection speed is high enough to make macOS airplay higher resolution than through WiFi.

**Comment by ionull** [comment]
Without cable (ethernet line), I can airplay 2560 by wifi, but it's super laggy.

**Comment by ionull** [comment]
The original display of iMac 2014 is 5120x2880 which requires high speed cable(either thunderbolt or ethernet) But I can't get thunderbolt work on Linux. I am using ethernet cable.

**Comment by fduncanh** [comment]
Still, something is perhaps not right with processing the PPS NAL unit.

I will make a special testing version, but maybe not right now

**Comment by ionull** [comment]
Thanks for you hard work, I will wait your update.

**Comment by ionull** [comment]
You can do it like me, connect ethernet to both devices. If you have a dock, just ethernet cable is ok (on both side). If you have no dock, you can find some thunderbolt to ethernet adapter. After connect both devices, you can setup a dhcp on Linux side( make sure the ip showed can ping both sides).

**Comment by fduncanh** [comment]
@ionull can you run uxplay fron the testing branch (without the -d option) and post some results
(showing your original error)

That way I can see what exactly the mac client is sending


https://github.com/FDH2/UxPlay/tree/testing

if you use git,
```
git clone http://github.com/FDH2/UxPlay
cd UxPlay
git checkout testing
makedir build
cd build
cmake ..
make
./uxplay -s 2560x1440
```

**Comment by ionull** [comment]
[log-testing.txt](https://github.com/FDH2/UxPlay/files/13172888/log-testing.txt)

**Comment by fduncanh** [comment]
Thanks!

But I dont understand what kind of video your macOS client is sending...
(The M2 2023 macbook pro running Sonoma 14.0  used for testing sends regular video that UxPlay expects)

I wonder if your mac is sending video in  the newer h265 video format instead of h264?

The decryption is  working correctly.

After the initial unencrypted packey with  a length-0 payload, there is an initial large video payload beginning "28 01 af 56 ......"
that is being interpreted as a h264 format  "type 8" NAL unit (because of the second entry "8")   After that, the video payloads all start as
```
02 01 d0 01 ...
02 01 d0 02 ...
02 01 d0 03 ...
etc
```
and are being interpreted as type 2 h264 nal units

in addition the initial large  "type 8" nal occasionally gets the size  "2560x1440"
output while it is printing, probably by  some other thread in uxplay which I could not identify (???)
```
...
b6 f5 b5 15 16 cd 34 a3 06 11 a5 86 9b ee be 1d 
85 ac 9b fe 03 76 a2 6c 4d fe d3 9c 72 66 2d 70 
3d 68 33 81 63 4b 7b 76 9f f0 07 1f fc 37 82 f7 2560x1440
f0 21 a4 43 d7 49 b4 7c 07 7a 35 cb e4 61 94 a4 
4f 72 a6 d8 98 a4 35 1c 51 90 c9 f4 52 95 6c 0f 
db 94 d6 45 b6 a7 b3 3e 39 b2 9a 95 a9 0d d3 12 
5f 81 89 a7 d4 c0 b3 83 16 73 65 c2 c2 2d 05 7c 
...
````

**Comment by fduncanh** [comment]
H265 info for reference

https://programmer.help/blogs/5c647da7dc2d1.html

**Comment by fduncanh** [comment]
H265 info for reference

https://programmer.help/blogs/5c647da7dc2d1.html



If this is H265  (high-def) video, the initial bytes 28 01 (first packet) is consistent with a "type 20" H265 NAL =  "NAL_UNIT_CODED_SLICE_IDR_LP"

and the subsequent numbered packets with initial bytes 02 01 would be "type 1" H265 NAL = "NAL_UNIT_CODED_SLICE_TRAIL_R"

This make sense, the initial VCL (video image) NAL in h264 is "type 5" "IDR slice-layer without partitioning", and the subsequent ones are are "type 1" ("non-IDR, slice layer without partitioning")

* In principle, supporting h265 would just require identifying it as different from the expected h264 video, and adding a GStreamer video renderer for h265 video.    But right now that's not going to happen.  Instead  uxplay should identify that it is receiving h265 instead of h264 video, and issue a meaningful error message.

Since a M2 2023 macbook seems to streame h264 video by default, maybe your M1 macbook  has some setting set to "high-definition video" (which is a codeword for h265) that can be switched off.

**Comment by ionull** [comment]
M1 Pro stream h264 when there is no cable connected as well ;)

**Comment by fduncanh** [comment]
It's possible that there is a "features" setting (a 64 bit bit string) that uxplay sends to the client that could tell it only to send h264 video? I'll try to look into that

**Comment by fduncanh** [comment]
@ionull 
I just added detection of h265 packets, with an error message that keeps repeating until the user closes the connection.
(I didn't work out how to just close the connection gracefully, so a new connection could be made)

At some time in the future, h265 support might be easy to add, but not now.

Perhaps you could test to see that the h265 you send is detected  with an error message.

It's in the latest github master branch.

Thanks for your input
sorry we haven't fixed your issue

**Comment by ionull** [comment]
Ok, thanks anyway for trying hard.

**Comment by ionull** [comment]
1. I have a dock with ethernet port, connect MBP to the dock by thunderbolt.
2. Connect dock and Ubuntu with ethernet cable.
3. Install isc-dhcp-server on Ubuntu and write conf set subnet 10.5.5.0
4. Set ethernet id to 10.5.5.1 : sudo ifconfig enp4s0f0 10.5.5.1
5. Start or restart the dhcp server: sudo systemctl restart isc-dhcp-server
6. Check the dhcp server status: sudo systemctl status isc-dhcp-server
7. Ping from MBP: ping 10.5.5.1 to make sure the network work
8. Start uxplay

**Comment by fduncanh** [comment]
thanks

**Comment by ionull** [comment]
@fduncanh instead of setup dhcp server. You can easily share network on Ubuntu: https://askubuntu.com/a/553374/1737826

**Comment by fduncanh** [comment]
The underlaying problem is that the Apple client is not including the 3 unencrypted h265 NAL units (VPS, SPS, PPS) needed to decode the h265/hevc video stream with the initial video packet.

Maybe this is because UxPlay is not using full encryption of communications?
