### ISSUE TITLE
no video

### ISSUE THREAD

**Issue by jiang-yuntao** [FDH2/UxPlay#232]
there is no vedio after start up uxplay successly!

**Comment by jiang-yuntao** [comment]
only hava audio ,no vedio

**Comment by Q1CHENL** [comment]
I have the same issue! I use Fedora 38 and tried installing from rpm and building locally but neither worked.

**Comment by Q1CHENL** [comment]
After a little bit debugging I found that the uint64_t type at line 552 was always set to 96 (Audio), hence no Mirroring happened. But since I am not familiar with plist so I couldn't go further.

**Comment by thiccaxe** [comment]
How are you starting the connection? You need to use the two rectangles icon to start "Screen Mirroring"

**Comment by Q1CHENL** [comment]
> How are you starting the connection? You need to use the two rectangles icon to start "Screen Mirroring"

what rectangle icons? i just start mirroring from the control center on iPhone, am I doing it wrongly?

**Comment by thiccaxe** [comment]
![image](https://github.com/FDH2/UxPlay/assets/51303986/48f65390-0ab3-4892-8ec1-700cf5191e04)

**Comment by Q1CHENL** [comment]
> ![image](https://user-images.githubusercontent.com/51303986/278836581-48f65390-0ab3-4892-8ec1-700cf5191e04.jpeg)

Thank you, legend! I thought it was in the same place where the audio/music plays. I have not been using AirPlay for so long that I need to remember how to connect correctly. 

I sense @jiang-yuntao is having the same problem

**Comment by fduncanh** [comment]
seems to be fixed
