### ISSUE TITLE
Cannot connect from Apple Music / Podcast from MacOS

### ISSUE THREAD

**Issue by pchaussalet** [FDH2/UxPlay#239]
Context:
RPi 3b / Armbian Jammy
UXPlay 1.66 built from sources
Clients: Apple Music / Podcast MacOS 13.6

UXPlay shows as an Apple TV in both Apple Music and Apple Podcast, but it fails to connect to it.

When using UXPlay as the system sound output, connection works and sound comes correctly from UXPlay.

**Comment by fduncanh** [comment]
> UXPlay shows as an Apple TV in both Apple Music and Apple Podcast, but it fails to connect to it.

Check the "Troubleshooting" section of the README, and give a more precise description of "fails to connect"

https://github.com/FDH2/UxPlay#troubleshooting

**Comment by fduncanh** [comment]
@pchaussalet 
If you have found the solution to your issue, please close it, otherwise provide more details.

**Comment by fduncanh** [comment]
closing, as no further information provided
