### ISSUE TITLE
gst_video_frame_map_id: assertion 'info->height <= meta->height' failed

### ISSUE THREAD

**Issue by Uckermark** [FDH2/UxPlay#241]
Hey, I just compiled UxPlay and tried to connect to it using my iPad. when i hit UxPlay in controlcenter a blank window popped up on my pc and this error is printed in a loop:

gst_video_frame_map_id: assertion 'info->height <= meta->height' failed

Please let me know if you need any additional information.

Host:
Ubuntu 23.10 mantic
UxPlay built from source

Client:
iPad 5th Gen, 16.6b1

**Comment by fduncanh** [comment]
This is a gstreamer  (gst) issue
You say you are running on  a pc (not Raspberry pi etc).

Look for guidance in the README: try different -vs <videosink> options   (maybe you need -vs waylandsink ?)

https://github.com/FDH2/UxPlay#3-problems-after-the-client-server-connection-has-been-made

https://github.com/FDH2/UxPlay#4-gstreamer-issues-missing-plugins-etc

**Comment by Uckermark** [comment]
Thanks for the fast response. In fact gtksink works, but the performance is really poor compared to the other options (which previously worked on a similar setup). 

I'll have a look at gstreamer. Maybe my gstreamer configuration is just messed up.

I'll close this as it's likely unrelated to uxplay
