### ISSUE TITLE
RPi 4B and iPhone Mirroring fails with no error given in logs

### ISSUE THREAD

**Issue by Babyyoda777** [FDH2/UxPlay#259]
babyyoda777@raspberrypi:~ $ uxplay -d
UxPlay 1.62: An Open-Source AirPlay mirroring and audio-streaming server.
Audio format 1: AAC-ELD 44100/2
GStreamer audio pipeline 1: "appsrc name=audio_source ! queue ! avdec_aac ! audioconvert ! audioresample ! volume name=volume ! level ! autoaudiosink sync=false"
Audio format 2: ALAC 44100/16/2
GStreamer audio pipeline 2: "appsrc name=audio_source ! queue ! avdec_alac ! audioconvert ! audioresample ! volume name=volume ! level ! autoaudiosink sync=false"
GStreamer video pipeline will be:
"appsrc name=video_source ! queue ! h264parse ! decodebin ! videoconvert ! autovideosink name=video_sink sync=false"
Initialized GStreamer video renderer
using system MAC address e4:5f:01:cb:73:fb
Initialized server socket(s)
^CStopping...
Exiting HTTP thread

The logs appear to be normal how ever when pressing mirror on my phone the loading bar appears and eventually times out saying couldn't connect.

**Comment by fduncanh** [comment]
Have you looked at the "troubleshooting"part of the README?
https://github.com/FDH2/UxPlay#troubleshooting

**Comment by fduncanh** [comment]
if issue is fixed please close issue

**Comment by fduncanh** [comment]
seem like issue is stale:

feel free to reopen if needed.
