### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by friendlypandabytes** [FDH2/UxPlay#26]
I have installed UxPlay on a debian machine. The machine can be seen through airplay on iOS devices in the same network. However, when trying to screen mirror through it, it shows a "Segmentation fault" error, I ran UxPlay in debug mode, it shows the following:

`Initialized server socket(s)
Accepted IPv4 client on socket 24
Local: 192.168.1.224
Remote: 192.168.1.121
Open connections: 1
httpd receiving on socket 24
conn_request
Handling request GET with URL /info
INFO len = 1946151172
httpd receiving on socket 24
conn_request
Handling request POST with URL /pair-setup
httpd receiving on socket 24
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 24
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 24
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 24
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 24
conn_request
Handling request SETUP with URL rtsp://192.168.1.224/14647767658038641318
DACP-ID: [REDACTED]
Active-Remote: [REDACTED]
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 54999
raop_ntp parse remote ip = 192.168.1.121
raop_ntp starting time
raop_ntp local timing port socket 26 port UDP 44549
raop_rtp parse remote ip = 192.168.1.121
raop_rtp_mirror parse remote ip = 192.168.1.121
eport = 42053, tport = 44549
raop_ntp send_len = 32
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -1634874414113411
Accepted IPv4 client on socket 27
Local: 192.168.1.224
Remote: 192.168.1.121
Open connections: 2
httpd receiving on socket 24
conn_request
Handling request GET with URL /info
INFO len = 1946151172
httpd receiving on socket 24
conn_request
Handling request GET_PARAMETER with URL rtsp://192.168.1.224/14647767658038641318
httpd receiving on socket 24
conn_request
Handling request RECORD with URL rtsp://192.168.1.224/14647767658038641318
raop_handler_record
httpd receiving on socket 24
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.224/14647767658038641318
httpd receiving on socket 24
conn_request
Handling request SETUP with URL rtsp://192.168.1.224/14647767658038641318
DACP-ID: [REDACTED]
Active-Remote: [REDACTED]
Transport: null
type = 110
streamConnectionID = [REDACTED]
raop_rtp_mirror starting mirroring
raop_rtp_mirror local data port socket 28 port TCP 38269
Mirroring initialized successfully
raop_rtp_mirror accepting client
raop_rtp_mirror width_source = 608.000000 height_source = 1080.000000 width = 608.000000 height = 1080.000000
raop_rtp_mirror sps size = 17
raop_rtp_mirror pps size = 4
raop_rtp_mirror video ntp = 1635023384196461, now = 1635023384141874, latency = -54587
raop_rtp_mirror video ntp = 1635023384246464, now = 1635023384149825, latency = -96639
raop_rtp_mirror video ntp = 1635023384263132, now = 1635023384161874, latency = -101258
raop_rtp_mirror video ntp = 1635023384296467, now = 1635023384199622, latency = -96845
raop_rtp_mirror video ntp = 1635023384329802, now = 1635023384229266, latency = -100536
raop_rtp_mirror video ntp = 1635023384363138, now = 1635023384271609, latency = -91529
raop_rtp_mirror video ntp = 1635023384396473, now = 1635023384300202, latency = -96271
raop_rtp_mirror video ntp = 1635023384429809, now = 1635023384337842, latency = -91967
raop_rtp_mirror video ntp = 1635023384463144, now = 1635023384371670, latency = -91474
raop_rtp_mirror video ntp = 1635023384496480, now = 1635023384403856, latency = -92624
Segmentation fault`

**Comment by fduncanh** [comment]
To see if it's anything in recent changes to uxplay, see if https://github.com/antimof/UxPlay and https://github.com/FD-/RPiPlay show the same problem.    These require any firewall to be turned off and have less
options than current UxPlay, which is derived from them,


current UxPlay  works fine on a standard Ubuntu 20.04 system, should work on Debian.

**Comment by friendlypandabytes** [comment]
After further research, it seems the issue seems to be with my linux drivers for integrated graphics not uxplay, sorry for the trouble

**Comment by schnulller** [comment]
This seems to be a problem with the Intel display driver. For some people it might help to know that installing the non-free version of the driver on Debian

`sudo  apt install intel-media-va-driver-non-free`

helped me resolve the issue for now.

**Comment by fduncanh** [comment]
@schnulller 
thanks for this tip., I'll add it to the troubleshooting part of the README.
