### ISSUE TITLE
Airplay 2 multi room audio?

### ISSUE THREAD

**Issue by stretch4x4** [FDH2/UxPlay#260]
I can't seem to find a definitive answer anywhere, is it possibly to stream using airplay 2, to multiple UxPlay instances or a mix of UxPlay and other airplay devices?

I currently have two other devices I can simultaneously send music to, and looking to use some old devices and speakers to add a few more options to cover my house. However my test run of UxPlay only seems to allow it to be a destination on it's own.

Not sure if there is a config option I am missing, currently just running the defaults on v1.46-1 as that was the package that was available for Ubuntu Jammy, which I have on my current test machine.

Thanks

**Comment by fduncanh** [comment]
No, for multiroom audio AirPlay2 , use [shairport-sync](https://github.com/mikebrady/shairport-sync)

**Comment by stretch4x4** [comment]
Thanks, maybe something worth mentioning in the readme?

**Comment by fduncanh** [comment]
It's really a different use of AirPlay,  UxPlay is for video  (screen mirroring to a single destination), with audio-only mode added back as an extra, because Apple originally (AirPlay 1) added screen mirroring to iTunes, and evolved it from there.    UxPlay evolved from an open source iTunes implementation ShairPlay    which was  completely independent of shairport, the ancestor  of shairport-sync, with no common code.

**Comment by stretch4x4** [comment]
That is fair, as someone new to the airplay space I found both projects, however UxPlay seemed like it would be easier to get running. I did gather that ShairPlay didn't do video and UxPlay did but as both supported AirPlay 2 I assumed that meant multi room audio for both.
I guess if I am the first person to ask about it, maybe it isn't a major issues as most people figure it out one way or another.

**Comment by fduncanh** [comment]
The Airplay 2 support is partial in both projects, different parts!

Interesting question: does genuine Apple Airplay2 do multiroom video?

**Comment by stretch4x4** [comment]
Which I am starting to understand :) Not sure the best way to do it but might be room for a note around that somewhere to help strange people like me.

Just did a quick test with a youtube video, can airplay to my TV but if I add my homepod mini, the TV drops to audio only and stops showing the video (but does play audio to both devices) I don't have a second airplay TV so not sure if streaming to two TVs would drop to audio as well or maintain the video feed..

Hope that helps a little.
