### ISSUE TITLE
Connection works with iPhone, but not with Macbook (M2 Max, macOS 14)

### ISSUE THREAD

**Issue by wenerme** [FDH2/UxPlay#264]
Soory to open this, I found this https://github.com/FDH2/UxPlay/issues/73 , but already using uxplay build from master source, I don't know where to look at.

[gst.log](https://github.com/FDH2/UxPlay/files/13896705/gst.log)
[uxplay.log](https://github.com/FDH2/UxPlay/files/13896710/uxplay.log)

started by

```bash
uxplay -n "tv@rad-office" -nh -fps 18 -fs -vs ximagesink
```

**Comment by fduncanh** [comment]
maybe the -fps18 is the issue?
try without this option.

**Comment by wenerme** [comment]
Thanks, Yes，`-fps18` is the problem, 😭 . Should I close this or wait to solve this ?

**Comment by fduncanh** [comment]
-fps 18 tells the client that the server will not accept video at a rate greater than 18fps.

It seems that your macOS M2 client system refuses to send any video at that slow rate.   The default is 30fps.

**Comment by wenerme** [comment]
@fduncanh Thanks, I use alpine on amd64 as host. UxPlay feels lag so I want to try lower fps, uxplay works like stop a will then works again.


https://github.com/FDH2/UxPlay/assets/1777211/86e3b1c5-8478-48b3-b198-ae745e87b769

**Comment by fduncanh** [comment]
uxplay should work without lags on amd64.   


Is alpine linux "friendly" in a multi-boot (multi-linux)  setup   (i.e. won't destroy other linux installations)?

**Comment by wenerme** [comment]
> uxplay should work without lags on amd64.
> 
> Is alpine linux "friendly" in a multi-boot (multi-linux) setup (i.e. won't destroy other linux installations - this is a grub2 issue)? Is a virtualbox installation OK for testing your issues?
> 
> How much memory does your amd-64 system have. how old is it (describe it more)
> 
> there appear to be various modes
> 
> 1. diskless mode
> 2. data disk mode
> 3. system disk mode
> 
> which one is giving you problems?

Thanks.

I use sys mode, no multi-boot (all my server are alpine), here is the neofetch output

```
OS: Alpine Linux v3.19 x86_64
Kernel: 6.6.9-0-lts
Uptime: 1 day, 23 hours, 28 mins
Packages: 125 (apk)
Shell: bash 5.2.21
Terminal: /dev/pts/0
CPU: Intel Pentium 4405U (4) @ 2.100GHz
Memory: 102MiB / 15923MiB
```

**Comment by fduncanh** [comment]
we installed an alpine linux 3.19  test installation (sys mode on x86_64), with kde.

running "uxplay -vs xvimagesink" triggers something (in gstreamer?) that causes PAM to immediately shutdown sddm, and terminate the user session.
"uxplay" by itself also does this, probably because xvimagesink is the default choice made by "autovideosink".

-vs ximagesink and -vs glimagesink work.

Another alpine SDDM weirdness (which apparently a KDE known bug in a prerelease version of SDDM, also reported in Arch Linux) is that the regular "enter" key is not recognized on the login screen, only the numeric keypad "enter" is.

**Comment by isthereamrsboop** [comment]
sorry to revive this; on an M3 MacBook encountering a similar issue to this + the other referenced issue. happy to help troubleshoot; here's the fun wrinkle, I'm running bazzite (so based on atomic fedora / silverblue)

it works flawlessly for everything else, but yeah; desktop airplay stuff from the MacBook does two things:

- resolution temporarily changes on the MacBook, then leaves me with a 'sticky' stream source selection window that I can't get rid of without rebooting on the mac
- I get a blank, black X11 window on the bazzite desktop (nvidia/intel cpu setup fwiw, can get specifics later if needed)

happy to run similar troubleshooting steps if it'll help resolve this. OS is the latest Tahoe, but I know we're a month away from an update so I'm not sure how long any changes / details we learn here will stick. 


I've turned notifications on for this thread, so I will respond as soon as I can!

**Comment by isthereamrsboop** [comment]
Another interesting note: if I airplay (extend) I get the *top bar* (the one with the mac logo, files, etc) but no background, app, or anything else visible! but it does show the menu bar briefly and sometimes I get a cursor freeze-frame. so it seems to be partially working but something else isn't coming through
