### ISSUE TITLE
cmake install manpage into deprecated directory

### ISSUE THREAD

**Issue by PetrusZ** [FDH2/UxPlay#27]
According [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrsharemanManualPages) and [cmake install doc](https://cmake.org/cmake/help/latest/command/install.html#installing-files), I think the correct way to install man page should be:

```
install( FILES uxplay.1 DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 )
```

instead of

```
install( FILES uxplay.1 DESTINATION man/man1 )
```

Current it installed into `/usr/man/man1`, in my system which is Gentoo Linux, I can't use man to read manpage from there.

**Comment by fduncanh** [comment]
thanks!
I have updated CMakeLists.txt

**Comment by fduncanh** [comment]
@PetrusZ 
If you clone the latest UxPlay from git, you could test to see if it installs the manpage correctly.

Thanks

**Comment by PetrusZ** [comment]
I tested from git repo, it install to `/usr/share/man/man1/`. The `man` command can read uxplay manpage now.
