### ISSUE TITLE
RPI UXPLAY Buildroot

### ISSUE THREAD

**Issue by hkfuertes** [FDH2/UxPlay#270]
Hello, quick question. Can UXPlay run on a non X11/WAYLAND (lite image) raspberrypi image? I was thinking on create a "dongle" with a pi02w using buildroot, but before even starting I ask if you guys know if it feasable.

Thank you! And also thank you for this awesome project!

**Comment by fduncanh** [comment]
yes pi20w runs well on lite with no X11/wayland

use -vs kmssink for the frame buffer. see the README
https://github.com/FDH2/UxPlay?tab=readme-ov-file#special-instructions-for-raspberry-pi-tested-on-raspberry-pi--zero-2-w-3-model-b-4-model-b-and--5-only
