### ISSUE TITLE
Redirection doesn't work on Raspberry Pi 5 (Bookworm)

### ISSUE THREAD

**Issue by MynockSpit** [FDH2/UxPlay#272]
For some reason, redirection of any kind (so far as I can tell) silences logging. 

Example showing that w/o redirection, it prints logs
<img width="537" alt="image" src="https://github.com/FDH2/UxPlay/assets/5713867/afb293f2-a6e5-4f76-b643-b295a51a3978">

Example w/ `tee`
<img width="619" alt="image" src="https://github.com/FDH2/UxPlay/assets/5713867/6b3ab2e7-1923-42b1-b3cd-bcdd7705f27e">

Example with `>`
<img width="620" alt="image" src="https://github.com/FDH2/UxPlay/assets/5713867/9a0be717-6524-400b-9407-ad90266da849">

**Comment by fduncanh** [comment]
what are you trying to do?

(the ";"  after the & is syntax error,  at least in bash)

**Comment by MynockSpit** [comment]
The bit before and including the semi-colon is just to show that five seconds have passed (echo out after five seconds) before I manually killed the program. 

The behavior is the same (no output from uxplay) without that.

**Comment by thiccaxe** [comment]
Can you test with cat or something instead of uxplay?

**Comment by MynockSpit** [comment]
Yup. Works fine with echo.

<img width="415" alt="image" src="https://github.com/FDH2/UxPlay/assets/5713867/9af95426-ee98-454c-b151-fac1834753c2">

<img width="489" alt="image" src="https://github.com/FDH2/UxPlay/assets/5713867/4aedc338-ef8b-4719-a428-89619cfa99a9">

**Comment by MynockSpit** [comment]
Okay, so I guess it's a bit more complicated. Seems like the output isn't written until after the process has been killed. Is that intentional? And if so, is it possible to change that behavior? I'd like to be able to tail the log as it's running to see what uxplay is doing.

<img width="552" alt="image" src="https://github.com/FDH2/UxPlay/assets/5713867/c9de94b6-c999-4dfd-a856-bbf27309559d">

**Comment by fduncanh** [comment]
The "log" is exactly what you see on the terminal.    To see more "uxplay -d"

0.  to just watch but not save:
uxplay -d 

1. To send it to a file
uxplay -d > logfile 2>&1

you wont see the terminal output.

2. to then watch on a different terminal (use ssh  to get one if you are using the Pi 5 in "Lite" mode without X)

tail -f logfile

to save and also watch on the uxplay terminal

3. uxplay -d | tee logfile

yes, its jerky (buffered) in case 2 and  3

Maybe without -d there is so little output that the buffer does not drain before you kill the process.

None of this is uxplay-specific.

**Comment by fduncanh** [comment]
@MynockSpit After the socket is initialized, uxplay is waiting for a client connection.   Nothing will be output until a client tries to connect.   You images dont seem to show any client activity.

**Comment by MynockSpit** [comment]
> yes, its jerky (buffered) in case 2 and 3

Ah, so this is what I'm seeing. I'm unused to output being buffered w/ redirections, or at least buffered such large chunks. Is there any way to control the buffer size? I just tested, and it took three songs before it output anything new.

**Comment by fduncanh** [comment]
@MynockSpit If you think this is a uxplay log issue,  it would be an issue in  lib/logger,c that controls all logging.

Feel free to identify anything you think could be improved, and submit a PR. 

https://github.com/FDH2/UxPlay/blob/master/lib/logger.c
https://github.com/FDH2/UxPlay/blob/master/lib/logger.h

**Comment by MynockSpit** [comment]
Just about to post that I think it's just a buffering config thing. This works: 

https://serverfault.com/questions/294218/is-there-a-way-to-redirect-output-to-a-file-without-buffering-on-unix-linux

Thanks for the insight!
