### ISSUE TITLE
Sound muffles if volume changed

### ISSUE THREAD

**Issue by eliklein02** [FDH2/UxPlay#274]
Hi, I'm using it like this "uxplay -nohold -as pulsesink -db -1:30" (yes I have pulseaudio) and if I play around with the volume on my phone, it becomes much louder and becomes muffled. 
Any ideas?
Thank you

**Comment by fduncanh** [comment]
"-db -1:30"

is this a typo ?     "-db -30:0"  is the default

**Comment by eliklein02** [comment]
No it’s not a typo, I thought the first one is the low and the second is high. :-)
What should I do?
________________________________

**Comment by fduncanh** [comment]
The -db option was introduced after the issue  #250

The default range is -db -30:0    This is amplitude gain decibels.   

I dont know enough about audio to advise what gain you should use, it probably depends on what kind or audio system
you have.    

https://www.hollyland.com/blog/tips/what-is-gain-in-audio


increasing the upper gain limit certainly makes the audio louder, but may introduce distortion ("clipping") ???

just experiment with it.  (or leave it at default)    Try -db -30:20    (a 50db range)   or -db -10:20  (same 30db range as default  but shifted  up by +20db.).

The upper setting should not be greater than +20 , as gstreamer doesn't  accept anything more.  

The volume profile give by option  "-taper" might  also be useful: this modifies  how the volume settings on the client change loudness, but doesn't change the decibel range.    If the range from L to H has H = L +30db,  
each 50% decrease in the "tapered" volume setting halves the perceived sound volume.
