### ISSUE TITLE
 *** invalid ntp_time < gst_video_pipeline_base_time #127 

### ISSUE THREAD

**Issue by da-the-dev** [FDH2/UxPlay#279]
This is an issue [repost](https://github.com/antimof/UxPlay/issues/127), since I'm having a similar issue

> I'm getting this error on loop when using UxPlay on ArchLinux with Wayland and Pipewire.
> It worked fine before switching to Pipewire
> 
> ```UxPlay 1.63: An Open-Source AirPlay mirroring and audio-streaming server. using system MAC address [...] Initialized server socket(s) Accepted IPv4 client on socket 25 Local: 192.168.1.50 Remote: 192.168.1.55 Client identified as User-Agent: AirPlay/675.4.1 Accepted IPv4 client on socket 27 Local: 192.168.1.50 Remote: 192.168.1.55 raop_rtp_mirror starting mirroring *** invalid ntp_time < gst_video_pipeline_base_time 11726.563526 ntp_time 1677493717.934162 base_time *** invalid ntp_time < gst_video_pipeline_base_time 11726.605209 ntp_time 1677493717.934162 base_time *** invalid ntp_time < gst_video_pipeline_base_time 11726.638555 ntp_time 1677493717.934162 base_time *** invalid ntp_time < gst_video_pipeline_base_time 11726.671902 ntp_time 1677493717.934162 base_time *** invalid ntp_time < gst_video_pipeline_base_time 11726.705248 ntp_time 1677493717.934162 base_time```
> 
> System info:
> OS: Arch Linux x86_64
> Kernel: 6.1.12-arch1-1
> DE: Hyprland
> WM: sway
> SoundServer: PipeWire 0.3.66

**Comment by fduncanh** [comment]
this is in the audio renderer when it received the audio with a timestamp.

The gst_video_pipeline_base_time 11726.563526 is clearly wrong

are you using uxplay-1.68?   you didnt post your own error messages.

**Comment by fduncanh** [comment]
can you post your own error messages.   thanks. (this code has changed )

**Comment by da-the-dev** [comment]
After a system upgrade GStreamer window stopped showing up for me after the AirPlay stream would start. I was looking online to find a solution and I found that old GitHub issue. I thought that the OP of the issue was experiencing something similar to what I had, so I decided to repost.

If I run `uxplay -async no -vsync no`
I get
```
UxPlay 1.68: An Open-Source AirPlay mirroring and audio-streaming server.
using system MAC address 5c:e4:2a:10:21:1a
Initialized server socket(s)
Accepted IPv4 client on socket 24
Local: 192.168.1.102
Remote: 192.168.1.31
connection request from Smart iPad 2077 (iPad7,11) with deviceID = 28:77:F1:82:31:39

Client identified as User-Agent: AirPlay/755.3.1
Accepted IPv4 client on socket 26
Local: 192.168.1.102
Remote: 192.168.1.31
raop_rtp_mirror starting mirroring
Begin streaming to GStreamer video pipeline
```
And then it's stuck like that. GStreamer window does not show up, the console just freezes.

If I run `uxplay`
Everything works properly.

The reason I used to run `uxplay -async no -vsync no` was because the stream would desync after a short while after it was started and error messages similar to those in the reposted issue would show up. So I looked around the options and made audio and video asyncronous (I didn't need it to be in sync at all anyway, I use my iPad as a whiteboard). 

I guess the crutch I used does not work, but I don't need it anymore? Hooray? xD 
And I guess I had a completely different issue, so the repost was not necessary.

**Comment by fduncanh** [comment]
Are you on Arch like the old post?

I booted into our Arch test installation to check.

Unfortunately I didn't test uxplay before upgrading.  After upgrading gstreamer was at new major release 1.24.1,
and uxplay video was not working any more.   I checked on Arch derivative Manjaro which is still on v 1.22.10 and all worked.   So there is some issue after the upgrade to gstreamer-1.24.x that needs fixing.

**Comment by fduncanh** [comment]
The  "correct" way to use uxplay  when  the client ipad is a whitebord is  "-vsync no", (-async no is the default anyway, though this may change in the future).

* On checking again, I did find an issue with "-vsync no" on Arch with gstreamer 1.24 but not on a different linux with v 1.22.x:

* when started with -vsync no, things worked, but if the client stopped streaming and then restarted, the mirror window did not reopen.   I'll check into this ASAP, but not immediately.
