### ISSUE TITLE
Flatpak Package

### ISSUE THREAD

**Issue by zefr0x** [FDH2/UxPlay#285]
I made an initial Flatpak manifest here: https://github.com/zefr0x/flathub/tree/uxplay

It builds, but still broken (not completed):

```
Required gstreamer libav plugin feature 'avdec_aac' not found:

This may be missing because the FFmpeg package used by GStreamer-1.x-libav is incomplete.
(Some distributions provide an incomplete FFmpeg due to License or Patent issues:
in such cases a complete version for that distribution is usually made available elsewhere)

if the plugin feature is installed, but not found, your gstreamer registry may have been corrupted.
to rebuild it when gstreamer next starts, clear your gstreamer cache with:
"rm -rf ~/.cache/gstreamer-1.0"
```
```
*** ERROR: No DNS-SD Server found (DNSServiceRegister call returned kDNSServiceErr_Unknown)
```

Also, I don't think it will be approved in FlatHub, since it doesn't has any GUI interface yet. Maybe we could work in a simple GTK+Adwaita interface built with python.

For now people can test it and use it by building it them self. If any one can solve current errors it would be great, since i'm not very motivated for now to work in this, and i don't know enough about the project or any related libraries.

---

Related: https://github.com/antimof/UxPlay/issues/65

**Comment by fduncanh** [comment]
The errors shown are 

(1) an incomplete ffmpeg package is being used by gstreamer-libav:  Redhat, Suse and some others dont ship i because of frauenhofer patents on AAC audio: you have to install a complete "community-provided  package"

https://en.wikipedia.org/wiki/Advanced_Audio_Coding

(2)  uxplay needs a DNS_SD server (e.g. avahi-daemon) to be active on the network.    It was not found.

**Comment by zefr0x** [comment]
> (1) an incomplete ffmpeg package is being used by gstreamer-libav: Redhat, Suse and some others dont ship a complete one because of frauenhofer patents on AAC audio: you have to install a complete "community-provided package" ; ubuntu, debian ship complete ffmpeg.
> 
> https://en.wikipedia.org/wiki/Advanced_Audio_Coding

FFmpeg is not installed at all in the sandbox. I will try to build it with `gstreamer-libav` rather than depending on the runtime for this.


> (2) uxplay needs a DNS_SD server (e.g. avahi-daemon) to be active on the network. It was not found.

Fixed: https://github.com/zefr0x/flathub/commit/d9827118273a5e9717f5d2aa5cfab3d0fa1407b0

**Comment by fduncanh** [comment]
Re: a gui.

Uxplay does not accept any input from the terminal except when it starts, and all input options can be read from a startup file ~/.uxplayrc (which can be relocated to env variable  $UXPLAYRC) .  It does output info to the terminal, and relies on
ctrl-C from the terminal to stop the server.      

A very simple gui (using a cross platform toolkit such as gtk or QT) would just offer these services with an option to show a terminal-like window with the terminal output.    https://en.wikipedia.org/wiki/Advanced_Audio_Coding

An option to display jpeg/png "cover art" in audio mode could be added; right now an option outputs this to a file which an external image viewer can access.

**Comment by fduncanh** [comment]
Keeps  us informed on progress!

Closing for now.
