### ISSUE TITLE
Can't build on Ubuntu 24.04

### ISSUE THREAD

**Issue by MANICX100** [FDH2/UxPlay#286]
says openssl not found v3 installed

**Comment by fduncanh** [comment]
please give more details

**Comment by MANICX100** [comment]
The issue is that Ubuntu 24.04 which to be fair isn't out yet (ETA: 25/04) comes with libssl3t64 3.2.1-3 but the libssl-dev package required for building needs v3.0.13-0ubuntu3.

I can fix this by downgrading and holding the package e.g.

`sudo apt install libssl3t64=3.0.13-0ubuntu3`
`sudo apt-mark hold libssl3t64`

I will close for now, unless there is a dependency issue or thing that could be upgraded from the projects perspective (feel free to reopen and merge any changes.

**Comment by fduncanh** [comment]
ubuntu-24.04 should supply uxplay-1.68.2   which is essentially up to date.
1.68.3 just has a fix needed for gstreamer-1.24.x which is bleeding edge (just used by Arch Linux so far)
