### ISSUE TITLE
compiled cli entries for videoflip

### ISSUE THREAD

**Issue by steveredden** [FDH2/UxPlay#287]
This was super helpful - thank you:

[../wiki/patch-for-broken--videoflip-method-in-GStreamer-1.22.0](../wiki/patch-for-broken--videoflip-method-in-GStreamer-1.22.0)

Here are the compiled commands I entered, if you wanted to add them to the wiki (I couldn't figure out how to PR on the wiki specifically 🤔 )

1. mkdir ~/gstream-patch
1. cd ~/gstream-patch
1. wget https://github.com/FDH2/UxPlay/files/14551547/gst_videoflip_1_22_0_diff.txt
1. sudo nano /etc/apt/sources.list
1. \>\> uncomment out the deb-src entries; save; exit <<
1. sudo apt update
1. sudo apt install devscripts -y
1. sudo apt build-dep gstreamer1.0-plugins-good -y
1. apt source gstreamer1.0-plugins-good
1. cd gst-plugins-good1.0-1.22.0
1. debuild
1. patch -p1 < ../gst_videoflip_1_22_0_diff.txt
1. cd obj*
1. ninja
1. cd gst/videofilter
1. strip libgstvideofilter.so
1. sudo cp libgstvideofilter.so /usr/lib/aarch64-linux-gnu/gstreamer-1.0/
1. sudo reboot

**Comment by fduncanh** [comment]
Thank you.  I added your recipe to the wiki
https://github.com/FDH2/UxPlay/wiki/patch-for-broken--videoflip-method-in-GStreamer-1.22.0
