### ISSUE TITLE
Mirror Uxplay stream to v4l2 device

### ISSUE THREAD

**Issue by jerryjaimon** [FDH2/UxPlay#289]
I am trying to mirror the uxplay stream on a v4l2 device. 
The end goal is to show this stream on a django server or a browser page. Is there any way to do mirror the stream on a v4l2 device or any other alternative that I can try?

Thanks!

**Comment by fduncanh** [comment]
uxplay decrypts  (raop code in lib) two separate streams (audio and video, each with timestamps) from the client   and sends them to gstreamer (code in renderers)  using callbacks  audio_process and video_process in uxplay.cpp.  These inject the streams into gstreamer.    The video gstreamer pipeline is fully user configurable. with options such as -vs <videosink>.     If you can work out a gstreamer pipeline you can probably modify uxplay to do what you want, by just modifying things in directory "renderers".    To send the stream on to somewhere else  by RTSP you would need to merge to audio and video streams.   Gstreamer has all sorts of possibilities for that kind of thing.
  
The only connection between decryption code in UxPlay/lib and rendering code in Uxplay/renderers is via the callbacks in uxplay.cpp

**Comment by fduncanh** [comment]
Closing because this isn't something planned.  But if you find out how to do this please let us know.

**Comment by duckinator** [comment]
I've used UxPlay with OBS Studio for recording video. This combination should also work for streaming.
