### ISSUE TITLE
FreeBSD fixes

### ISSUE THREAD

**Issue by fduncanh** [FDH2/UxPlay#29]
@swills,
http://github.com/FD-/RPiPlay#277
have installed FreeBSD on virtualbox to test.
please leave comments on this "issue"  here.

What fixes did you need to make so far?

**Comment by swills** [comment]
See #30

**Comment by fduncanh** [comment]
Thanks @swills 
Builds and runs now! (FreeBSD13.0 in virtualbox)

**Comment by swills** [comment]
Why did you hard code /usr/local/lib ? It's not guaranteed that's the path, users can change their install path for ports if they wish. There shouldn't be any need to special case it.

Anyway, there's still the issue that it builds and runs but doesn't work. It shows up in the AirPlay list, but doesn't connect.
