### ISSUE TITLE
-r not working with fbdevsink

### ISSUE THREAD

**Issue by Boaztheostrich** [FDH2/UxPlay#292]
I was trying to rotate the video output using this command:

```
uxplay -vs fbdevsink -r L
```
(-r R also didn't work)

But it would not rotate, I am using a Pi CM4 with the following carrier board: https://www.fysetc.com/products/raspberry-pi-cm4-hmi-display-module-small-and-high-resolution-him-dpi-interface-capacitive-touch-screen-module

Using an unpatched version of uxplay with everything up to date.

I've attached some picture below to showcase the issue:

![IMG_4974](https://github.com/FDH2/UxPlay/assets/81034456/ae2d5108-4627-4c61-aaf1-e732fd743630)
![IMG_4976](https://github.com/FDH2/UxPlay/assets/81034456/1612b07e-7bed-4e6f-8834-65fac5c4a926)

Additionally the image output stays over the terminal, or desktop if you run this command with desktop, until you run the clear command.

Thanks,
Boaz

**Comment by Boaztheostrich** [comment]
It also has an invisible "box" around it, meaning that:
```
uxplay -vs fbdevsink -s 800x480
```
```
uxplay -vs fbdevsink -s 1167x800
```
and
```
uxplay -vs fbdevsink -s 1000x600
```

all have the same output on the screen, shown below:

![IMG_4978](https://github.com/FDH2/UxPlay/assets/81034456/eb78c081-1463-44fc-a9d5-23f0f0e3cc42)



If you go larger though, such as 
```
uxplay -vs fbdevsink -s 1667x1000
```

It does increase the size of the output to where it is bigger than the 800x480 screen, as shown below:

![IMG_4977](https://github.com/FDH2/UxPlay/assets/81034456/14b9d111-6103-40bb-851f-2f0a147923fa)


Thanks

**Comment by fduncanh** [comment]
did you try kmssink?

**Comment by fduncanh** [comment]
tested on R Pi OS lite Bookworm.    

I confirmed that uxplay -vs dfbvideosink works (without -r R), but leaves parts of image on screen when window closes.

*  with the option "-r R"  it fails to work   (cannot build working pipeline)

use -vs kmssink instead.

**Comment by Boaztheostrich** [comment]
This is what I get for kmssink
```
boazburnett@raspberrypi:~ $ uxplay -vs kmssink
UxPlay 1.62: An Open-Source AirPlay mirroring and audio-streaming server.
Failed to initialize GStreamer video renderer
using system MAC address e4:5f:01:fa:db:68
Initialized server socket(s)
GStreamer error: Could not open DRM module (NULL)
Failed to initialize GStreamer video renderer
Initialized server socket(s)
GStreamer error: Could not open DRM module (NULL)
```

**Comment by fduncanh** [comment]
does "gst-inspect-1.0 kmssink" show it is present?

**Comment by Boaztheostrich** [comment]
It does!
```
boazburnett@raspberrypi:~ $ gst-inspect-1.0 kmssink
Factory Details:
  Rank                     secondary (128)
  Long-name                KMS video sink
  Klass                    Sink/Video
  Description              Video sink using the Linux kernel mode setting API
  Author                   Víctor Jáquez <vjaquez@igalia.com>
  Documentation            https://gstreamer.freedesktop.org/documentation/kms/#kmssink-page

Plugin Details:
  Name                     kms
  Description              Video sink using the Linux kernel mode setting API
  Filename                 /usr/local/lib/aarch64-linux-gnu/gstreamer-1.0/libgstkms.so
  Version                  1.22.12
  License                  LGPL
  Source module            gst-plugins-bad
  Documentation            https://gstreamer.freedesktop.org/documentation/kms/
  Source release date      2024-04-29
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseSink
                         +----GstVideoSink
                               +----GstKMSSink

Implemented Interfaces:
  GstVideoOverlay

Pad Templates:
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      video/x-raw
                 format: { (string)BGRA, (string)RGBA, (string)P016_LE, (string)P010_10LE, (string)NV24, (string)BGRx, (string)RGBx, (string)RGB, (string)BGR, (string)Y42B, (string)NV61, (string)NV16, (string)UYVY, (string)YVYU, (string)YUY2, (string)I420, (string)YV12, (string)NV21, (string)NV12, (string)RGB16, (string)BGR16 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  SINK: 'sink'
    Pad Template: 'sink'

Element Properties:

  async               : Go asynchronously to PAUSED
                        flags: readable, writable
                        Boolean. Default: true
  
  blocksize           : Size in bytes to pull per buffer (0 = default)
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4096 
  
  bus-id              : DRM bus ID
                        flags: readable, writable
                        String. Default: null
  
  can-scale           : User can tell kmssink if the driver can support scale
                        flags: readable, writable
                        Boolean. Default: true
  
  connector-id        : DRM connector id
                        flags: readable, writable
                        Integer. Range: -1 - 2147483647 Default: -1 
:
```

**Comment by fduncanh** [comment]
complicated!   not sure what you can do.

**Comment by Boaztheostrich** [comment]
Very complicated haha, and I've been unable to get any real help from the manufacturer. I may have to learn how to make a video driver to replace the existing one. idk

On the bright side this:

```
boazburnett@raspberrypi:~ $ uxplay -vs "videoscale ! video/x-raw,width=480,height=800 ! fbdevsink"
```

Is full screen and works better than any other command I have tried on this display!

The latency is still not what I want it to be but it is getting there. 

Thanks again for all of the help!!

If you have any suggestions for further optimizing the above command it would be appreciated, it looks like there are a lot of gstreamer options I can play with

**Comment by fduncanh** [comment]
If you need the rotation, you should use GST_DEBUG to find out why it does not work.  maybe moving the posotion in the pipeline where the rotation is done might solve it   (see renderers/video_renderer_gstreamer.c)


https://github.com/FDH2/UxPlay/blob/master/renderers/video_renderer_gstreamer.c#L150

closing issue for now

**Comment by fduncanh** [comment]
PS  you should test your gstreamer pipeline directly, without uxplay:


works:
gst-launch-1.0 -v videotestsrc ! videoscale ! fbdevsink

doesnt work : (find out why?)

gst-launch-1.0 -v videotestsrc ! videoscale ! videoflip video-direction=GST_VIDEO_ORIENTATION_90R !  fbdevsink

works: 

gst-launch-1.0 -v videotestsrc ! videoscale ! videoflip video-direction=GST_VIDEO_ORIENTATION_90R !  kmssink

**Comment by fduncanh** [comment]
OK what works is 

```
gst-launch-1.0 -v videotestsrc !  videoflip video-direction=GST_VIDEO_ORIENTATION_90R ! videoconvert !videoscale! fbdevsink
```
https://gstreamer.freedesktop.org/documentation/videofilter/videoflip.html?gi-language=c

**Comment by fduncanh** [comment]
I will see if UxPlay should have a    ...! videoconvert ! .. in its pipeline

**Comment by fduncanh** [comment]
There is still the issue that fbdevsink leave stuff behind when it closes.

**Comment by fduncanh** [comment]
so;

uxplay -r R -vs " videoconvertscale ! fbdevsink"  

seems to do the job.

**Comment by Boaztheostrich** [comment]
Thank you!

**Comment by fduncanh** [comment]
the github uxplay source has just been updated to move videoconvert (which was already there, but before videoflip)
to after it, and then to add a videoscale  before the videosink.

* now just "uxplay -vs fbdevsink -r R" should work without needing to add videoscale or videconvert

(or for you,   uxplay -vs "video/x-raw,width=480,height=800 ! fbdevsink" -r R )

**Comment by Boaztheostrich** [comment]
Excellent! Thanks again for the help
