### ISSUE TITLE
Fullscreen mode with d3d11videosink (windows) : fixed (was:Need fullscreen on cast)

### ISSUE THREAD

**Issue by drephuz** [FDH2/UxPlay#295]
using 

`uxplay -vs "d3d11videosink fullscreen-toggle-mode=alt-enter"` I am able to get the full screen to launch with **ALT+ENTER**

with the -fs flag, it only launches in full screen (with border) one time, all subsequent connections from iOS are not fullscreen.

Are there any parameters for `fullscreen-toggle-mode` other than `alt-enter` available?

Is there any way to make it so the casting screen goes borderless full screen every time?

**Comment by fduncanh** [comment]
Latest  github uxplay source has a fix for this:

uxplay -vs d3d11videosink      will give you the alt-enter toggle mode
uxplay -vs d3d11videosink -fs    will give you fullscreen mode each time a video connection is made


or use 

uxplay -vs "d3d11videosink fullscreen-toggle-mode=property fullscreen=true"

https://gstreamer.freedesktop.org/documentation/d3d11/d3d11videosink.html?gi-language=c

please check, and close the issue if it works for you.

**Comment by drephuz** [comment]
100% is the fix! We should add that information into the primary documentation, unless I just used the wrong guide! 

Thank you!!

**Comment by fduncanh** [comment]
added documentation of improved d3d11 support for fullscreen
