### ISSUE TITLE
[FEATURE] Add support for HDCP standard

### ISSUE THREAD

**Issue by Fallcrim** [FDH2/UxPlay#300]
As for a short introduction, so you don't have to google it, HDCP stands for High-bandwidth Digital Content Protection. It is a protocol which's job it is to testrict copying media data on its transfer through Displayport, HDMI or wireless solutions like Airplay.

As of right now, Netflix, Disney+ and other streaming services are using HDCP to protect the contents provided by them. On actual AppleTV devices, this standard is implemented and it is possible to stream using these devices. 
If I were to be a C programmer, I would take a look at it myself but unfortunately I have never looked into any of the C languages which is why I am writing this.
Thanks for any replies
Kind regards and greetings from Germany 👋

**Comment by thiccaxe** [comment]
AFAIK Netflix doesn't allow casting through airplay. The platforms that do use HLS (http live streaming). This is currently being developed in "Alternative Implementation"
