### ISSUE TITLE
Use X11 forwarding (ssh -X) to view UxPlay video on a headless system, needs X11 to be running (was "Kmssink not working")

### ISSUE THREAD

**Issue by Koefte** [FDH2/UxPlay#302]
On a headless pi the kmssink option goes through fine yet no video is displayed

**Comment by fduncanh** [comment]
kmssink is well tested on many different pi models, so something is wrong on your system.

give full details, include video monitor, OS etc.  check you have kmssink install with  gst-inspect-1.o 

see the UxPlay README

**Comment by fduncanh** [comment]
> On a headless pi

without a "head",   (video monitor) of course  no video will show.  You can only render audio.

**Comment by fduncanh** [comment]
If by "headless" you mean you want to use X11 forwarding to display video on a remote terminal,  you need to be running X11 on the pi, so kmssink will not do this.   

https://linuxconfig.org/how-to-enable-x11-forwarding-on-raspberry-pi



  I suppose you could set up X11 forwarding  and experiment with -vs xvimagesink or -vs ximagesink

(unfortunately ximagesink is broken on Pi for Gstreamer 1.22.0 - 1.22.10, it needs a tiny patch to fix a missing initialization the crept in when it was upgraded to touchscreen support.  without the patch it segfaults on starting.

ask here if you need the details on how and what to patch.

**Comment by fduncanh** [comment]
I tested X11 forwarding.  Yes  uxplay works:  video on the ssh client  (but the sound still comes from the Pi)

I also tested uxplay -vs xvimagesink    so it doesnt need  the ximagesink (which is patched on my system) 


use just   `ssh  <user@raspberrypi> -X uxplay`
