### ISSUE TITLE
Yocto Support

### ISSUE THREAD

**Issue by chrisvollorenew** [FDH2/UxPlay#305]
I would like to add this to a yocto project. Does anybody know of a Yocto meta-layer that has this functionality built-in?

**Comment by fduncanh** [comment]
Yocto is essentially a packaging system?

Apart from providing a generic RPM spec file, we leave packaging up to others.

**Comment by fduncanh** [comment]
should we close this (or will you)?

**Comment by chrisvollorenew** [comment]
@fduncanh I can close it. I think my question is answered ... there doesn't seem to be any specific yocto meta layer for this project. It would be good if someone made one =-)
