### ISSUE TITLE
Error linking CXX executable uxplay on Windows MSYS64

### ISSUE THREAD

**Issue by marekbujko** [FDH2/UxPlay#308]
Hi,
Linux UxPlay compiled without problems, but on Windows I have a problem.

After entering the ninja command, this pops up:
User@PC MINGW64 ~/UxPlay/build
$ ninja
[1/1] Linking CXX executable uxplay.exe
FAILED: uxplay.exe
C:\Windows\system32\cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe   CMakeFiles/uxplay.dir/uxplay.cpp.obj -o uxplay.e
xe -Wl,--out-implib,libuxplay.dll.a -Wl,--major-image-version,0,--minor-image-version,0  renderers/librenderers.a  lib/l
ibairplay.a  -lpthread  lib/playfair/libplayfair.a  lib/llhttp/libllhttp.a  -lwsock32  -liphlpapi  -lws2_32  C:/msys64/m
ingw64/lib/libplist-2.0.a  C:/msys64/mingw64/lib/libcrypto.dll.a  "C:/Program Files/Bonjour SDK//Lib/x64/dnssd.lib"  C:/
msys64/mingw64/lib/libgstsdp-1.0.dll.a  C:/msys64/mingw64/lib/libgstvideo-1.0.dll.a  C:/msys64/mingw64/lib/libgstapp-1.0
.dll.a  C:/msys64/mingw64/lib/libgstbase-1.0.dll.a  C:/msys64/mingw64/lib/libgstreamer-1.0.dll.a  C:/msys64/mingw64/lib/
libgobject-2.0.dll.a  C:/msys64/mingw64/lib/libglib-2.0.dll.a  C:/msys64/mingw64/lib/libintl.dll.a  -lkernel32 -luser32
-lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x292): undefined reference to `__imp_plist_from_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2ad): undefined reference to `__imp_plist_to_xml'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2eb): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x68f): undefined reference to `__imp_plist_from_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x6aa): undefined reference to `__imp_plist_to_xml'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x6b8): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x984): undefined reference to `__imp_plist_from_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x999): undefined reference to `__imp_plist_to_xml'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x9cf): undefined reference to `__imp_plist_dict_get_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x9e9): undefined reference to `__imp_plist_get_node_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x9fd): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0xad5): undefined reference to `__imp_plist_array_get_size'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0xaeb): undefined reference to `__imp_plist_array_get_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0xafa): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x10d1): undefined reference to `__imp_plist_from_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x10e0): undefined reference to `__imp_plist_dict_get_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1104): undefined reference to `__imp_plist_new_dict'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x111b): undefined reference to `__imp_plist_get_node_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1151): undefined reference to `__imp_plist_get_node_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1178): undefined reference to `__imp_plist_to_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x117f): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x12aa): undefined reference to `__imp_plist_get_string_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1476): undefined reference to `__imp_plist_get_data_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1656): undefined reference to `__imp_plist_get_bool_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1728): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1856): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1875): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x18da): undefined reference to `__imp_plist_new_array'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x18e8): undefined reference to `__imp_plist_array_get_size'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x18fa): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x195d): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x19e4): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x19f2): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1a23): undefined reference to `__imp_plist_array_append_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1a3b): undefined reference to `__imp_plist_array_get_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1a58): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1af2): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1b1a): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1b5a): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1b8a): undefined reference to `__imp_plist_get_uint_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1bae): undefined reference to `__imp_plist_get_bool_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1be4): undefined reference to `__imp_plist_get_bool_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1ca3): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1cb6): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1cc6): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1db3): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x1dc4): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2710): undefined reference to `__imp_plist_from_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2717): undefined reference to `__imp_plist_dict_get_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x278d): undefined reference to `__imp_plist_get_node_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x27b9): undefined reference to `__imp_plist_get_node_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x27dc): undefined reference to `__imp_plist_get_node_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2876): undefined reference to `__imp_plist_get_string_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x29aa): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x29bb): undefined reference to `__imp_plist_new_dict'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x29cf): undefined reference to `__imp_plist_new_data'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x29ef): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2a23): undefined reference to `__imp_plist_to_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2a83): undefined reference to `__imp_plist_get_data_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2b27): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2b43): undefined reference to `__imp_plist_new_dict'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2b54): undefined reference to `__imp_plist_new_data'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2b67): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2b7b): undefined reference to `__imp_plist_to_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2bb2): undefined reference to `__imp_plist_get_data_val'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2c4a): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2c93): undefined reference to `__imp_plist_new_dict'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2c9d): undefined reference to `__imp_plist_new_data'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2cc3): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x2d38): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x3001): undefined reference to `__imp_plist_new_dict'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x305d): undefined reference to `__imp_plist_new_string'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x306f): undefined reference to `__imp_plist_dict_set_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x30bf): undefined reference to `__imp_plist_new_data'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x3129): undefined reference to `__imp_plist_new_uint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x317b): undefined reference to `__imp_plist_new_array'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x31f0): undefined reference to `__imp_plist_array_append_item'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x3332): undefined reference to `__imp_plist_new_bool'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x366b): undefined reference to `__imp_plist_to_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop.c.obj):raop.c:(.text+0x3674): undefined reference to `__imp_plist_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop_rtp_mirror.c.obj):raop_rtp_mirro:(.text+0x89c): undefined reference to `__imp_plist_from_bin'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libairplay.a(r
aop_rtp_mirror.c.obj):raop_rtp_mirro:(.text+0x8ba): undefined reference to `__imp_plist_to_xml'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by marekbujko** [comment]
I reinstalled it again, only now I didn't use the command:
pacman -Syu

Then linking the CXX executable uxplay.exe worked.

**Comment by fduncanh** [comment]
all's well that ends well, then

closing as done.
