### ISSUE TITLE
Error about Server

### ISSUE THREAD

**Issue by Adalbar3333** [FDH2/UxPlay#316]
```bash
Initialized server socket(s)
*** ERROR: No DNS-SD Server found (DNSServiceRegister call returned kDNSServiceErr_Unknown)
```

I use linux because it's fairly light, so I am linux illiterate. What does this mean, and how do I resolve it?

**Comment by thiccaxe** [comment]
You need to start and/or install avahi

**Comment by ChrTopf** [comment]
Installing and then starting avahi solves this issue.
Just execute `systemctl start avahi-daemon` prior to starting uxplay.
I am using Manjaro and avahi was installed but not running yet.

**Comment by fduncanh** [comment]
looks done?

**Comment by nilspolek** [comment]
to be save enable it with `systemctl enable avahi-daemon` otherwise you have to restart it every time you use UxPlay
