### ISSUE TITLE
How to block seeing the terminal when mirroring.

### ISSUE THREAD

**Issue by AndrewPochapsky** [FDH2/UxPlay#318]
Using uxplay 1.68 on raspberry pi 5 with latest of dietpi.

Right now when mirroring with an iphone 13 I can still see the terminal running when both in portrait and landscape mode. Otherwise the shared resolution looks good, but I would prefer not seeing the terminal. Is there some way to add black bars or something else to cover the terminal? I am using X11.

I looked at the docs and I thought that maybe the `-o` flag would be what I wanted, but it doesn't seem to make a difference. Thank you!

**Comment by fduncanh** [comment]
alt-enter on X11 should put you in full screen mode.  or use the -fs option
