### ISSUE TITLE
Operation in parallel to KODI

### ISSUE THREAD

**Issue by DaCHack** [FDH2/UxPlay#319]
Hi,

I am following-up on an older post of mine here:
https://github.com/antimof/UxPlay/issues/112

Meanwhile I switched to an AMD64 system with virtual machines managed by Proxmox.
One VM is responsible for handling my HTPC needs and has the iGPU passed through.
The VM runs Debian and both KODI and UxPlay run fine even being booted with `sudo systemctl set-default multi-user.target` .

BUT: If I want to run both in parallel I was hoping to see the UxPlay stream on top of or instead of the KODI screen as soon as a connection is established. Instead, there is either no UxPlay stream or it is hidden behind KODI.

I run UxPlay with `uxplay -n Homeserver -vs "fbdevsink device=/dev/fb1"`.

Any idea how I can get its output into the foreground?

Thanks!

**Comment by thiccaxe** [comment]
Your desktop environment/window manager might provide API for this. For example, kde plasma has a dbus api which you can use to control windows.

**Comment by DaCHack** [comment]
The Plan is to use uxplay without a desktop Environment only in „init 3“. This is why I am using fbdevsink.

any chance to solve this without?

**Comment by thiccaxe** [comment]
You would need some sort of compositor to overlay and position your outputs from KODI and UxPlay.

**Comment by DaCHack** [comment]
OK, thanks. Need to check on how KODI produces its output without a DE. Probably via X11 - not sure about GDM...
But that would force me to use another sink I guess such as

**Comment by fduncanh** [comment]
closing as not a direct uxplay issue.

if you find a solution please post it here!

**Comment by Li-Gru** [comment]
on RaspbianOS

```
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install -y pipewire-audio-client-libraries pipewire-audio wireplumber pipewire-pulse pipewire-alsa
sudo apt-get install -y xwayland cage kodi uxplay avahi-daemon
sudo apt-get install -y gstreamer1.0-plugins-base gstreamer1.0-libav gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-gl gstreamer1.0-tools
sudo systemctl --now enable avahi-daemon.service
systemctl --user --now enable wireplumber.service

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
cat << EOF | sudo tee /etc/systemd/system/getty@tty1.service.d/autologin.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $USER --noclear %I $TERM
EOF

cat << 'EOF' > ~/.bash_profile 
test -z "$DISPLAY" && test "$(tty)" = "/dev/tty1" && /usr/bin/cage -- kodi --windowing=wayland
EOF

mkdir -p ~/.config/systemd/user
cat << EOF | tee ~/.config/systemd/user/uxplay.service
[Unit]
Description=uxplay wayland
ConditionUser=!root
After=avahi-daemon.service dbus.service wireplumber.service
[Service]
Type=simple
NoNewPrivileges=yes
RestrictNamespaces=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
Environment=WAYLAND_DISPLAY=/run/user/$(id -u)/wayland-0
ExecStart=/usr/bin/uxplay -vs waylandsink
Slice=session.slice
Restart=always
[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now uxplay.service
```
