### ISSUE TITLE
Lubuntu 18.04.3 needs gstreamer1.0-x

### ISSUE THREAD

**Issue by ovacikar** [FDH2/UxPlay#32]
After a reinstall of Lubuntu 18.04.3 , I was not able to get uxplay to work. 
0:00:01.456431080  6619 0x560031079a90 WARN             waylandsink gstwaylandsink.c:333:gst_wayland_sink_find_display:<video_sink-actual-sink-wayland> warning: Failed to create GstWlDisplay: 'Failed to connect to the wayland display '(default)''

A google search suggested to install gstreamer1.0-x , and it worked!

**Comment by fduncanh** [comment]
Thanks for the tip!

**Comment by fduncanh** [comment]
Thanks for the tip!

**Comment by fduncanh** [comment]
added a note in the Troubleshooting section of  README.   I had gstreamer1.0-x installed presumably it was installed as a dependency.  If you uninstall all gstreamer and reinstall just the packages mentioned in the build section of README, does gstreamer1.0-x get pulled in?

**Comment by ovacikar** [comment]
gstreamer1.0-plugins-good "recommends", not depends on gstreamer1.0-x

**Comment by fduncanh** [comment]
Thanks for this info
