### ISSUE TITLE
Mirror screen freezing close window

### ISSUE THREAD

**Issue by mbretter** [FDH2/UxPlay#322]
We are aware that a frozen mirror screen due to a reset connection will not block new connections. However, we use uxplay with an interactive kiosk in fullscreen mode and in this case the frozen mirror screen blocks every other actions.
Is there any way to somehow close the 'frozen mirror screen'?

**Comment by fduncanh** [comment]
This is handles by a call back function in uxplay.cpp   line 1506.

add a line "reset_video = false"   or just comment out the line "close_video = reset_video"

It would be easy to add a cmake option "cmake -DCLOSE_VIDEO" to do this  at compile time, if it would help you.


```
extern "C" void conn_reset (void *cls, int timeouts, bool reset_video) {
    LOGI("***ERROR lost connection with client (network problem?)");
    if (timeouts) {
        LOGI("   Client no-response limit of %d timeouts (%d seconds) reached:", timeouts, 3*timeouts);
        LOGI("   Sometimes the network connection may recover after a longer delay:\n"
             "   the default timeout limit n = %d can be changed with the \"-reset n\" option", NTP_TIMEOUT_LIMIT);
    }
    printf("reset_video %d\n",(int) reset_video);
    close_window = reset_video;    /* leave "frozen" window open if reset_video is false */
    raop_stop(raop);
    reset_loop = true;
}
```

**Comment by mbretter** [comment]
thank you for pointing this solution, I will give it a try and come back, after testing it.

**Comment by mbretter** [comment]
`close_window = false` was the trick.
I'll try to come up with a clean pr in the next days.
cheers,

**Comment by fduncanh** [comment]
I can do it.

Is a compile time  cmake option OK (to avoid yet another runtime option) or is an option needed?

(This depends on who needs this feature)

**Comment by mbretter** [comment]
Personally, I would prefer a commandline option, atm we have to maintain our own debian package. When implementing a commandline option we could you use the standard package of the distribution in the future.

**Comment by fduncanh** [comment]
OK, I'll see what to do for an option.

**Comment by fduncanh** [comment]
Done    (-nofreeze option). 

Please test  (you can also put "nofreeze" in your ~./uxplayrc file)

This is will very soon be part of a uxplay-1.69 release.    -nofreeze is tested, but please also test.

**Comment by mbretter** [comment]
Thank you, perfect!

We will test it as soon as possible

cheers

**Comment by fduncanh** [comment]
closing issue.

@mbretter 
reopen if your  test shows a problem
let us know the result

**Comment by mbretter** [comment]
We have just tested it successfully

thanx,
cheers
