### ISSUE TITLE
why the control packet should be enqueued into audio raop_buffer?

### ISSUE THREAD

**Issue by kgbook** [FDH2/UxPlay#324]
read packet from data socket and enqueue:
https://github.com/FDH2/UxPlay/blob/db38ac3ed1bec8f2d7d5043ecea4b83c004bc27d/lib/raop_rtp.c#L668

read packet from control socket and enqueue:

https://github.com/FDH2/UxPlay/blob/db38ac3ed1bec8f2d7d5043ecea4b83c004bc27d/lib/raop_rtp.c#L536

**Comment by fduncanh** [comment]
resent audio  packets are sent to the control port
