### ISSUE TITLE
UPDATED 2024-11-11: UxPlay-v1.71 beta: Experimental support for HLS video streaming is available for testing

### ISSUE THREAD

**Issue by fduncanh** [FDH2/UxPlay#326]
EDIT 2024-11-11: The latest code    (UxPlay-1.71-beta) is at https://github.com/FDH2/UxPlay/tree/video4

(an older  version  (based on UxPlay-1.69) remains available at  https://github.com/FDH2/UxPlay/tree/video2

* EDIT: 2024-08-24  The code now has removed code borrowed from external projects.

See the Wiki page https://github.com/FDH2/UxPlay/wiki/experimental-version-of-UxPlay-with-support-for-HLS-video-streaming-(you-tube-movies)

* Thanks to @shuax, @thiccaxe, @GenghisKhanDrip for helping get this started.   See issue #134

**Comment by thiccaxe** [comment]
I think the position key is off by a factor of 1000. Maybe something to do with the GST_SECOND constant?

**Comment by tehsu** [comment]
Works pretty darn good with Premium.

**Comment by nathanbacon** [comment]
> Works pretty darn good with Premium.

Did you test it on Mac?

**Comment by fduncanh** [comment]
Now in master branch as future UxPlay-1.71

Please test HLS videos treaming!

**Comment by fduncanh** [comment]
@thiccaxe 
>  think the position key is off by a factor of 1000. Maybe something to do with the GST_SECOND constant?

can you explain?   is this still an issue in the code now on UxPlay master  as a future uxplay-1.71?

* I perhaps did not implement starting at the "position" in the video.   Any testing feedback would be good.

The -hls option is needed to activate hls support.

**Comment by fduncanh** [comment]
HLS support is now included in the UxPlay-1.71 release.

Thanks to all whose help was invaluable, @thiccaxe @shuax,  @GenghisKhanDrip for helping getting started with this!

and to @tishion for his work on apsdk-public https://github.com/air-display/apsdk-public which was an invaluable guide.

(see the v-1.71 release text https://github.com/FDH2/UxPlay/releases/tag/v1.71 )
