### ISSUE TITLE
Option -dacp not working

### ISSUE THREAD

**Issue by DaCHack** [FDH2/UxPlay#329]
For context:
- Still working on having KODI and UxPlay work in parallel (https://github.com/FDH2/UxPlay/issues/319)
- Tried to find a way to close KODI on UxPlay connections and then restart again
   - Hint to use the dacp-file from [here](https://github.com/FDH2/UxPlay/issues/271#issuecomment-1952627545) does not work as to be seen below
   - Pre-/Post-connection hooks as suggested [here](https://github.com/FDH2/UxPlay/issues/46#issuecomment-1007941461) are not implemented. **Question**: Is this understanding still correct?

```
uxplay -n Homeserver -nh -s 1280x1024 -nohold -dacp .uxplay.dacp -vs "fbdevsink device=/dev/fb1"
unknown option -dacp, stopping
```

**Comment by fduncanh** [comment]
-dacp was only added in v1.67.    Current is 1.69

1.67 2023-11-30 Add support for Apple-style one-time pin authentication of clients with option "-pin": (uses SRP6a authentication protocol and public key persistence). Detection with error message of (currently) unsupported H265 video when requesting high resolution over wired ethernet. Removed rpi* options (which are not valid with new Raspberry Pi model 5, and can be replaced by combinations of other options). Added optional argument "mac" to "-m" option, to specify a replacement MAC address/Device ID. Update llhttp to v. 9.1.3. **Add -dacp option for exporting current client DACP info (for remotes)**.

**Comment by DaCHack** [comment]
@fduncanh Thanks! And adding hook options to the cmd is still not planned?
