### ISSUE TITLE
UxPlay will no initialize server sockets as root

### ISSUE THREAD

**Issue by DaCHack** [FDH2/UxPlay#330]
Just came across this while testing UxPlay on a q35 VM in Proxmox under Debian 12:

Seems like UxPlay 1.62 does not initialize server socket(s) under root. With an unprivileged user it works.

Not sure if this is by intention or I spotted a very specific case here.

**Comment by fduncanh** [comment]
It's not designed for running as root.  (which is not advised).  A quick test seems to show that server sockets get initialized but the dns-sd "bonjour" service doesnt connect.
