### ISSUE TITLE
Uxplay looks blurry in 4k resolution ( especially the texts, youtube videos seems fine)

### ISSUE THREAD

**Issue by ank-007** [FDH2/UxPlay#333]
this is the how i am launching uxplay -n \"%2\" -pin %3 -nh -avdec -fs -vs d3d11videosink -reg, 

videos i play with my phone is fine, but the texts which comes in ads or if I open wikipedia, the texts are horribleand not readable.  Is it because of -avdec, I removed it , it didn't make any change

**Comment by fduncanh** [comment]
what do you mean by "4K resolution".. describe your setup.

default resolution of AirPlay is 1080p,  1920 x1080.      (wxh)2560x14440
Try changing it with -s wxh    (default is  1080p "-s 1920x1080")  see how much higher the iOS client allows:
4K is 3480x2160   

1440p is "-s 2560x1440"  and works for me.

Whether you get those resolutions just because you ask the client for them isn't clear.  Just try and see.

**Comment by fduncanh** [comment]
You have to create your own startup file ~/.uxplayrc   See the uxplay README (or even uxplay -h).   Its just a convenience to avoid using -s wxh explicitly

The debug logs won't provide any useful info about your issue..

do you notice any difference when you use -s 1980x1080,-s 2560x1440 or -s 3840x2160?

**Comment by ank-007** [comment]
it seems to be display scaling issue my 4k monitor was running with 300% scaling, with 100% its fine, how can I make uxplay d3d11 window ignore display scaling, tried doing this in qt, but didn't work 
QString pathWithArgs = QString("%1 -n \"%2\" -pin %3 -nh -s 3840x2160 -avdec -fs -vs d3d11videosink -reg ").arg(processPath[i]).arg(name).arg(pin);
            QProcessEnvironment env1 = QProcessEnvironment::systemEnvironment();

            env1.insert("QT_SCALE_FACTOR", "1");
            env1.insert("QT_AUTO_SCREEN_SCALE_FACTOR", "0");
            env1.insert("QT_ENABLE_HIGHDPI_SCALING", "0");
            rxProcess[i]->setProcessEnvironment(env1);
            rxProcess[i]->start(pathWithArgs);

**Comment by fduncanh** [comment]
this is the d3d11 gstreamer doc.

maybe -vs "d3d11videosink  scale-x=0.33 scale-y=0.33"  ???

https://gstreamer.freedesktop.org/documentation/d3d11/d3d11videosink.html?gi-language=c

**Comment by ank-007** [comment]
Thank you for the help.
Got it working with reg key change like [this](https://superuser.com/questions/1230346/overriding-high-dpi-scaling-from-the-command-line)
