### ISSUE TITLE
iPhone doesn't see airplay

### ISSUE THREAD

**Issue by NotIdrizdi** [FDH2/UxPlay#334]
Does anyone have an idea why my iPhone does not see the possibility of airplay on Raspberry Pi 5, from what I noticed, my Windows PC can connect to the Pi via SSH, but iPhone and Macbook are not able to do this.

**Comment by fduncanh** [comment]
>Does anyone have an idea why my iPhone does not see the possibility of airplay on Raspberry Pi 5, from what I noticed, my Windows PC can connect to the Pi via SSH, but iPhone and Macbook are not able to do this.

*  ??? UxPlay does not use SSH (Secure SHell)


the answers will probably be found in https://github.com/FDH2/UxPlay#uxplay-169--airplay-mirror-and-airplay-audio-server-for-linux-macos-and-unix-now-also-runs-on-windows

> The UxPlay server and its client must be on the same local area network, on which a Bonjour/Zeroconf mDNS/DNS-SD server is also running (only DNS-SD "Service Discovery" service is strictly necessary, it is not necessary that the local network also be of the ".local" mDNS-based type). On Linux and BSD Unix servers, this is usually provided by [Avahi](https://www.avahi.org/), through the avahi-daemon service, and is included in most Linux distributions (this service can also be provided by macOS, iOS or Windows servers).

**Comment by NotIdrizdi** [comment]
I understand that this connection does not go through SSH, I wanted to provide more information that somehow my Mac does not even see the Raspberry on the network and this may be the reason why I cannot share the screen via UxPlay. As you can see on SS, both systems are on the same network, although the iPhone and Macbook are not able to see my Raspberry Pi 5
![photo_2024-08-30_09-02-12](https://github.com/user-attachments/assets/1333370d-693a-4230-ac69-2780f410ea5c)
![photo_2024-08-30_09-04-30](https://github.com/user-attachments/assets/dd4dc485-872b-450a-8436-cd8d48f61c15)

**Comment by fduncanh** [comment]
Form the README document:  here is a useful tool for investigating DNSSD network problems:

If UxPlay stalls without an error message and without the server name showing on the client, this is a network problem (if your UxPlay version is older than 1.60, it is also the behavior when no DNS-SD server is found.)

A useful tool for examining such network problems from the client end is the (free) Discovery DNS-SD browser [available in the Apple App Store](https://apps.apple.com/us/developer/lily-ballard/id305441020) for both iOS (works on iPadOS too) and macOS.
