### ISSUE TITLE
Sound stuttering / streaming from iOS device to Debian 13

### ISSUE THREAD

**Issue by BastaRasta** [FDH2/UxPlay#337]
Hi all,

I’m using version 1.69 and this is the command I’m issuing :

uxplay -async -n harman/kardon -nh -nohold 

sound streaming works fine but I have either sound stuttering or small pauses during streaming which is quite annoying.
I use uxplay to stream radio stations from iOS and be able to change volume / pause from iOS. Linux sound output is plugged into an amp to listen to radio.

I’m suspecting it’s from my internet speed or latency.

Is there a way to enforce really large sound buffering, like 5 or 10 seconds? Anything else you could recommend?

**Comment by fduncanh** [comment]
does dropping option " -async " help in any way?

in lib/raop_buffer.c,  you will find

#define RAOP_BUFFER_LENGTH 32

For ALAC sound,   each frame takes 354/44100   = 0.008 secs, so a (ring) buffer size 32 stores  about 0.25 secs.

for a 10 sec buffer I think that means buffer length  32 x 40   There might be something else you need to  change to delay audio though.


Anyway, try a rebuild with a bigger buffer to see if that does anything for you.

**Comment by fduncanh** [comment]
>I think you are implying above to slightly change the code and recompile. I think this is way too much for my level, but thank you!

Its really easy!  just follow the line by line recipe for compiling in https://github.com/FDH2/UxPlay#uxplay-169--airplay-mirror-and-airplay-audio-server-for-linux-macos-and-unix-now-also-runs-on-windows

once you have mastered that, change 
#define RAOP_BUFFER_LENGTH 32   (0.25 sec ) in  UxPlay/lib/raop_buffer.c line 36 so 32 -> 960   (10 seconds buffer)
and recompile then  install.

it will install in /usr/local/bin  so if  you dont uninstall your current uxplay, call it with /usr/local/bin/uxplay.    

you can do it!

**Comment by fduncanh** [comment]
@BastaRasta should this be closed?

**Comment by fduncanh** [comment]
closing, as seems stale.

fell free to reopen if there is more info.
