### ISSUE TITLE
Apple TV not showing

### ISSUE THREAD

**Issue by kreimben** [FDH2/UxPlay#34]
Hi guys. always thanks about your contributions though, I can mirror almost of app in my ipad and iphone EXCEPT Apple TV.

Whenever I play any serices of apple original, mirroring is stopped.

Is that problem of Apple? (prevent mirroring not real apple devices or something...)

Please help me :)

**Comment by fduncanh** [comment]
Yes.

Apple TV video (but not audio) is protected by an extra layer of encryption that UxPlay can't decrypt.

You get to see the frame in which the video should play, and the controls for it, but no actual video.
