### ISSUE TITLE
Pin option not working

### ISSUE THREAD

**Issue by Koefte** [FDH2/UxPlay#342]
Raspberry pi os on pi 3 pin simply doesnt work, connection is established but with pin flag enabled and set to any value, the pin isn't requested on the client.

**Comment by fduncanh** [comment]
Just tested  "uxplay -pin" on a R Pi 3B+ running current Raspberry Pi OS (bookworm)   UxPlay was self-compiled UxPlay-1.69 from github.    

worked perfectly: the pin displayed on the R Pi, and the box asking for the pin showed on the client iPad

(The version of uxplay supplied with bookworm is 1.62, which doesn't support -pin, and shows an "unknown option" error is -pin is used.)

**Comment by fduncanh** [comment]
Note:    If the client has ever successfully registered   with uxplay, it will never again request a pin untill UxPlay changes its deviceID   (usually the host's true MAC address)

(There is probably a way to get the client to forget a pin-pairing, but if so, I don't remember)

To use the above MAC address,

```
uxplay -pin -m AA:AA:AA:AA:AA:AA
```
 

To use a different 6-octet MAC address like AA:AA:AA:AA:AA:AA try

**Comment by fduncanh** [comment]
closing as seems stale.
feel free to reopen with further info
