### ISSUE TITLE
AppleTV app video uses extra DRM that UxPlay cannot decrypt (was: No Video Display When Streaming Apple TV Content, Only Audio)

### ISSUE THREAD

**Issue by TecSeeker** [FDH2/UxPlay#345]
**System Information**
- Computer OS: Debian 12
- iPad: iPad Air 4
- iPadOS version: 17.7
- UxPlay version：UxPlay 1.62

 I am using UxPlay to mirror my iPad to my computer. Other apps stream without any problems—both audio and video work perfectly. However, when I try to stream content from the Apple TV app, UxPlay only plays the audio, and the video does not display.Is there any way to fix this, or is it a limitation of UxPlay when handling Apple TV content?

**Comment by fduncanh** [comment]
It's a limitation: This is explained in the README:

>Note that Apple video-DRM (as found in "Apple TV app" content on the client) cannot be decrypted by UxPlay, and the Apple TV app cannot be watched using UxPlay's AirPlay Mirror mode (only the unprotected audio will be streamed, in AAC format), but both video and audio content from DRM-free apps like "YouTube app" will be streamed by UxPlay in Mirror mode.
