### ISSUE TITLE
freezing after a few minutes

### ISSUE THREAD

**Issue by rahulsindhu01** [FDH2/UxPlay#347]
so i am using uxplay on linux mint and i am able to connect and then stream from my ipad without any problem but after a few minutes or even seconds it just freezes at one frame and there are no error messages in the terminal 

this is the output 

`UxPlay 1.68: An Open-Source AirPlay mirroring and audio-streaming server.
using system MAC address 0a:e0:af:a2:03:91
Initialized server socket(s)
Accepted IPv4 client on socket 39
Local: 192.168.x.xx
Remote: 192.168.x.xx
connection request from iPad (2) (iPad12,1) with deviceID = xxxxxxxxxxxx

Client identified as User-Agent: AirPlay/800.74.1
Accepted IPv4 client on socket 41
Local: 192.168.x.xx
Remote: 192.168.x.xx
raop_rtp_mirror starting mirroring
Begin streaming to GStreamer video pipeline

*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode

`

**Comment by fduncanh** [comment]
Use uxplay -d to get full debug output.   This may show what is happening.

To expose any GStreamer issues use "export GST_DEBUG = 2" (or 4) before running uxplay.

There is a trouble-shooting section in the README https://github.com/FDH2/UxPlay#troubleshooting

**Comment by fduncanh** [comment]
Please let us know if this is resolved

**Comment by rahulsindhu01** [comment]
> Please let us know if this is resolved

It seems to freeze when i change the workspace, i am using obs and whenever i change to another workspce that doesnt have the uxplay window it just freezes and i have to reconnect everytime

**Comment by fduncanh** [comment]
Are you using UxPlay with obs, or just running obs at the same time?  (Not very familiar with obs, and have not tested with it, though see #349)

Can you give a complete description of what you are doing, on what kind of hardware, and step-by-step instructions for what we need to do to reproduce your issue.

**Comment by rahulsindhu01** [comment]
I reinstalled obs and uxplay and now i am on arch linux, everything is working fine
