### ISSUE TITLE
Fixed: UxPlay on MacOS + Homebrew gstreamer >= 1.24 (was) No window popup

### ISSUE THREAD

**Issue by LoSunny** [FDH2/UxPlay#354]
When I try to run UxPlay on MacOS, no window will be popup when I choose the `osxvideosink`, in which a warning occurred
```
% uxplay -fs -vs osxvideosink
UxPlay 1.70: An Open-Source AirPlay mirroring and audio-streaming server.
macOS detected: use -nc option as workaround for GStreamer problem

** (<unknown>:20718): WARNING **: 00:02:10.269: An NSRunLoop needs to be running on the main thread to ensure correct behaviour on macOS. Use gst_macos_main() or call [NSApplication sharedApplication] in your code before using this element.
using system MAC address aa:aa:aa:aa:aa:aa
Initialized server socket(s)
```

**Comment by fduncanh** [comment]
we  just tested on macos sonoma 14.7 with uxplay-1.70.   macbook pro m2
Gstreamer-1.24.8 from the gstreamer site is being used.

"uxplay -vs osxvideosink" works here.
a small green square initially opens.   when the connection to the client is made, the full  osxvideosink window opens.

something is different from usual on your system:, any idea what might be special about your setup (describe it more)?


>** (<unknown>:20718): WARNING **: 00:02:10.269: An NSRunLoop needs to be running on the main thread to ensure correct behaviour on macOS. Use gst_macos_main() or call [NSApplication sharedApplication] in your code before using this element

This is unfamilar: maybe its some now issue in macOS Sequioa: are you using that?

We are using gst_macos_main, but it's  possible something needs adjusting for Sequoia, will check.

**Comment by fduncanh** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-docs/-/issues/79
please let us know ASAP whether this is macOS sequioa, in case something needs fixing.

**Comment by fduncanh** [comment]
When you ran cmake,  to build uxplay there should have been a message "define GST_MACOS"  do you get it?:


```
if  ( GST_MACOS )
     add_definitions( -DGST_MACOS )
     message ( STATUS "define GST_MACOS" )
endif()
```

**Comment by fduncanh** [comment]
issue now fixed. get latest Github  UxPlay and rebuild.

**Comment by LoSunny** [comment]
Yes needed I have install gstreamer from homebrew, the fix works perfectly. Thank you 🙌
