### ISSUE TITLE
Homebrew improvement: Custom path installation

### ISSUE THREAD

**Issue by LoSunny** [FDH2/UxPlay#357]
Some users might install homebrew in custom paths, thus we could also add a new environment path which make use of either `HOMEBREW_PREFIX` or `HOMEBREW_REPOSITORY` environment variable accord to [this](https://docs.brew.sh/Manpage#environment)
Improvement 1:
https://github.com/FDH2/UxPlay/blob/b1bf3d49158b1c23a8ec296fa2de988629092e15/lib/CMakeLists.txt#L44-L48
Add two lines
```
set( ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:$ENV{HOMEBREW_PREFIX}/lib/pkgconfig/" ) # Brew using prefix
set( ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:$ENV{HOMEBREW_PREFIX}/opt/openssl@3/lib/pkgconfig" ) # Brew using prefix
```
Improvement 2:
https://github.com/FDH2/UxPlay/blob/b1bf3d49158b1c23a8ec296fa2de988629092e15/renderers/CMakeLists.txt#L5-L7
Same as above
```
set( ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:$ENV{HOMEBREW_PREFIX}/lib/pkgconfig/" ) # Brew using prefix
```

**Comment by fduncanh** [comment]
Thanks, will add.

**Comment by fduncanh** [comment]
done

**Comment by fduncanh** [comment]
@LoSunny 

since you presumably have a homebrew installation, can you test the change now?

**Comment by LoSunny** [comment]
Yes it works. Thanks
