### ISSUE TITLE
Is Support for hls video stream still been developed?

### ISSUE THREAD

**Issue by hhchenhhhhhhh** [FDH2/UxPlay#361]
### Discussed in https://github.com/FDH2/UxPlay/discussions/360

<div type='discussions-op-text'>

<sup>Originally posted by **hhchenhhhhhhh** November  2, 2024</sup>
The last commit for the branch video2 is 2 months ago</div>

**Comment by fduncanh** [comment]
Yes

the video2 branch will be integrated into latest  uxplay in video3 branch.  (thls work slowed while h265 video was added to UxPlay 1.70, (after a discovery on how to get h265 in AirPlay was made)

video3 branch is not yet functional.
