### ISSUE TITLE
Fixed broken support for Ubuntu-20.04LTS  (was: Install fails with error)

### ISSUE THREAD

**Issue by Booth1983** [FDH2/UxPlay#364]
Hi,
when I compile Uxplay on Ubuntu 20.04 it gives me the same Issue as mentioned above in the Headline.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBPLIST
    linked by target "airplay" in directory /home/schule/bin/uxplay/UxPlay/lib

-- Configuring incomplete, errors occurred!
```

Use of **sudo apt install libplist3** (or **sudo apt-get install libplist3**)  says, that its allready installed. Same with libplist-dev.

Greetings

**Comment by fduncanh** [comment]
Ubuntu 20.04 is old and UxPlay has been well-tested on it.
(maybe newer UxPlay hasnt been tested, though). Will check.


I'm not sure that libplist3 package is needed.      (It might be a command-line utiility for plists)

try removing it.    If its is needed, reinstalling libplist-dev will reinstall it.


what is needed is libplist-dev   (see the README installation instructions)
presumably it is not installed properly somehow?

sudo apt install  libplist-dev

did you get the "found libplist-<version>" cmake message?

lib/CMakeLists.txt:
```
# libplist
pkg_search_module(PLIST REQUIRED libplist-2.0)
if ( PLIST_FOUND )
   message( STATUS "found libplist-${PLIST_VERSION}" )
endif()
if( APPLE )
<snip>
elseif( WIN32)
<snip>  
else ()
  find_library( LIBPLIST ${PLIST_LIBRARIES} PATH ${PLIST_LIBDIR} )   <======== plist library didnt get found!!!
  target_link_libraries ( airplay PUBLIC ${LIBPLIST} )
endif()
target_include_directories( airplay PRIVATE ${PLIST_INCLUDE_DIRS} )
```

**Comment by fduncanh** [comment]
We checked that UxPlay-1.70 builds correctly on  Ubuntu 20.04.6 LTS, fully updated.

interestingly,  it builds if libplist3 is installed, _whether or not liblist-dev is installed_

**Comment by fduncanh** [comment]
Question: did cmake tell you that libplist-3.2.0  was found? (or not)

**Comment by Booth1983** [comment]
Ill send it in the next few days.

**Comment by Booth1983** [comment]
Here are my results

**sudo apt install libplist-dev** 

`Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libplist-dev ist schon die neueste Version (2.1.0-4build2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 24 nicht aktualisiert.`

**cmake .**

`-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project name: uxplay
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Will compile using X11 Libraries  (use cmake option -DNO_X11_DEPS=ON if X11 dependence is not wanted)
-- *** CFLAGS "" from build environment will be postpended to CMAKE_CFLAGS
-- Using CFLAGS with  -march=native
-- *** ONLY USE THIS WHEN COMPILING ON THE MACHINE THAT WILL RUN UXPLAY
--   run "cmake -DNO_MARCH_NATIVE=ON" to switch off this compiler option
-- using CMAKE_CFLAGS: -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Wall -Ofast -march=native 
-- Looking for include file sys/endian.h
-- Looking for include file sys/endian.h - not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'libplist-2.0'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'libplist-2.0' found
Call Stack (most recent call first):
  lib/CMakeLists.txt:85 (pkg_search_module)


-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.1f", minimum required is "1.1.1")  
-- Checking for one of the modules 'avahi-compat-libdns_sd'
-- Will use X_DISPLAY_FIX
-- Checking for module 'gstreamer-1.0>=1.20'
--   Requested 'gstreamer-1.0 >= 1.20' but version of GStreamer is 1.16.3
--   Failure to find Gstreamer >= 1.20 is NOT an error!
--   ZOOMFIX will be applied as Gstreamer version is < 1.20
-- Checking for modules 'gstreamer-1.0>=1.4;gstreamer-sdp-1.0>=1.4;gstreamer-video-1.0>=1.4;gstreamer-app-1.0>=1.4'
--   Found gstreamer-1.0, version 1.16.3
--   Found gstreamer-sdp-1.0, version 1.16.3
--   Found gstreamer-video-1.0, version 1.16.3
--   Found gstreamer-app-1.0, version 1.16.3
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBPLIST
    linked by target "airplay" in directory /home/schule/bin/uxplay/UxPlay/lib

-- Configuring incomplete, errors occurred!
See also "/home/schule/bin/uxplay/UxPlay/CMakeFiles/CMakeOutput.log".
See also "/home/schule/bin/uxplay/UxPlay/CMakeFiles/CMakeError.log".
`

**Comment by fduncanh** [comment]
your show

```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'libplist-2.0'                          <==============something weird here should be `libplist>=2.0`
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'libplist-2.0' found
Call Stack (most recent call first):
  lib/CMakeLists.txt:85 (pkg_search_module)


-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.1f", minimum required is "1.1.1")  
-- Checking for one of the modules 'avahi-compat-libdns_sd'
```

I get
`
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'libplist>=2.0'                              <==================  NOTE DIFFERENCE
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "3.0.2", minimum required is "1.1.1")  


```

My lib/CMakeLists.txt   contains

```
# libplist
if( APPLE OR WIN32 )
   <snip>
else ()
  pkg_search_module(PLIST libplist>=2.0)                             <===================NOTE THIS LINE
  if(NOT PLIST_FOUND)
    pkg_search_module(PLIST REQUIRED libplist-2.0)
  endif()
  find_library( LIBPLIST ${PLIST_LIBRARIES} PATH ${PLIST_LIBDIR} )
  target_link_libraries ( airplay PUBLIC ${LIBPLIST} )
endif()
target_include_directories( airplay PRIVATE ${PLIST_INCLUDE_DIRS} )

```


This is UxPlay-1.70 from github.

what version are you using?   is that line in your CMakeLists.txt modified?

```
$uname -a
Linux ubuntu21 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 22.04.1 LTS \n \l
$cmake --version
cmake version 3.22.1

```

**Comment by fduncanh** [comment]
AHA:  I am testing on UBuntu 22.04

**Comment by fduncanh** [comment]
Now on 20.04
$ cat /etc/issue
Ubuntu 20.04.6 LTS \n \l

cmake shows:
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'libplist-2.0'
-- found libplist-2.2.1
```
BUT THEN I FOUND libplist in /usr/local/lib, and when I removed it, I reproduce your error!!!. so I must have build it from source on the ubuntu-20.04 test machine.

https://github.com/FDH2/UxPlay#building-libplist--200-from-source

* IIRC, the libplist maintainer made some change that broke something.   I'll look into this issue some more, not today.
* You might need to build a more recent libplist.

**Comment by Booth1983** [comment]
Compiled libplist by hand and now **cmake .** gives the following output:

```
-- Project name: uxplay
-- Will compile using X11 Libraries  (use cmake option -DNO_X11_DEPS=ON if X11 dependence is not wanted)
-- *** CFLAGS "" from build environment will be postpended to CMAKE_CFLAGS
-- Using CFLAGS with  -march=native
-- *** ONLY USE THIS WHEN COMPILING ON THE MACHINE THAT WILL RUN UXPLAY
--   run "cmake -DNO_MARCH_NATIVE=ON" to switch off this compiler option
-- using CMAKE_CFLAGS: -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Wall -Ofast -march=native 
-- Checking for one of the modules 'libplist-2.0'
-- found libplist-2.6.0-3-ga5df0a6
-- Will use X_DISPLAY_FIX
-- Checking for module 'gstreamer-1.0>=1.20'
--   Requested 'gstreamer-1.0 >= 1.20' but version of GStreamer is 1.16.3
--   Failure to find Gstreamer >= 1.20 is NOT an error!
--   ZOOMFIX will be applied as Gstreamer version is < 1.20
-- Configuring done
-- Generating done
-- Build files have been written to: /home/schule/bin/uxplay/UxPlay
```

so this seems so solve the problem. Got an error with make now, but I guess I have deinstalled some dependencies on the way. Going to reinstall my ubuntu, just in case.

**Comment by fduncanh** [comment]
I'll take a look to see if I can get it to build with the libplist  in Ubuntu-20.04.   It should be easy to teset for the libplist release, and use an #ifdef

There was an  api-breaking  change in a libplist release to make to code "prettier".     (When it happened a second time I intervened with the maintainer and got that change reversed)
