### ISSUE TITLE
How to Request IDR Frame for Video Stream

### ISSUE THREAD

**Issue by hellomanyi** [FDH2/UxPlay#366]
AirPlay video frames, how does the receiving end actively request IDR frames?

**Comment by hellomanyi** [comment]
AirPlay currently only sends I frames in the first frame or when switching between horizontal and vertical screens. Can the receiving end actively request IDR frames?

**Comment by fduncanh** [comment]
No

In screen mirror mode, uxplay does not communicate much  with the iOS client after the initial  setup,  except to send a heartbeat signal, NTP request or missing audio frame request, nothing on the video channel, and , so iDR frames are only sent when the client decides to do it (e.g, when its rotated from horizontal to vertical screens).

(There is a possibility for an  "event" channel used for reverse http that is unused in mirror mode.   It is used in HLS mode
 (in development)  but not in the mirror mode.)

* why do you need to request IDR frames?

**Comment by hellomanyi** [comment]
> No
> 
> In screen mirror mode, uxplay does not communicate much with the iOS client after the initial setup, except to send a heartbeat signal, NTP request or missing audio frame request, nothing on the video channel, and , so iDR frames are only sent when the client decides to do it (e.g, when its rotated from horizontal to vertical screens).
> 
> (There is a possibility for an "event" channel used for reverse http that is unused in mirror mode. It is used in HLS mode (in development) but not in the mirror mode.) _This would be the only way the client could initiate anything, but I don't think the mirror mode protocol has such a feature?_
> 
> * why do you need to request IDR frames?

Thank you for your reply; if there is only one IDR frame, we need to continue to decode the entire mirror mode; when it is necessary to pause the display for a while, and then display it again, and so on; during this period, the best way is to re-request the IDR; currently we can only It is necessary to continue decoding, otherwise the screen will be blurred;

**Comment by fduncanh** [comment]
I don't think  mirror mode allows the server to pause the stream.

An older version of mirroring protocol is described here.
http://nto.github.io/AirPlay.html#screenmirroring

Note  HLS video  streaming  is  available in this experimental version of UxPlay:
https://github.com/FDH2/UxPlay/tree/video4
HLS video can be paused by action of the client.    I believe HLS video could be paused on the server, using the "event channel", but uxplay doesnt accept any user input except the startup options.

what are you trying to accomplish? are you trying to extend uxplay capabilities as a fork, or just 
use it (in which case, please explain more about "pausing the display" : is this the client display or the server display?)

**Comment by fduncanh** [comment]
seems done (no further info)

closing
