### ISSUE TITLE
Running uxplay on a specific display via DISPLAY=... doesn't work

### ISSUE THREAD

**Issue by carylewis** [FDH2/UxPlay#370]
When I attempt to launch uxplay on a specific X display by setting DISPLAY=:1 for example, uxplay, once a device connects, renders on display :0.

If I run uxplay from a terminal window within a tigervnc virtual X11 session, (DISPLAY=:1) then it renders as expected.

What does uxplay use to determine which display to render on?

**Comment by fduncanh** [comment]
Yes it would be better to have an option telling uxplay which display to use.  



You should be able to do it with

```
uxplay -vs "xvimagesink display=:1 " 

```

We dont have a system with a second display set up right now, but could get one set up.     Maybe you can test?

With a single display,  "xvimagesink display=:0" works but "..display=:1" doesn't, so I think the format is correct.


see https://gstreamer.freedesktop.org/documentation/xvimagesink/index.html?gi-language=c

Can you confirm if it works.  If so, it should be mentioned in the "readme".

It would also be easy to add an option "-Xdisplay n"

**Comment by fduncanh** [comment]
UxPlay does not itself determine the display.   It leaves it up to GStreamer to make the choice "automatically"    From what you describe, I would guess the default choice by GStreamer is the display in which the window of the terminal that launches uxplay is displayed, but giving the display=:n option to xvimagesink will override that.

**Comment by fduncanh** [comment]
Tried and failed to  get a multidisplay setup working with -vs "xvimagesink display=:1" working, but it seems to be the right format since display=:0 works.  Please report if it works for you.

**Comment by carylewis** [comment]
This command worked:

 uxplay -vs "ximagesink display=:1" -d -bt709
 
 I am running this on a RaspberryPi 4B using tigervnc.
 
 Thanks for your help.

The frame rate is not great, I am assuming that's because of the version of Gstreamer I am using.

I have a Raspberry Pi 5 on order, so I am hoping that the frame rate on that will be better.

Btw, I am running gstreamer 1.22.0, why do I still need to use the -bt709 option? I thought that was only needed on unpatched gstreamers?

Furthermore, I seem to get less jaggy playback with:

 uxplay -vs "ximagesink display=:1" -d -avdec

**Comment by fduncanh** [comment]
> Btw, I am running gstreamer 1.22.0, why do I still need to use the -bt709 option? I thought that was only needed on unpatched gstreamers?

are you using raspberry pi OS?   which release?

**Comment by carylewis** [comment]
I'm sorry that I left that out of the post, I am running Debian bookworm:

RETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by fduncanh** [comment]
Debian should be OK on R Pi 5,  but wont have the out-of-mainline-kernel driver for h264 decoding in the Broadcom GPU of pi 4B and earlier.    Pi 5 is powerful enough to use software decoding (-avdec) for h264 video. and doesnt have hardware h264 decoding.

(Pi 5 has a h265 decoding block as does Pi 4B, but the driver for that is also not yet in mainline kernel and is not yet supported by GStreamer, so UxPlay cannot use it at this time: this is for 4K video).


The -bt709 option was needed to get video4linux2 (v4l2) working, this is used to access the proprietary  driver for the Broadcom GPU.  provided in R Pi OS but not simple debian. The v4l2 driver originally  did not recognize the slightly unusual variant bt709 color map used by apple.  I got the fix into GStreamer 1.22.

Note that current RPiOS is based on bookworm, but has a non-mainline kernel with  R Pi added drivers..


what is different if you dont use -bt709 ?

**Comment by carylewis** [comment]
Nothing gets displayed without the -bt709

To be clear, I am running the PiOS (at least that is what the splash screen
on boot up shows).

**Comment by fduncanh** [comment]
to be clear:

*  what do  "uname -a ", "gst-inspect-1.0 video4linux2 ", and "lsmod | grep bcm"    report?

can you explain more about:

> I am running this on a RaspberryPi 4B using tigervnc.

**Comment by fduncanh** [comment]
* YES YOU ARE CORRECT!!!  it seem -bt709 IS still needed by R Pi 4B  (and  earlier) with GStreamer-1.22.0   (Raspberry Pi OS bookworm)

I checked that the "fix"  that was accepted July 2022 in GStreamer is there in the code.   Mysterious.

Since R Pi OS Bookworm was released when R Pi 5 became available, and we got an early one, maybe bookworm on R Pi 4B wasnt properly tested?   Maybe some other change broke things again?
 
Will look into this.   "export GST_DEBUG=4" should reveal what is happening.

**Comment by fduncanh** [comment]
It seems that the original problem that the -bt709 option fixed is indeed fixed   (fixed in GStreamer 1.20.4) , but there is some new issue since GStreamer 1.22.0 in video4linux2 that gets fixed by -bt709 option.      I will update the README docs for that.

The "jerkiness" you see might be due to using a vnc to send X11 video to another computer?   Please explain the vnc   use some more.    If I can understand your setup, I will try to duplicate it.

**Comment by carylewis** [comment]
First off, thanks for the all of the help and engagement.

My setup is as follows:

RP 4B running PiOS 64 bit - debian bookworm

I don't want to run uxplay on the main display because I want it to run in an minimal screen environment, so I am using tigervnc to create a virtual X display (":1") and access that display via vnc viewer from a Mac Book Pro. But eventually this will be accessed via noVNC or some other window capture / broadcast methodology.

In my experiments, using -avdec:

`uxplay -avdec -vs "ximagesink display=:1" -d`

provided smoother playback on both the main display and the virtual one, but it really drives up the cpu utilization (duh), and I need to be able to do some processing on the uxplay frames, so I really want to get the GPU acceleration working.

I just got my RP 5 and will switch to that platform where there won't be any gpu acceleration, and I expect the playback to be smoother.

If I run the export GST_DEBUG=4, what specifically should I be looking for?

**Comment by fduncanh** [comment]
the new  -bt709 issue is because the AirPlay color code is now detected as 1:3:7:1 rather then 1:3:5:1
5 = "video transfer bt709", 7 = "video transfer sRGB".     

I dont know whether this is a change by Apple or in  how GStreamer reads the initial video stream.

I can get rid of the issue in GStreamer-1.24.0 by patching GStreamer, but  for the moment use -bt709 option.  The README has been modified accordingly


The DISPLAY issue is fixed for you, right?  This is now also added to the README doc.

closing now.

feel free to reopen or post new issues.

**Comment by carylewis** [comment]
Thank!On Dec 22, 2024, at 12:41 PM, fduncanh ***@***.***> wrote:﻿
the new  -bt709 issue is because the AirPlay color code is now detected as 1:3:7:1 rather then 1:3:5:1
5 = "video transfer bt709", 7 = "video transfer sRGB".
I dont know whether this is a change by Apple or in  how GStreamer reads the initial video stream.
I can get rid of the issue in GStreamer-1.24.0 by patching GStreamer, but  for the moment use -bt709 option.  The README has been modified accordingly
The DISPLAY issue is fixed for you, right?  This is now also added to the README doc.
closing now.
feel free to reopen or post new issues.
