### ISSUE TITLE
Whether UxPlay accept C++ code contribution or not

### ISSUE THREAD

**Issue by kgbook** [FDH2/UxPlay#372]
we have done some work on airplay mirror, audio stream：
- audio streaming support jitterbuffer, better performance with 2.4G WiFi network
- fix some issue

**Comment by fduncanh** [comment]
uxplay.cpp is C++

code in lib and renderers is C.

suggestions for improvements are welcome,  might reimplement in C if C++.


Would have to see what you have done.

**Comment by fduncanh** [comment]
this doesnt need action, so closing now.

please feel free to submit/propose and fixes.   C++ can be used as a basis for C implementation if needed.
