### ISSUE TITLE
Vaapisink renders in greyscale

### ISSUE THREAD

**Issue by anthonysmillie** [FDH2/UxPlay#375]
So I wanted hardware-accelerated rendering because waylandsink was struggling with my 4K monitor, so I opted for vaapisink as I have an AMD graphics card, but I run into the following issue:

- When I click to extend, it extends fine and perfectly rendered
- Within a few seconds all of the color fades until I'm left with a predominantly white/greyscale screen.
- I've tried playing with contrast, brightness, saturation etc and this makes no difference.
- I've tried -bt709 which made no difference, and my uxplay says -srgb isn't a valid option as I wanted to try -srgb no.
- Mac still sees the colors just fine as screenshots show full color.

Host OS: Arch - 6.12.4-arch1-1
UxPlay version 1.71 (Latest on AUR)
Command: `uxplay -vs "vaapisink" -as 0 -fps 60 -vsync no -s 3840x2160@60 -h265`

It works perfectly and renders in color using waylandsink but not vaapisink and I'm not sure why. It also displays in full color for around 3 seconds then slowly fades to greyscale. Happy to post whatever logs are needed.

**Comment by fduncanh** [comment]
Couldn't get a  test system working with vaaapi sink.    (a test without uxplay, just of vaapisink with gst-launch-1.0).

So not sure what your issue is.    Does your command line  work with default s  (1920x1080 and h264)?

 uxplay -vs vaapisink -as 0 -fps 60 -vsync no

**Comment by thiccaxe** [comment]
I can reproduce the behavior on vaapisink using `./uxplay -vs vaapisink -as 0 -fps 60 -vsync no`.

> "It also displays in full color for around 3 seconds then slowly fades to greyscale."
Yep, for me it is almost as if it is only the blue channel initially before fading to grayscale as well.

**Comment by fduncanh** [comment]
@anthonysmillie 

Using "export GST_DEBUG=2"  beforerunning uxplay then =4 and =6 gives progressively more information from GStreamer that might provide a clue, but there is likely too much output to look through.

If a fix is forund it would presumably involve modifying the video pipeline.
(with -vc or -vd options)

perhaps:

-vc  vaapippostproc

-vd vaapih264dec     (Or h265)

**Comment by thiccaxe** [comment]
actually I am seeing the same behavior on `gst-launch-1.0 videotestsrc ! vaapisink` so it is an upstream issue

**Comment by thiccaxe** [comment]
Gstreamer confirmed that vaapisink is deprecated. It should most likely not be uses anymore.

**Comment by fduncanh** [comment]
Here is a link to this info

https://discourse.gstreamer.org/t/setting-up-hardware-acceleration-vaapi-for-webrtc/3700

**Comment by fduncanh** [comment]
@anthonysmillie 

will close, as message from GSgtreamer is that vaapisink is obsolete/unsuported.    README doc will be updated.

However decodebin3 may invoke the hardware acceleration so try  "uxplay  -vd decodebin3" and report any results.
thanks
