### ISSUE TITLE
Stuttering on odroid n2+

### ISSUE THREAD

**Issue by brylos1** [FDH2/UxPlay#42]
Hey I bought myself an odroid n2 +. And on my device, the movie is stuttering and has a terrible lag, but the audio is ok. How do I fix it. Is there hardware support for amlogic?

**Comment by fduncanh** [comment]
Stuttering may mean it may not have  a powerful enough processor to use GStreamer for h264 video..
Have you tried https://github.com/FD-/RPiPlay ?
This has video and audio renderers which are good with RPi, so maybe also odroid

**Comment by fduncanh** [comment]
@brylos1 

UxPlay is now working well on Raspberry Pi, using gstreamer with a backport to get Video4Linux2 working for hardware video decoding by the broadcom GPU on the Pi.


I have no idea what the Odroid N2+ GPU supports,   the new option uxplay -v4l2 might work with it now. 

see https://github.com/FDH2/UxPlay/wiki/UxPlay-on-Raspberry-Pi:-success-reports:
