### ISSUE TITLE
Relation to antimof/UxPlay

### ISSUE THREAD

**Issue by Harvie** [FDH2/UxPlay#47]
I see this was forked from https://github.com/antimof/UxPlay
Is there some cooperation between these two projects? It seems both are actively developed...
Are you planning to merge new features/fixes back to antimof repo?

**Comment by Harvie** [comment]
Oh, looks like there is not too much will to continue on the other side?
https://github.com/antimof/UxPlay/issues/70

**Comment by fduncanh** [comment]
antimov is not active with this anymore, but updates from this site are now peridocally being merged as a courtesy by antimov.   The only active site is this one.
