### ISSUE TITLE
Rebroadcast the stream?

### ISSUE THREAD

**Issue by Wowfunhappy** [FDH2/UxPlay#49]
This is a blatant feature request. I think it would be cool, but feel free to ignore it. :)

Since this project is using gstreamer—and gstreamer has an [rtsp server plugin](https://github.com/GStreamer/gst-rtsp-server)—I wonder if it would be possible to add an option to rebroadcast the received AirPlay stream over RTSP? This would make it possible to run UXPlay on a headless server, and display the video on other devices in e.g. VLC Media Player.

HLS streaming would be great too for added compatibility, but it doesn't look like there's a gstreamer plugin for that, so it would probably be too much effort.

Anyway, this project is awesome, great work! Cheers!

**Comment by fduncanh** [comment]
Go for it!   I guess You would just need to use the videosink and audiosink in (video/audio)_renderer_gstreamer.c as source for further transmission. might even be easy,  Let  us know if you get it working!

**Comment by fduncanh** [comment]
why dont you experiment with using the -vs videosink and -as audiosink    to output to rtsp server etc?  (I have no idea if this would work, but...)
