### ISSUE TITLE
gldisplay "could not find or open DRM device"

### ISSUE THREAD

**Issue by nuno27** [FDH2/UxPlay#50]
Hi, I can't solve this, on RaspberryPi.

_0:00:01.124568875  9435  0x179fc60 WARN    gleglgbm gstgl_gbm_utils.c:472:gst_gl_gbm_find_and_open_drm_node: Found no matching DRM devices
0:00:01.124909969  9435  0x179fc60 ERROR   gldisplay gstgldisplay_gbm.c:394:gst_gl_display_gbm_new: could not find or open DRM device
0:00:01.133443405  9435  0x179fc60 WARN    glwindow gstglwindow.c:293:gst_gl_window_new: Could not create window. user specified (null), creating dummy window_

Full log below:
[Pastebin Link](https://pastebin.com/aQKVqra0)

**Comment by fduncanh** [comment]
This is some kind of gstreamer video  problem.       Gstreamer cannot find find a video display that It can use.   It seems to be trying all the possible plugins and nothing works.   Either your video is messed up, or GStreamer is not properly installed or both (?)

**Comment by fduncanh** [comment]
Consider trying RPiPlay https://github.com/FD-/RPiPlay  which has audio and video renderers that are specific to Pi.  (OpenMax)
UxPlay probably needs RPi4 for GStreamer to work well.

**Comment by fduncanh** [comment]
actually, I am surprised that uxplay didnt give any error message that  video could not be initialized.
You seem to have show the GST_DEBUG=2 Gstreamer error messages.
 If you run uxplay -d,  (with GST_DEBUG=0)  do you see this message

,"Initialized GStreamer video renderer"
       ?

**Comment by nuno27** [comment]
i found out why it wasn't working, i was using an ssh session insted of the terminal "on screen", now i found that that the video is super slow, but maybe cause it is an RPI2 (on RPiPlay it was fine), the audio it's fine.
I used to use RPiPlay but i wanted to stream video from apps and that is not possible on RPiPlay.
Another question of topic, can this be compatible with RHEL based linux?

**Comment by fduncanh** [comment]
RHEL:   Please Read the README     (Yes full instructions for RHEL are given)
I heard that RPi2 is not powerful enough for good quality GStreamer  (RPi4 is fine, I think)  but RPiPlay offers OMX for Pi . I would have thought you can stream video with that.
(It also has Gstreamer renderers backported from early UxPlay)
