### ISSUE TITLE
Package for Fedora

### ISSUE THREAD

**Issue by laolux** [FDH2/UxPlay#51]
Hi, I made a fork and added a spec file so this awesome project can be used on Fedora more easily.
From Fedora it can now be used with a simple ` dnf copr enable laolux/UxPlay`, followed by `dnf install uxplay`. All dependencies should be resolved automatically.
Please let me know if you are interested in keeping the spec file for generating the rpm package here, though I am quite happy to keep it separated as not so spam the original code base with packaging related commits.
Also, if you prefer the package not to be available for direct install (for example because you are afraid packaging issues would be reported here), then please tell me so and I will remove the package from copr.
However, if you like the package being easier accessible for others, I would be happy to add a note to the readme about how to install UxPlay on Fedora using the copr package.

**Comment by fduncanh** [comment]
Sounds good!  Thanks for packaging!
Note UxPlay 1.45 is just released.  (slightly improved behavior, wind closes when streaming stops, but prvious bevahior is still available as an option, plus a few internal improvements)

For the moment, I prefer not to host the rpm specs, there are just too many distributions and package managers out there!

**Comment by laolux** [comment]
Good, so I will keep my repository around. That way I can keep playing around and see if I can get automatic package updates to run whenever a new version is published. For now I just enabled notification from github so that I will hopefully not be behind for too long.

Automatically closing window is nice and works well for me.
