### ISSUE TITLE
BUG: Illegal instruction when start 

### ISSUE THREAD

**Issue by rengui01** [FDH2/UxPlay#56]
When inputting uxplay at the terminal, output
------------------------------------------
using system MAC address 04:0e:3c:**:**:**
Initialized server socket(s)
fish: Job 1, 'uxplay' terminated by signal SIGILL (Illegal instruction)
-------------------------------------------
How to solve the above problems

**Comment by fduncanh** [comment]
1. This is probably a gstreamer issue

please show the output from uxplay -d

**Comment by fduncanh** [comment]
@rengui01 
its probably not gstreamer

Please see if an earlier version UxPlay-1.45 does not  have the problem 

https://github.com/FDH2/UxPlay/archive/refs/tags/v1.45.zip

**Comment by fduncanh** [comment]
@rengui01 

since it does not happen for me, you also need to describe what system (linux type,  computer hardware,  etc,you are running on)

**Comment by rengui01** [comment]
> 

I uninstalled uxplay-git r233.8ebac4c-2 and then installed UxPlay-1.45 and the problem was solved

**Comment by rengui01** [comment]
> @rengui01
> 
> 因为它不会发生在我身上，还需要描述您正在运行的系统（Linux类型、您的硬件等）

Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.2-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Memory: 7.3 GiB of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics

**Comment by fduncanh** [comment]
Please check the current git and let me know if the problem is gone
Thanks

**Comment by fduncanh** [comment]
Oh this is an arch package? uxplay-git r233.8ebac4c-2

I don't see that number in the git commits on github

**Comment by rengui01** [comment]
reno@MyArch ~ [SIGINT]> uxplay -d
supported audio format 1: AAC-ELD 44100/2
supported audio format 2: ALAC 44100/16/2
supported audio format 3: AAC-LC 44100/2
supported audio format 4: PCM 44100/16/2 S16LE
Initialized GStreamer video renderer
using system MAC address 04:0e:3c:a3:5e:d3
Initialized server socket(s)

No problem now, would you like to see the output of uxplay -d?

**Comment by fduncanh** [comment]
No, not if its working!

Just report on 1.46 latest:

**Comment by rengui01** [comment]
> Oh this is an arch package? uxplay-git r233.8ebac4c-2
> 
> I don't see that number in the git commits on github



> Oh this is an arch package? uxplay-git r233.8ebac4c-2
> 
> I don't see that number in the git commits on github

yes i installed it on aur

**Comment by rengui01** [comment]
> Oh this is an arch package? uxplay-git r233.8ebac4c-2
> 
> I don't see that number in the git commits on github

yes i installed it on aur

**Comment by fduncanh** [comment]
Aur has a uxplay 1.46-1 listed.
latest is this  github version
https://github.com/FDH2/UxPlay/archive/refs/tags/v1.46b.zip

**Comment by rengui01** [comment]
> 



> Aur has a uxplay 1.46-1 listed. latest is this github version https://github.com/FDH2/UxPlay/archive/refs/tags/v1.46b.zip

I am using uxplay 1.46-1 and it works fine

**Comment by fduncanh** [comment]
thanks for your input
