### ISSUE TITLE
Systemd Service Requirements

### ISSUE THREAD

**Issue by uvbeenzaned** [FDH2/UxPlay#59]
I attempted to create a simple systemd service file to bring it up on startup as my personal user and it just crashes with no useful errors. Any ideas what environment the process needs to work correctly as a service? Here is my service file:

```
[Unit]
Description=UxPlay Airplay Mirror Service
After=network.target
Wants=network-online.target

[Service]
Restart=always
User=me
Type=simple
ExecStart=/usr/local/bin/uxplay -s 1920x1080@144
Environment='XDG_RUNTIME_DIR=/run/user/1000'

[Install]
WantedBy=multi-user.target
```

**Comment by fduncanh** [comment]
Sound like a nice idea. I dont know enough about this to help.   
I assume running uxplay -s 1920x1080@144 work fine ?
(default is 1920x1080@60)

You might want to test with -vs fpsdisplaysink to see what kind of framerate the streaming is at   (default maxFPS  is 30,
maybe -fps 36   (144/4) or 48 = (144/3) might help if you have a 144Hz refresh rate terminal.

**Comment by uvbeenzaned** [comment]
Thanks, I am mainly just looking to see what it takes to run as a service because it make much more sense for my use case to just have it always available. It didn't seem like 144hz was actually working on my high refresh rate monitors, it still seemed like 30fps. I will play with the settings you showed there. And yes, that command line did work fine from the shell without error. The service just seems to be missing something that the program expects. I have given it the XDG_RUNTTIME_DIR variable as you see and the service is set to run as my user but alas it crashes constantly. I will try my best to put the error I get into this issue here when I get a chance.

**Comment by fduncanh** [comment]
If you find the solution please reopen this issue (or post a new issue).  It could help others!

closing for now.

**Comment by markst** [comment]
Hey @uvbeenzaned, this seems to be working for me.

```
[Unit]
Description=%p Service
After=service.system.docker.service
Requires=network-online.service
After=network-online.service

[Service]
Type=simple
ExecStart=/bin/sh /storage/.kodi/addons/%p/bin/%p
ExecStop=/bin/sh /storage/.kodi/addons/%p/bin/stop

[Install]
WantedBy=multi-user.target
```

**Comment by monomycelium** [comment]
@markst, can you share your start and stop scripts with us? Also, is `/bin/sh` necessary for running the scripts?

**Comment by markst** [comment]
@monomycelium https://github.com/markst/plugin.audio.uxplay/blob/main/bin/plugin.audio.uxplay

**Comment by monomycelium** [comment]
@markst, looking at your file, do you think this line of code from @uvbeenzaned in the service file would be enough to set the desktop environment, or should we set the environment differently?

```
Environment='XDG_RUNTIME_DIR=/run/user/1000'
```
