### ISSUE TITLE
installed on RPI 4 server open connection but no mirroring

### ISSUE THREAD

**Issue by swingstate** [FDH2/UxPlay#63]
cloned latest build, then build and installed on a PI4 w/ 2GB on ubuntu server 21.10 impish

Build went fine, no errors
Server starts and accepts connections from local Macbook (12.3 beta) and iPhone 12 (IOS 15.4)

output in terminal looks fine: 

```
pi@ubuntu:~/UxPlay$ ./uxplay
using system MAC address dc:a6:32:01:a2:fb
Initialized server socket(s)
Accepted IPv4 client on socket 27
Local: 192.168.178.105
Remote: 192.168.178.37
Open connections: 1
Client identified as User-Agent: AirPlay/610.14.1
Accepted IPv4 client on socket 29
Local: 192.168.178.105
Remote: 192.168.178.37
Open connections: 2
raop_rtp_mirror starting mirroring
raop_rtp_mirror tcp socket closed
Connection closed for socket 27
Destroying connection
Open connections: 1
Connection closed for socket 29
Destroying connection
Open connections: 0
```

PI is connected through HDMI to 34" screen.
Although everything looks fine no content is mirrored. 

Tried through SSH and with keyboard in front of screen, same results.

RPIplay works on some server, though audio does not mirror hence wanted to use UxPlay.

Any advise?

**Comment by fduncanh** [comment]
To my knowledge, UxPlay has not been tested on RPi4, but  the RPi4 should be powerful enough for gstreamer to work OK.

To see what is going on with your setup.

(1) run uxplay -d to get explicit (RAOP) debug output.
(2) GStreamer can be debugged using
"export GST_DEBUG=2" before running uxplay
(3) repeat , using GST_DEBUG=4

Hopefully, one would be able to see what your issue is from these

**Comment by swingstate** [comment]
To me the log looks fine from what I understand. Tried again from my Macbook and there seems to be a Videostream. However, the picture on the screen does not change, I only see the ubuntu console.

CPU load is 15 - 20%, few peaks at 45% when running uxplay
Memory load is 130MB

I attached the log file. 

[uxplay-pi4-log.txt](https://github.com/FDH2/UxPlay/files/8044765/uxplay-pi4-log.txt)

**Comment by fduncanh** [comment]
Video was streaming, but not being displayed.

Then there is a TEARDOWN request.
I suppose this is you stopping the client  (clicking on "StopStreaming"?)
Or did it stop by itself?


I suspect you dont have a working GStreamer pipeline.
probably you have not installed a needed gstreamer plugin  (?)

the uxplay debug system doesnt tell you about GStreamer.
GStreamers debug is activate by 
"export GST_DEBUG=2" in the terminal window, before you run uxplay.
Then move up to GST_DEBUG=4

(which will have too much info, I'm afraid.)



 



```
raop_rtp_mirror video ntp = 1644531871848795, now = 1644531871783887, latency = -64908
raop_rtp_mirror video ntp = 1644531871882128, now = 1644531871817616, latency = -64512
raop_rtp_mirror video ntp = 1644531871915461, now = 1644531871850534, latency = -64927
raop_rtp_mirror video ntp = 1644531871948795, now = 1644531871883648, latency = -65147
raop_rtp_mirror video ntp = 1644531871982128, now = 1644531871916594, latency = -65534
raop_rtp_mirror video ntp = 1644531872015461, now = 1644531871951556, latency = -63905
raop_rtp_mirror video ntp = 1644531872048795, now = 1644531871983551, latency = -65244

Received video streaming performance info packet from client
raop_rtp_mirror tcp socket closed
httpd receiving on socket 27
conn_request

TEARDOWN rtsp://192.168.178.105/7733720095892062347 RTSP/1.0
Content-Length: 69
Content-Type: application/x-apple-binary-plist
CSeq: 18
DACP-ID: 7AE31B99A69BFEDD
Active-Remote: 3429634580
User-Agent: AirPlay/610.14.1
```

**Comment by fduncanh** [comment]
GST_DEBUG=2
only reports errors

GST_DEBUG=4 reports EVERYTHING!

**Comment by swingstate** [comment]
not sure if I got your advise 100%, but this is with "2", sounds a bit like it cannot connect to the PIs HDMI?
```

pi@ubuntu:~$ export GST_DEBUG=2
pi@ubuntu:~$ uxplay
0:00:00.265922064  1393  0x14b2e00 WARN                gleglgbm gstgl_gbm_utils.c:473:gst_gl_gbm_find_and_open_drm_node: Found no matching DRM devices
0:00:00.266035859  1393  0x14b2e00 ERROR              gldisplay gstgldisplay_gbm.c:439:gst_gl_display_gbm_new: could not find or open DRM device
0:00:00.269611998  1393  0x14b2e00 WARN                glwindow gstglwindow.c:323:gst_gl_window_new: Could not create window. user specified (null), creating dummy window
0:00:00.270202957  1393  0x1477928 WARN               glcontext gstglcontext.c:1257:gst_gl_context_create_thread:<glcontextegl0> Failed to create context
0:00:00.270336456  1393  0x14b2e00 WARN             glimagesink gstglimagesink.c:1095:_ensure_gl_setup:<sink> error: Failed to initialize egl: EGL_NOT_INITIALIZED
0:00:01.696920602  1393  0x14b2e00 WARN                 kmssink gstkmssink.c:848:gst_kms_sink_start:<video_sink-actual-sink-kms> error: Could not open DRM module (NULL)
0:00:01.696981749  1393  0x14b2e00 WARN                 kmssink gstkmssink.c:848:gst_kms_sink_start:<video_sink-actual-sink-kms> error: reason: No such file or directory (2)
0:00:01.697100545  1393  0x14b2e00 WARN                basesink gstbasesink.c:5869:gst_base_sink_change_state:<video_sink-actual-sink-kms> error: Failed to start
0:00:01.699453397  1393  0x14b2e00 WARN              ximagesink ximagesink.c:867:gst_x_image_sink_xcontext_get:<video_sink-actual-sink-ximage> error: Could not initialise X output
0:00:01.699624007  1393  0x14b2e00 WARN              ximagesink ximagesink.c:867:gst_x_image_sink_xcontext_get:<video_sink-actual-sink-ximage> error: Could not open display
0:00:01.702852908  1393  0x14b2e00 WARN             waylandsink gstwaylandsink.c:362:gst_wayland_sink_find_display:<video_sink-actual-sink-wayland> warning: Could not initialise Wayland output
0:00:01.702913704  1393  0x14b2e00 WARN             waylandsink gstwaylandsink.c:362:gst_wayland_sink_find_display:<video_sink-actual-sink-wayland> warning: Failed to create GstWlDisplay: 'Failed to connect to the wayland display '(default)''

```

**Comment by swingstate** [comment]
and log level 4, attached due to size. 

Log says "...Could not initialise Wayland output..." . That's beyond my knowledge, however I'll google that later and try to understand if that's a plugin or lib I need to install. 

[uxplay-pi4-loglevel-4.txt](https://github.com/FDH2/UxPlay/files/8044957/uxplay-pi4-loglevel-4.txt)

**Comment by fduncanh** [comment]
gstreamer tried all the videosinks it could fink to test if they worked.
none did, (the last one tried was Waylandsink for a Wayland system (the intended replacement for X11))

So in the end it created the "fakesink" video sink,  something like sending the video stream to die in /dev/null  (nowhere)!
```
:00:01.728554121  1427  0x14a6000 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:360:gst_element_factory_create: creating element "fakesink" named "fake-video-sink"
```

 Please at least see if the audio stream works.  If the client is a macbook have some youtube video with audio stream.

To see what you might be missing, what you get with
```
sudo apt list -- installed | grep -i gstreamer
```

**Comment by fduncanh** [comment]
What  video hardware does your Rpi 4 use?

**Comment by fduncanh** [comment]
maybe this is helpful?

https://qengineering.eu/install-gstreamer-1.18-on-raspberry-pi-4.html

**Comment by swingstate** [comment]
I installed the GStreamer packages by following the page you posted above.


```
$ sudo apt-get install libx264-dev libjpeg-dev

$ sudo apt-get install libgstreamer1.0-dev \
     libgstreamer-plugins-base1.0-dev \
     libgstreamer-plugins-bad1.0-dev \
     gstreamer1.0-plugins-ugly \
     gstreamer1.0-tools \
     gstreamer1.0-gl \
     gstreamer1.0-gtk3

$ sudo apt-get install gstreamer1.0-pulseaudio
```

No changes. I can pick Uxplay as Airplay target on the IPhone and connect to it but nothing is displayed or audible from the screen. If I listen to music and switch to Airplay the stream is still running in the IPhone app but no audio is coming from the Screen. 

Short logs from audio streaming test:

```
uxplay
using system MAC address dc:a6:32:01:a2:fb
Initialized server socket(s)
Accepted IPv4 client on socket 27
Local: 192.168.178.105
Remote: 192.168.178.102
Open connections: 1
Client identified as User-Agent: AirPlay/610.14.21
Accepted IPv4 client on socket 29
Local: 192.168.178.105
Remote: 192.168.178.102
Open connections: 2
ct=2 spf=352 usingScreen=0 isMedia=1  audioFormat=0x40000
start audio connection, format ALAC 44100/16/2
raop_rtp starting audio
AL lib: (EE) ALCplaybackAlsa_reset: snd_pcm_hw_params(self->pcmHandle, hp) failed: File descriptor in bad stateConnection closed for socket 29
Destroying connection
Open connections: 1
Connection closed for socket 27
Destroying connection
Open connections: 0
^CStopping...
```
Full logs:
[uxplay-loglevel4-audiostream.txt](https://github.com/FDH2/UxPlay/files/8047387/uxplay-loglevel4-audiostream.txt)

**Comment by fduncanh** [comment]
for audio the article I referenced says
```
$ sudo apt-get install gstreamer1.0-pulseaudio
```
did you do thjs?

First get audio working, then work on the video.

**Comment by fduncanh** [comment]
I assume you did do the suggested test?
```
With all GStreamer modules installed let's test the installation with $ gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink .
```

**Comment by swingstate** [comment]
I bet this is a config issue, and not hardware related. 

```
sudo apt list --installed | grep -i gstreamer

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-gstreamer-1.0/impish,now 1.18.5-1 armhf [installed,automatic]
gstreamer1.0-gl/impish,now 1.18.5-1 armhf [installed]
gstreamer1.0-gtk3/impish,now 1.18.5-1ubuntu2 armhf [installed]
gstreamer1.0-libav/impish,now 1.18.5-1 armhf [installed]
gstreamer1.0-plugins-bad/impish,now 1.18.5-1ubuntu1 armhf [installed]
gstreamer1.0-plugins-base/impish,now 1.18.5-1 armhf [installed,automatic]
gstreamer1.0-plugins-good/impish,now 1.18.5-1ubuntu2 armhf [installed,automatic]
gstreamer1.0-plugins-ugly/impish,now 1.18.5-1 armhf [installed]
gstreamer1.0-pulseaudio/impish,now 1.18.5-1ubuntu2 armhf [installed]
gstreamer1.0-tools/impish,now 1.18.5-1 armhf [installed]
gstreamer1.0-vaapi/impish,now 1.18.5-1 armhf [installed]
gstreamer1.0-x/impish,now 1.18.5-1 armhf [installed,automatic]
libgstreamer-gl1.0-0/impish,now 1.18.5-1 armhf [installed,automatic]
libgstreamer-opencv1.0-0/impish,now 1.18.5-1ubuntu1 armhf [installed,automatic]
libgstreamer-plugins-bad1.0-0/impish,now 1.18.5-1ubuntu1 armhf [installed,automatic]
libgstreamer-plugins-bad1.0-dev/impish,now 1.18.5-1ubuntu1 armhf [installed]
libgstreamer-plugins-base1.0-0/impish,now 1.18.5-1 armhf [installed,automatic]
libgstreamer-plugins-base1.0-dev/impish,now 1.18.5-1 armhf [installed]
libgstreamer-plugins-good1.0-0/impish,now 1.18.5-1ubuntu2 armhf [installed,automatic]
libgstreamer-plugins-good1.0-dev/impish,now 1.18.5-1ubuntu2 armhf [installed,automatic]
libgstreamer1.0-0/impish,now 1.18.5-1 armhf [installed,automatic]
libgstreamer1.0-dev/impish,now 1.18.5-1 armhf [installed]
```

I'll spend some time tonight to troubleshoot further and go through your comments.

**Comment by fduncanh** [comment]
first thing, do the gstreamer test:

gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink

**Comment by swingstate** [comment]
I did a fresh install with RPI OS 64Bit, installed the packages and can do the streamer test on the RPI terminal (not remotely through SSH). 
I can start uxplay and from the terminal it looks like it its accepting connections, however no audio or video makes it to the screen.

**Comment by fduncanh** [comment]
It seems that there are a lot of complicated issues right now on RPi 4B,   like 32bit vs 64 bit, Debian Bullseye vs Buster, 
changes in h264 support etc.  UxPlay is RPiPlay with improvements and fixes, and gstreamer (usually for X86_64 architecture) instead of  the OpenMax renderers that RPiPlay was created to use.  (the gstreamer support from UxPlay was backported to RPiPlay, but I think most RPiPlay users use OpenMax.)      But now OpenMax is being abandoned as obsolete in Debian-Bullseye-based distros for the Pi, and there are a lot of questions on this at the RPiPlay site.

The RPi 4  seems to have the right hardware (with built in h264 decoding) to run UxPlay well, if you can get gstreamer properly working to use it.     If you can get RPiPlay working with its gstreamer option, then you can  also run UxPlay.    I cant really help with this because I don/t  have the RPi 4 , and I now see its not a simple issue.  You need to get help from  RPi users.

**Comment by fduncanh** [comment]
> I did a fresh install with RPI OS 64Bit, installed the packages and can do the streamer test on the RPI terminal (not remotely through SSH).

This might be because ubuntu-21.10 has moved  the default display system from X11 to Wayland.   You could try to  make your RPi  4 use X11 instead of Wayland to see if that solves things.   According to the post below some love Wayland some hate it.
https://forums.raspberrypi.com/viewtopic.php?t=313685

> I can start uxplay and from the terminal it looks like it its accepting connections, however no audio or video makes it to the screen.

I'm puzzled by the "no audio"  as there were no audio errors showing up in the  GST_DEBUG.
You are sure that audio was streaming, and the volume wasn't turned down?    the uxplay -d output will show the audio packets
arriving one-by-one among the video packets.

I would say, solve the audio first, then try to solve the video issue.

**Comment by fduncanh** [comment]
Or the issues could be that you are running Wayland on an RPI 4 with only 2GB memory (?) .  Are you running 32 bit or 64 bit ubuntu? I think you need the 32 bit ubuntu for your system.    The post says something about things working well only on 4GB or 8GB systems.
[https://forums.raspberrypi.com/viewtopic.php?t=31368](https://forums.raspberrypi.com/viewtopic.php?t=313685)

**Comment by swingstate** [comment]
appreciate your support! I'll test a few things with the RPI and with VMs to see if this is RPI issue or I am doing a mistake somewhere. Suggest to close the issue.

**Comment by fduncanh** [comment]
R Pi 4 is now supported.
see the readme. (you need to patch GStreamer, until updates come)

**Comment by fduncanh** [comment]
@swingstate 
the RPi support is for Bullseye not Buster.
