### ISSUE TITLE
[BUG] X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by Delta-official** [FDH2/UxPlay#64]
When I run uxplay and I try to connect to it I get this output:
```
sudo uxplay -vs xvimagesink -n aps

(gst-plugin-scanner:104669): GLib-GObject-WARNING **: 22:18:18.381: cannot register existing type 'GstQtQuick2VideoSink'

(gst-plugin-scanner:104669): GLib-GObject-CRITICAL **: 22:18:18.381: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gst-plugin-scanner:104669): GLib-CRITICAL **: 22:18:18.381: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:104669): GStreamer-CRITICAL **: 22:18:18.381: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
using system MAC address 64:6c:80:7d:22:29
Initialized server socket(s)
Accepted IPv4 client on socket 28
Local: ---.---.--.---
Remote: ---.---.--.--
Open connections: 1
Client identified as User-Agent: AirPlay/605.1
Accepted IPv4 client on socket 30
Local: ---.---.--.---
Remote: ---.---.--.--
Open connections: 2
raop_rtp_mirror starting mirroring
error: XDG_RUNTIME_DIR not set in the environment.
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0xac00002
  Serial number of failed request:  6142
  Current serial number in output stream:  6142
```
another issue (https://github.com/antimof/UxPlay/issues/77) has been filed in the old repository referencing to the same bug and the user that experienced it has the same system configuration (Arch Linux + KDE Plasma)

**Comment by fduncanh** [comment]
I have tested a few days ago on arch with kde plasma (build from github, see README for instructions)
works perfectly with -cs xvimagesink.

One of the two versions of uxplay in AUR was bad, recently see issue #56

**Comment by Delta-official** [comment]
i downloaded uxplay from the aur package, will try to install it manually

**Comment by Delta-official** [comment]
successfully built uxplay and everything works, issue is resolved

**Comment by sacsar** [comment]
I was hitting this same issue, and also resolved it by building from source rather than installing the AUR package. The issue seems to be related to ZOOMFIX--running cmake *without* ZOOMFIX was ultimately what got me a working installation. The only other thing that's notable is that I had success building the 1.47 release, but not from master (currently [2584a55](https://github.com/FDH2/UxPlay/commit/2584a55c3dcc73c84b8975062598d071159a5dc6)). (I'll admit to not being 100% certain that I did a no-ZOOMFIX install from master, but I believe that's what I did first.)

**Comment by fduncanh** [comment]
@sacsar.   What architecture are you building on standard X86_64 or something else?  I have arch on a virtual box.   I hesitated to put it on a real partition on a  multiboot X86_64 system in case it didnt play nice with other Linux installations.

**Comment by sacsar** [comment]
Yes, x86_64. I should have mentioned I'm on Manjaro, but I don't think that makes much difference vs Arch.

Looking through the pamac history I have:
```
[2022-01-30T13:40:07-0500] [ALPM] installed uxplay (1.46-1) <--- worked fine
[upgrades to a lot of stuff on 2/5 and 2/27, but *not* uxplay]
[2022-03-02T12:51:22-0500] [ALPM] removed uxplay (1.46-1) <--- I started getting segfaults before the iPad connected
[2022-03-02T12:52:46-0500] [ALPM] installed uxplay-git (r559.23addca-1) <--- problem solved, briefly
```
The odd thing is that the move from `uxplay` to `uxplay-git` really did appear to solve things. I use uxplay while teaching on Tuesdays and Thursdays. I believe I started getting segfaults prior to connecting on 3/1, switched to `uxplay-git` on 3/2, tested it quickly that evening and then started having the BadWindow issues on 3/3. I'm afraid I don't know enough about how pamac/pacman/yay all interact/keep records to know for sure that I didn't pick up a newer commit between 3/2 and 3/3.

If I have a moment, I'll mess around building against different commits to see if I can narrow it down for you. I hope that my comment mentioning skipping `ZOOMFIX` is enough to get other folks on Arch-derivative a working build, as it does seem like an "us" problem more than a "you" problem.

**Comment by fduncanh** [comment]
I have a working build on arch in virtual box, but direct compile and AUR PKGBUILD compile ( and  an manjaro arch for rpi 4)

I'm looking at a AUR issue right now ( a crash when the client sleeps in the AUR build but not the direct build)
