### ISSUE TITLE
X Error of failed request: BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by CodeSpoof** [FDH2/UxPlay#78]
Started uxplay without arguments on RPi 3b, established screen mirroring connection and it crashed immeadiatly after a short flash of a window opening on the Pi. Sometimes mirroring the gallery from my ipad works fine, but with extreme latency
```
Initialized server socket(s)
Accepted IPv4 client on socket 30
Local: 192.168.178.35
Remote: 192.168.178.111
Open connections: 1
Client identified as User-Agent: AirPlay/605.1
Accepted IPv4 client on socket 32
Local: 192.168.178.35
Remote: 192.168.178.111
Open connections: 2
raop_rtp_mirror starting mirroring
Begin streaming to GStreamer video pipeline
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0xe007d8
  Serial number of failed request:  179884
  Current serial number in output stream:  179884
```

**Comment by fduncanh** [comment]
did you follow instructions in #70 ?

For software decoding (poor latency) use uxplay -rpi -avdec   (on current uxplay 1.48)

**Comment by fduncanh** [comment]
on Pi use Open GL  ( -vs glimagesink)   the -rpi option does this.

First get uxplay -rpi -avdec working (with poor latency) then do the [v4l2](https://github.com/FDH2/UxPlay/wiki/Gstreamer-Video4Linux2-plugin-patches) from the UxPlay Wiki

**Comment by fduncanh** [comment]
The patch is now in recent R Pi  OS update  to gstreamer1-plugins-good.

If you have updated or patched gstreamer and still have errors, open a new Issue.
closing
