### ISSUE TITLE
Start UxPlay as a service?

### ISSUE THREAD

**Issue by ShadityZ** [FDH2/UxPlay#80]
I am making a TV box using an RPi 4 that I have got.

I've managed to figure out the right parameters to get UxPlay working, but I have been trying to figure out how to run UxPlay as a service, so it runs at start up with the arguments I give it. 

Also, I have made it so Kodi starts up at boot, as soon as the desktop and required dependencies load. I was thinking, would there be a way to modify UxPlay to make it so that it stops Kodi before establishing the connection? To start Kodi, I have used the autostart menu in XFCE.

BTW, I am running TwisterOS. (Based off Raspbian Buster 32-bit)
Any help is appreciated.

**Comment by qrkourier** [comment]
You can manage processes on Debian Buster with systemd. You need a service unit definition file that describes the process and its environment in the right directory, then you can do `systemctl daemon-reload` to load that configuration. Then you can use the standard `systemctl` commands to control the process, and `journalctl` to view the log emissions to the journal.

**Comment by fduncanh** [comment]
seems that there is nothing more to say?

**Comment by monomycelium** [comment]
@ShadityZ, can I take a look at your service file? I'm wondering what you have to set the environment.
