### ISSUE TITLE
no audio comes out

### ISSUE THREAD

**Issue by TapsHTS** [FDH2/UxPlay#84]
Hi ! Any audio comes out but the mirror works:

I use a Raspberry PI 3B+ and I start with `uxplay -rpi -vs kmssink -n "TV Salon" -nh`

**Comment by fduncanh** [comment]
Do you have working audio with any other app?

I found that only the "pi" user had working audio, and just lately new installations  discourage using a "pi" account.  This is nothing to do with uxplay.

I think pulse audio needs to be installed.

**Comment by TapsHTS** [comment]
It works ! Thank you !
I have another question: when my iPhone is vertical everything works fine but when I put it horizontal, to watch a video... it disconnects. I guess that's not normal?

**Comment by fduncanh** [comment]
The "official" RPi update for gstreamer1.0-plugins-good has some but not all of the backport from GStreamer-1.21 needes to fix things.   The person I was in contact with at RaspberryPi  has passed the remaing part of the fix on for future release, but it hasnt happen yet.       This is the fix for what happens when you rotate (change the shape of the image) .   Follow the simple procedure in the UxPlay wiki https://github.com/FDH2/UxPlay/wiki/Gstreamer-Video4Linux2-plugin-patches
to patch libgstvideo4linux2.so to fix the issue.

**Comment by TapsHTS** [comment]
I have an error when i follow the procedure in the UxPlay wiki: 
`sudo apt-get build-dep gstreamer1.0-plugins-good` give:
```
Reading package lists... Done
Picking 'gst-plugins-good1.0' as source package instead of 'gstreamer1.0-plugins-good'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 builddeps:gst-plugins-good1.0 : Depends: meson (>= 0.48) but it is not installable
                                 Depends: xvfb
                                 Depends: libcairo2-dev (>= 1.10.0) but it is not going to be installed
                                 Depends: libcaca-dev but it is not installable
                                 Depends: libspeex-dev (>= 1.1.6) but it is not installable
                                 Depends: libshout3-dev but it is not installable
                                 Depends: libjpeg-dev but it is not installable
                                 Depends: libaa1-dev (>= 1.4p5) but it is not installable
                                 Depends: libflac-dev (>= 1.1.4) but it is not installable
                                 Depends: libdv4-dev but it is not installable or
                                          libdv-dev but it is not installable
                                 Depends: libxdamage-dev but it is not installable
                                 Depends: libxext-dev but it is not installable
                                 Depends: libxfixes-dev but it is not installable
                                 Depends: libxv-dev but it is not installable
                                 Depends: libgdk-pixbuf2.0-dev (>= 2.8.0) but it is not installable
                                 Depends: libgtk-3-dev (>= 3.15) but it is not going to be installed
                                 Depends: libtag1-dev (>= 1.5) but it is not installable
                                 Depends: libwavpack-dev (>= 4.60) but it is not installable
                                 Depends: libsoup2.4-dev (>= 2.48) but it is not installable
                                 Depends: libbz2-dev but it is not installable
                                 Depends: libjack-jackd2-dev but it is not installable
                                 Depends: libvpx-dev (>= 1.5) but it is not installable
                                 Depends: libmp3lame-dev but it is not installable
                                 Depends: libmpg123-dev (>= 1.13) but it is not installable
                                 Depends: libtwolame-dev (>= 0.3.10) but it is not installable
                                 Depends: qtbase5-dev but it is not installable
                                 Depends: qtdeclarative5-dev but it is not installable
                                 Depends: libqt5x11extras5-dev but it is not installable
                                 Depends: libraw1394-dev (>= 2.0.0) but it is not installable
                                 Depends: libiec61883-dev (>= 1.0.0) but it is not installable
                                 Depends: libavc1394-dev but it is not installable
                                 Depends: libv4l-dev but it is not installable
                                 Depends: libgudev-1.0-dev (>= 147) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
If you have a video tutorial, I would like to but I will wait for the release of the update. Do you have a date?

**Comment by fduncanh** [comment]
You havent described what  exactly you are doing.    
What Operating system are you using?    The above shows something is quite messed up.
 The instructions are for Raspberry Pi OS (Bullseye) 
Did you follow edit /etc/apt/sources.list to activate deb-src and then run atp-get update?
what does 
```
uname -a
```
report?

**Comment by TapsHTS** [comment]
Report is : `Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`

**Comment by TapsHTS** [comment]
`/etc/apt/sources.list`:

![image](https://user-images.githubusercontent.com/61658427/162702897-7c5da020-34f6-4a5a-9ece-c38735d6e421.png)

**Comment by TapsHTS** [comment]
Ok I'm dumb...

**Comment by fduncanh** [comment]
I see you still have the 5.10 kernel: good! 
If you are using the "Desktop" RPi OS version with X11 , you should prevent an update to the 5.15 kernel with
```
sudo apt-mark hold raspberrypi-kernel
```
see issue #83.
The new 5.15 kernel breaks something (probably OpenGL ).     (This doesn't apply to the "Lite version where -vs kmssink is used)
You can release the hold at a later time when 5.15 is working correctly .

**Comment by TapsHTS** [comment]
I don't use the Desktop, I'm in the RPi OS Lite

**Comment by fduncanh** [comment]
you have a broken system  google for solutions to this error message you got.

```
Unable to correct problems, you have held broken packages.
```

sudo apt-get upgrade
sudo apt-get dist upgrade

might help.

**Comment by fduncanh** [comment]
closing, please open a new issue if needed.
