### ISSUE TITLE
UxPlay service works and initializes server socket for AirPlay mirror, but "unable to connect" via AirPlay on iPhone

### ISSUE THREAD

**Issue by DPatel0211** [FDH2/UxPlay#88]
Attached are screenshots of uxplay running on terminal (alacritty) and appearing on my iPhone to describe the issue, would appreciate any tips or advice on the matter:
![image](https://user-images.githubusercontent.com/43239911/164589428-3d49df81-8834-4585-a421-0c7c9aa833b9.png)
![image](https://cdn.discordapp.com/attachments/589578335684919296/966900513734025266/IMG_3264.png)

**Comment by fduncanh** [comment]
Try looking at "Troubleshooting"  in the README.

First guess,  (as explained in README)  you have a firewall run ning on the linux server.

try
```
sudo systemctl status firewalld
```

if its running, that explains it.
either turn it off
```
sudo systemctl stop firewalld
```
or (prefeably) open some ports for uxplay, and use the uxplay -p ...  option to use them

see the uxplay README.

**Comment by fduncanh** [comment]
was issue solved? 
closing as no further info was given
