### ISSUE TITLE
Debian Sid package: Fails to stream with "GStreamer error: Internal data stream error"

### ISSUE THREAD

**Issue by fduncanh** [FDH2/UxPlay#90]
This is a repost of issue #21 by @scovit

(@scovit please post new issues: I posted your issue  again here)

* "GStreamer error: Internal data stream error" is a very generic error, usually when GStreamer fails to find working plugins.

* A package of UxPlay for Debian Sid exists (produced by a third party, see issue #22 )

@scovit reports "GStreamer Error: Internal data stream error":
Steps to reproduce:

    install debian sid
    activate experimental repository (add deb http://deb.debian.org/debian experimental main to sources.list)
    apt update
    apt -t experimental install uxplay

**Comment by scovit** [comment]
Than you for this help,
this are the output of those commands:
```
$ uname -a
Linux maleo 5.16.0-6-amd64 #1 SMP PREEMPT Debian 5.16.18-1 (2022-03-29) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux bookworm/sid \n \l

$ apt list --installed | grep gstreamer

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-gstreamer-1.0/testing,now 1.20.1-1 amd64 [installed,automatic]
gstreamer1.0-adapter-pulseeffects/testing,now 4.8.4-1 amd64 [installed]
gstreamer1.0-alsa/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-autogain-pulseeffects/testing,now 4.8.4-1 amd64 [installed]
gstreamer1.0-clutter-3.0/testing,now 3.0.27-2+b1 amd64 [installed]
gstreamer1.0-convolver-pulseeffects/testing,now 4.8.4-1 amd64 [installed]
gstreamer1.0-crystalizer-pulseeffects/testing,now 4.8.4-1 amd64 [installed]
gstreamer1.0-espeak/testing,now 0.5.0-1 amd64 [installed]
gstreamer1.0-fdkaac/testing,now 1.18.4-3 amd64 [installed]
gstreamer1.0-gl/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-gtk3/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-libav/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-nice/testing,now 0.1.18-2 amd64 [installed]
gstreamer1.0-omx-bellagio-config/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-omx-generic-config/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-omx-generic/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-opencv/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-packagekit/testing,now 1.2.5-3 amd64 [installed]
gstreamer1.0-pipewire/testing,now 0.3.50-1 amd64 [installed]
gstreamer1.0-plugins-bad-apps/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-plugins-bad/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-plugins-base-apps/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-plugins-base/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-plugins-good/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-plugins-rtp/testing,now 1.14.4.1 amd64 [installed]
gstreamer1.0-plugins-ugly/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-pocketsphinx/testing,now 0.8+5prealpha+1-14 amd64 [installed]
gstreamer1.0-pulseaudio/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-python3-plugin-loader/testing,now 1.20.1-1+b1 amd64 [installed]
gstreamer1.0-qt5/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-rtsp/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-tools/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-vaapi/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-wpe/testing,now 1.20.1-1 amd64 [installed]
gstreamer1.0-x/testing,now 1.20.1-1 amd64 [installed]
libgstreamer-gl1.0-0/testing,now 1.20.1-1 amd64 [installed,automatic]
libgstreamer-opencv1.0-0/testing,now 1.20.1-1 amd64 [installed,automatic]
libgstreamer-plugins-bad1.0-0/testing,now 1.20.1-1 amd64 [installed,automatic]
libgstreamer-plugins-base1.0-0/testing,now 1.20.1-1 amd64 [installed,automatic]
libgstreamer-plugins-base1.0-dev/testing,now 1.20.1-1 amd64 [installed]
libgstreamer1.0-0/testing,now 1.20.1-1 amd64 [installed]
libgstreamer1.0-dev/testing,now 1.20.1-1 amd64 [installed]


```

**Comment by fduncanh** [comment]
you seem to have all the gstreamer packages installed.

In any case, I saw it worked, at least on my system.


(1) try to force software decoding with uxplay -avdec  (sometime vaapi is the problem, with some nonfree stuff missing  in Debian)
try various videosinks  (-vs glimagesink  -0vs gtksink -vs ximagesink -vs xvimagesink etc)


gstreamer debugging with

export GST_DEBUG=2   (or 4) may give a clue

**Comment by fduncanh** [comment]
from the README "Troubleshooting section:

Other reported problems are connected to the GStreamer VAAPI plugin (for hardware-accelerated Intel graphics, but not NVIDIA graphics). Use the option "-avdec" to force software h264 video decoding: this should prevent autovideosink from selecting the vaapisink videosink. Alternatively, find out if the gstreamer1.0-vaapi plugin is installed, and if so, uninstall it. (If this does not fix the problem, you can reinstall it.)

There are some reports of other GStreamer problems with hardware-accelerated Intel HD graphics. One user (on Debian) solved this with "sudo apt install intel-media-va-driver-non-free". This is a driver for 8'th (or later) generation "*-lake" Intel chips, that seems to be related to VAAPI accelerated graphics.

If you do have Intel HD graphics, and have installed the vaapi plugin, but -vs vaapisink does not work, check that vaapi is not "blacklisted" in your GStreamer installation: run gst-inspect-1.0 vaapi, if this reports 0 features, you need to export GST_VAAPI_ALL_DRIVERS=1 before running uxplay, or set this in the default environment.

**Comment by fduncanh** [comment]
@scovit 
was this solved?
should this issue be closed

**Comment by fduncanh** [comment]
closing, in the absence of new information.
