### ISSUE TITLE
Integration with desktop manager

### ISSUE THREAD

**Issue by librarianmage** [FDH2/UxPlay#97]
I don't know what information is fed from the playing device, but it would be neat if my desktop (GNOME) would show what was playing and if I could control the audio with my keyboard.

**Comment by fduncanh** [comment]
This is a big feature request.   What Uxplay mainly does is negotiate with the Apple device, and  decrypt what Apple sends in encrypted form (video and audio) and pushes  the video and audio streams with timestamps into gstreamer which takes it from there.

If audio-only ALAC apple lossless audio is being sent, there is metadata and cover-art that is sent  and right now is not displaye,
and just discarded.
In principle, if that could be displayed with gstreamer it could be used,  or maybe it could be displayed using the terminal.

After starting, Uxplay doesnt accept any keyboard input (except ctrl-c to shut it down), and neither does gstreamer.
In  principle a gui interface as a front end to gstreamer could be possible.

It would require someone motivated to fork UxPlay and work on it......

**Comment by fduncanh** [comment]
Feature request.  closing as it won't happen (except as a fork) sorry!

(When I have time , I'll see if  any  of the ALAC audio-only metadata line  music description might be made visible on the terminal).

**Comment by fduncanh** [comment]
coverart can also be displayed with the -ca <file> option. see the README
