### ISSUE TITLE
How to start uxplay on a remote host (like raspberry pi)  with ssh

### ISSUE THREAD

**Issue by fduncanh** [FDH2/UxPlay#98]
This answers issue http://github.com/antimof/UxPlay#92

To start uxplay on a remote host (e.g. a raspberry pi) by ssh:

```
ssh user@raspberrypi
export DISPLAY=:0
nohup uxplay [options] &
```
 DISPLAY=:0 displays the video (and  renders sound) on the remote host.

nohup = "no hang-up" keeps uxplay alive when the ssh session is terminated.

The terminal output will be saved to nohup.out on the remote host.

maybe you can send it to /dev/null instead ?  
checkout man nohup.

**Comment by monomycelium** [comment]
Thank you for that swift response. It works just like I wanted it to. Is there a way I can start UxPlay as a Linux service or start it automatically?

**Comment by fduncanh** [comment]
It was a good question.  I added the answer to the README
see #59
